import type { DistractorMap } from "./index";

const kingdomOfWrenlyDistractors: DistractorMap = {
  "kw-01": [
    ["Lucas is the twelve-year-old prince of Wrenly, and Clara is his cousin, the daughter of a visiting duke.", "Lucas is the young stable boy of Wrenly, and Clara is the princess, daughter of King Caleb and Queen Tasha, who rule together from the castle overlooking the harbor."],
    ["King Caleb's royal crown goes missing, and Queen Tasha promises a grand feast to whoever finds it.", "A rare ruby necklace goes missing from the treasury, and the royal advisor offers gold to whoever finds it."],
    ["They travel across Wrenly to Silvertown (the port town), Thornwood (the land of knights), Flatfrost (the land of giants), and the Stone Forest (home of the gnomes).", "They travel only within the castle grounds, searching every tower, garden, moat, and hidden passage for three long days before giving up and finally asking the royal wizards of Hobsgrove for help."],
    ["They want to win the reward money so Clara's family can afford a bigger house near the castle gates by autumn.", "They want to prove to King Caleb that they are responsible enough to be trusted with real royal duties, even though they are still just children."],
    ["It introduces a rivalry between Lucas and his older brother, Prince Edmund, that continues to cause growing tension throughout many of the later books in the series.", "It introduces the Witch of Bogburp as a recurring villain who tries to stop Lucas and Clara at every turn throughout the series."],
  ],
  "kw-02": [
    ["A silver egg washes ashore near Mermaid's Cove, and a young sea dragon hatches from it.", "An ancient egg is unearthed in the Stone Forest, and a golden dragon emerges when it cracks open."],
    ["King Caleb declares that the special dragon belongs to Clara, who is thrilled and names it right away.", "King Caleb declares that the dragon must stay wild in Crestwood forever, since dragons shouldn't be allowed to live inside the castle walls."],
    ["The dragon, later named Ruskin, wanders off and gets lost.", "The dragon, later named Ruskin, refuses to eat for days."],
    ["They need moonflowers, which only bloom at night in the swamps of Bogburb.", "They need frost lilies, which only grow high in the icy mountains of Flatfrost."],
    ["The trolls of Burth refuse to let anyone pick the berries without first solving one of their notoriously tricky riddles, which can take hours to work out.", "The berries only ripen once a year during the coldest week of winter, so Lucas and Clara worry they've already missed their only chance until next year."],
  ],
  "kw-03": [
    ["Reports of a ghost ship appearing near the harbor every foggy night.", "Warnings of a whirlpool swallowing fishing boats close to the shore."],
    ["She is a retired ship captain who taught Lucas to swim every summer since he was small, and she once told him about surviving a terrible storm at sea near Silvertown.", "She is Clara's aunt who lives by the docks, and she once told him a story about a mermaid who saved her life."],
    ["King Caleb is terrified of the rumors and forbids anyone from going near the water, while Lucas sneaks out anyway.", "King Caleb wants to hunt the monster down immediately, while Lucas argues they should try to talk to it first."],
    ["They discover the creature is guarding a sunken ship full of treasure and doesn't want anyone near it.", "They discover the creature is actually searching for its lost baby somewhere along the coastline."],
    ["Ruskin stays behind at the castle the entire time, too afraid of the water to help at all.", "Ruskin accidentally causes more trouble by scaring away the very creature Lucas is trying to find."],
  ],
  "kw-04": [
    ["It has been bitterly cold for six whole days, and the rivers are in danger of freezing solid overnight.", "Thick fog has rolled in for six whole days, and ships are in danger of wrecking along the coastline."],
    ["He suspects the trolls of Burth, believing they used stolen dragon scales to summon the storm.", "He suspects a jealous nobleman from a rival province, believing the man secretly hired a sorcerer to ruin the kingdom's entire harvest."],
    ["She is a witch who offers to stop the rain in exchange for Ruskin's friendship forever.", "She is a witch who offers to stop the rain only if Lucas gives up his place as prince."],
    ["They want to ask her to teach them a spell that could protect the castle.", "They want to warn her that the king plans to banish her from the kingdom."],
    ["She tells them to bring her three drops of rainwater collected at midnight to reverse the curse.", "She tells them to find a four-leaf clover growing somewhere in the Stone Forest to break the spell."],
  ],
  "kw-05": [
    ["Lucas and Ruskin accidentally set fire to the castle's grand tapestries, getting them both in trouble.", "Lucas and Ruskin accidentally knock over the queen's favorite fountain, getting them both in trouble."],
    ["As punishment, they are sent to apologize personally to every servant in the castle for the mess they made.", "As punishment, they are sent to help the trolls of Burth rebuild a bridge they accidentally damaged."],
    ["They have to help Ruskin learn to walk quietly across the ice so he doesn't wake the sleeping giants below.", "They have to help Ruskin learn to share his food with the other young dragons nearby."],
    ["They learn that the giants secretly wish they could leave Flatfrost and live somewhere warmer.", "They learn that the giants have been feuding with the trolls of Burth for generations."],
    ["If Ruskin doesn't show better training and control, he could lose his fire-breathing ability.", "If Ruskin doesn't show better training and control, Lucas could lose his place as prince."],
  ],
  "kw-06": [
    ["Clara has always wanted to learn magic from the wizards, and she invites Prince Lucas to watch her first lesson.", "Clara has always wanted to ride a dragon into battle, and she invites Prince Lucas to help her train."],
    ["It is a grove of stone pillars and arches formed long ago by an ancient, powerful earthquake.", "It is a grove of stone pillars and arches formed by dragons breathing fire onto solid rock."],
    ["She is Lucas's visiting cousin, and at first she acts shy and refuses to speak to anyone at all.", "She is Clara's visiting cousin, and at first she acts jealous of Clara's friendship with Lucas."],
    ["Her puppy gets stolen by a mischievous goblin who lives deep in the forest nearby.", "Her puppy falls into an underground river and is swept away."],
    ["She realizes that she would rather live in the Stone Forest with the gnomes than return to her own kingdom.", "She realizes that she wants to become a gem-cutter herself instead of inheriting her family's throne."],
  ],
  "kw-07": [
    ["The kingdom's Harvest Festival, where farmers race, fairies dance, and wizards perform for the crowd.", "The kingdom's coronation ceremony, where every island sends a gift to honor the royal family."],
    ["Sir Hugh is the newest recruit among the Spires, and Gilbert is the tournament's head judge.", "Sir Hugh is King Caleb's personal bodyguard sworn to protect the royal family, and Gilbert is a visiting prince from Hobsgrove."],
    ["He declares that only nobles can enter the tournament, which makes Clara determined to prove him wrong.", "He declares that Clara is too young to compete, which makes Clara determined to prove him wrong."],
    ["She is determined to become Sir Hugh's official squire and personal trainee instead of competing in the tournament herself.", "She is determined to convince the head judges to let Ruskin compete alongside the armored knights."],
    ["It challenges the idea that only trolls can ever be truly strong, showing instead that dragons deserve just as much respect and admiration.", "It challenges the idea that tournaments should always be won through raw strength alone, showing that kindness and cleverness matter just as much."],
  ],
  "kw-08": [
    ["A gust of wind flips the raft over and tosses Lucas into the waves.", "Ruskin bumps the raft while diving and knocks Lucas overboard."],
    ["He catches a glimpse of a sunken pirate ship filled with old chests, glittering coins, and jewels.", "He catches a glimpse of a glowing underwater cave filled with strange, luminous fish."],
    ["He tells Lucas that the mermaids are actually quite dangerous to humans and should always be avoided at all costs.", "He tells Lucas that the mermaids used to be enemies of Wrenly, long before Lucas was born."],
    ["Lucas takes his father's advice completely to heart and stops thinking about the mermaids entirely.", "Lucas decides to tell the whole kingdom about the mermaids so everyone in Wrenly can finally meet them too."],
    ["Lucas's fear of the open sea pulls against his desire to prove himself brave to his father.", "Clara's jealousy of the beautiful mermaids pulls hard against her deep loyalty to her best friend Lucas."],
  ],
  "kw-09": [
    ["He does not want to attend his etiquette lessons, preferring to practice sword fighting instead.", "He does not want to sit through the royal ball, preferring to spend the evening with Ruskin instead."],
    ["A retired knight named Rowan visits and tries to convince Lucas that real magic lies in swordsmanship.", "A wandering healer named Petra visits and tries to convince Lucas that real magic lies in medicine."],
    ["He tells of Queen Elara and her knight Sir Percy, and how a raging fire threatening their entire village was finally calmed by his singing alone.", "He tells of a lonely giant living in the mountains, and how his crying was soothed by a lullaby William once played."],
    ["They stumble upon a group of lost travelers, and Lucas learns firsthand how music can lift people's spirits.", "They stumble upon Ruskin stuck in a ravine, and Lucas learns firsthand that music can calm a frightened dragon."],
    ["He resolves to give up his music lessons, deciding swordsmanship suits him better after all.", "He resolves to invite William to become the castle's permanent court musician."],
  ],
  "kw-10": [
    ["He wishes for a new pet dragon, not realizing Ruskin might get jealous.", "He wishes for Clara to become a princess, not realizing she'd rather stay as she is."],
    ["The gnomes' gemstones have mysteriously lost their glow, and no one knows what happened to them.", "The wizards' spellbooks have mysteriously vanished from Hobsgrove, and no one knows what happened to them."],
    ["They ask Grom the wizard for help, and he reveals that a mischievous goblin has been stealing the berries.", "They question the trolls themselves, who insist a flock of hungry birds has been eating the berries at night."],
    ["They scatter berries along the beach at Silvertown and wait patiently for hours inside a nearby fishing boat.", "They leave a trail of berries leading up to the castle gates and watch from a tower window."],
    ["They must convince the young pegasus to stay in Wrenly and become the kingdom's new guardian.", "They must teach the young pegasus how to fly again after it injured its wing in a storm."],
  ],
  "kw-11": [
    ["A sudden storm turns almost all the fairies to stone, leaving only one fairy unharmed.", "A jealous sorcerer traps almost all the fairies in tiny glass jars, leaving only one free."],
    ["Falsk is the one remaining fairy, and she is known for being unusually shy around strangers.", "Falsk is the one remaining fairy, and she is known throughout Primlox for her beautiful singing."],
    ["They must work with Falsk to brew a potion strong enough to break the spell.", "They must work with Falsk to convince the king that fairies deserve his protection."],
    ["Because Falsk once served an enemy kingdom, they worry she might secretly be working against Wrenly.", "Because Falsk refuses to explain how the spell was cast, they worry she might have caused it herself."],
    ["It shows that fairies are naturally untrustworthy creatures who should always be watched carefully by outsiders.", "It shows that the truth doesn't matter nearly as much as being brave enough to help your friends when it truly counts the most in the end."],
  ],
  "kw-12": [
    ["Deer have stopped grazing and rivers have begun flowing backward because a mysterious magic is disturbing Trellis.", "Trees have stopped growing and flowers have wilted overnight because a mysterious magic is disturbing Trellis."],
    ["They team up with Grom the wizard to face whatever dark magic is disturbing Trellis.", "They team up with the gnomes of the Stone Forest, who know the woods better than anyone."],
    ["A vengeful ghost — an enemy that is difficult to fight because it can pass through walls unseen.", "An enormous, invisible beast — an enemy that is difficult to fight because no one can ever see it coming."],
    ["It represents an ancient curse placed on the forest generations before Lucas was even born.", "It represents the sorcerer's loneliness after being abandoned by his family as a child."],
    ["By trapping it inside an old enchanted mirror that Grom the wizard just happens to be carrying with him that day.", "By having Ruskin burn it away completely with one powerful, well-aimed blast of dragon fire."],
  ],
  "kw-13": [
    ["The Spires are an elite council of wizards, and they currently have only nine members.", "The Spires are a secret order of dragon riders, and they currently have only seven members."],
    ["They are searching for a replacement after one of their oldest and most respected knights retired quite unexpectedly last winter.", "They are searching for someone strong enough to finally break an ancient curse that was placed on their order generations ago."],
    ["The winner must show speed, strength, and perfect swordsmanship.", "The winner must show loyalty, patience, and skill with a bow."],
    ["She decides to help judge the special contest instead of competing in it herself.", "She decides to train Lucas for the contest instead of entering it on her own."],
    ["Because the winner will be given command of the entire royal army for a full year afterward, answering only to the king himself.", "Because the losing competitors are traditionally banished from the kingdom of Wrenly forever, never allowed to return home again."],
  ],
  "kw-14": [
    ["Footsteps echo down empty hallways, portraits seem to change expression, and cold winds sweep through locked rooms.", "Dishes rattle in the kitchen at night, shadows move along the walls, and whispers drift through the throne room."],
    ["They become convinced a troll has secretly moved into the castle's basement.", "They become convinced Grom the wizard is testing a new spell on the castle."],
    ["They must warn the king before the ghost frightens the staff away.", "They must solve the whole mystery before the royal ball starts."],
    ["The ghost is friends with Grom, the wizard, though he swore never to reveal the secret.", "The ghost is friends with a young stable hand who has kept the secret for years."],
    ["They have to uncover an old family feud from long ago and team up with Grom the wizard to finally calm the restless ghost down.", "They have to uncover a buried treasure hidden somewhere nearby and team up with the trolls of Burth to find it before anyone else does."],
  ],
  "kw-15": [
    ["They find an injured fox kit, alone and shivering beneath a fallen tree.", "They find an abandoned baby griffin, alone and unable to fly."],
    ["They live deep underground in hidden caves and rarely surface, so the only proof of them is scattered fur and claw marks.", "They roam only during the coldest winter storms and vanish by spring, so the only proof of them is frozen tracks in the snow."],
    ["Sir Hugh the knight accompanies them, ready to protect them from any danger.", "Nanny Louisa accompanies them, since she once lived near the forest of Burth."],
    ["They discover that the wolves are actually loyal to Grom the wizard, who has trained them secretly.", "They discover that the wolves actually have magical powers that let them turn completely invisible whenever they want."],
    ["A rival pack of wolves — Lucas and Clara realize they need to protect the family from other wolves.", "A terrible sickness — Lucas and Clara realize they need to find medicine before the pups fall ill."],
  ],
  "kw-16": [
    ["The Whispering Cave — a strange, echoing tunnel hidden beneath the cliffs of Silvertown, carved by the sea long ago.", "The Sunken Spire — a strange, crumbling tower hidden beneath the waves near Mermaid's Cove, built by an ancient king."],
    ["Ruskin accidentally wanders through the Dream Portal and gets trapped inside.", "Ruskin is cursed by the Witch of Bogburp after flying too close to her treehouse."],
    ["They must risk asking the Witch of Bogburp for a counter-spell to save him.", "They must risk traveling to Hobsgrove to beg the wizards for their help."],
    ["It is somehow linked to Ruskin's own mind — and it can only ever be closed if Ruskin faces his very worst fear.", "It is somehow tied to the moon's cycle — and it only opens once every hundred years at midnight."],
    ["They need a rare potion from the trolls of Burth to fight back against the portal's magic.", "They need the help of every wizard in Hobsgrove to fight back against the portal's power."],
  ],
  "kw-17": [
    ["They were driven from their homeland and forced to live underground as a result.", "They were tricked by the wizards into signing away their claim to Trellis as a result."],
    ["A group of goblins have stolen the wizards' spellbooks, hoping to learn magic for themselves.", "A group of goblins have trapped the wizards inside Hobsgrove, demanding an apology from the king."],
    ["They meet an old goblin elder who wants to negotiate peacefully instead of holding a grudge.", "They meet a goblin who used to work secretly for the wizards before the Goblin Battles began."],
    ["They must decide whether to tell King Caleb about the goblins before trying to rescue anyone.", "They must decide whether Ruskin is strong enough to fight the goblins if things go wrong."],
    ["That old magic, once lost long ago, can never truly be restored again no matter how hard anyone searches for it.", "That wizards and goblins are destined to be bitter enemies forever, no matter what anyone ever tries to do about it."],
  ],
  "kw-18": [
    ["They meet a young wizard practicing a spell he hasn't mastered yet.", "They meet Grom the wizard testing a brand-new potion on Ruskin."],
    ["The spell makes the two friends shrink down to the size of mice.", "The spell makes the two friends completely invisible to everyone else."],
    ["They must find a way to switch back before the witch's teacher returns.", "They must find a way to switch back before the royal ball begins that evening."],
    ["If they don't undo it before midnight, they will slowly begin to forget their own memories.", "If they don't undo it before midnight, the witch-in-training will lose her magic for good."],
    ["It's a mystery adventure where Lucas and Clara must track down the witch before she disappears for good.", "It's a lighthearted comedy where Lucas and Clara must convince the entire castle staff that nothing strange happened at all that day."],
  ],
  "kw-19": [
    ["Trolls live in the Stone Forest, and all of their tools have suddenly gone missing overnight.", "Wizards live in the Stone Forest, and all of their spellbooks have suddenly turned blank."],
    ["They team up with Grom the wizard, who suspects a curse has been placed on the forest.", "They team up with the Witch of Bogburp, who claims she knows how to restore the gems' shine."],
    ["The gems power the lanterns that light the gnomes' winding tunnels day and night, so losing them would leave the tunnels completely dark.", "The gems are traded with the wizards of Hobsgrove for food and supplies, so losing their value could leave the gnomes hungry all winter."],
    ["They must find a way to convince the gnomes to move to a safer home.", "They must find the thief who has been stealing the gnomes' gems."],
    ["It shows how Lucas is finally ready to take over ruling the entire kingdom on his own, without his father's constant guidance.", "It shows how the gnomes eventually decide to leave the Stone Forest behind for good and settle somewhere new near Hobsgrove."],
  ],
  "kw-20": [
    ["Rumors of a sea monster spread after strange wreckage washes up near the docks.", "Rumors of a curse spread after the harbor's fish suddenly vanish overnight."],
    ["They are asked to guard a rare and ancient treasure chest recovered from a shipwreck.", "They are asked to look after an injured young griffin found near the cliffs."],
    ["At first they are frightened of it and want to send it back to wherever it came from.", "At first they assume it must belong to the mermaids and try to return it to the sea."],
    ["They learn that the phoenix has been secretly spying on them for the missing pirates.", "They learn that the phoenix can only ever be fully trusted once it has bonded completely with its rightful owner."],
    ["They are trying to figure out who stole the royal ship and why the phoenix appeared right after.", "They are trying to figure out whether Silvertown is safe and whether the phoenix should stay there."],
  ],
};

export default kingdomOfWrenlyDistractors;
