import type { DistractorMap } from "./index";

const kingdomOfWrenlyDistractors: DistractorMap = {
  "kw-01": [
    ["Lucas is the king's nephew, and Clara is a young palace guard.", "Lucas is a stable boy, and Clara is a visiting duchess."],
    ["A royal sword goes missing, and Queen Tasha offers the reward.", "The crown itself is stolen, and King Caleb offers the reward."],
    ["They only search Primlox and Mermaid's Cove before giving up.", "They travel to Hobsgrove and Crestwood but skip the rest of the islands."],
    ["They want to impress the king so Lucas can become a knight.", "They are afraid Clara's mother will be blamed if the stone isn't found."],
    ["It shows Lucas learning to rule the kingdom on his own.", "It introduces a rivalry between Lucas and a jealous cousin."],
  ],
  "kw-02": [
    ["A dragon egg is stolen from the royal treasury and later found on Crestwood.", "A group of trolls discovers the egg and brings it to the castle."],
    ["He gives the dragon to Clara instead, since she found the egg first.", "He decides the dragon must live wild on Crestwood instead of at the castle."],
    ["It refuses to eat anything the royal cooks prepare for it.", "It grows too big for its stall and starts damaging the castle."],
    ["Sparkleberries, which only bloom once a year on Primlox.", "Frostberries, which grow only in the icy caves of Flatfrost."],
    ["The forest is guarded by trolls who don't want to share their berries.", "The berries are protected by a riddle that must be solved first."],
  ],
  "kw-03": [
    ["A shortage of fish that has nothing to do with any sea creature.", "A mysterious fog that has been rolling in from the sea every night."],
    ["Nanny Louisa is Clara's grandmother, who used to be a sailor.", "Nanny Louisa is a mermaid in disguise who has lived among humans for years."],
    ["King Caleb is the one who believes in the monster, while Lucas doubts it.", "Both King Caleb and Lucas are equally certain the monster is dangerous."],
    ["The creature is actually stealing fish to feed its hungry babies.", "The creature is guarding a shipwreck full of ancient treasure."],
    ["Ruskin scares the creature away for good with a burst of fire.", "Ruskin refuses to go anywhere near the water the entire book."],
  ],
  "kw-04": [
    ["It has been snowing nonstop, burying the kingdom's farms.", "A terrible drought has dried up every river in the kingdom."],
    ["He suspects the Witch of Bogburp cursed the kingdom out of spite.", "He suspects his cousin Bella cast the curse to embarrass him."],
    ["She offers to stop the rain in exchange for Ruskin himself.", "She offers to stop the rain only if the king gives up his throne."],
    ["They want to ask her for a spell that would make Ruskin stronger.", "They want to warn her that Grom is planning to attack her treehouse."],
    ["A drop of dragon's blood, which only Ruskin can provide.", "Three golden feathers, which must be gathered from Crestwood."],
  ],
  "kw-05": [
    ["Lucas and Ruskin accidentally set the royal library on fire.", "Lucas and Ruskin knock over every statue in the throne room."],
    ["The king sends them to apologize personally to the giants of Flatfrost.", "The king sends them to train with the knights of the Spires instead."],
    ["They have to help Ruskin learn to fly higher and faster.", "They have to help Ruskin learn to breathe underwater."],
    ["They learn that the giants are actually afraid of dragons.", "They learn the giants have a secret feud with the trolls of Burth."],
    ["Ruskin will have to live with the giants in Flatfrost permanently.", "Ruskin will lose his fire-breathing ability altogether."],
  ],
  "kw-06": [
    ["Clara wants to sell gemstones she finds in the Stone Forest.", "Clara is searching for a lost family heirloom hidden underground."],
    ["It was carved by ancient dragons who once ruled the land.", "It was created by a wizard's spell gone wrong centuries ago."],
    ["She is Lucas's younger sister, visiting from a nearby kingdom.", "She is a princess from Hobsgrove who studies magic."],
    ["Her puppy is stolen by a goblin living beneath the forest.", "Her puppy runs away after being frightened by Ruskin."],
    ["She decides she wants to become queen of the gnomes herself.", "She realizes gnomes should not be allowed to live so close to the castle."],
  ],
  "kw-07": [
    ["A masked jousting contest where no one knows each other's identity.", "A cooking competition between chefs from every island in Wrenly."],
    ["Sir Hugh is Lucas's uncle, and Gilbert is a visiting prince.", "Sir Hugh is the newest knight, and Gilbert is his older brother."],
    ["He says only trolls are strong enough to compete in the tournament.", "He says dragons should not be allowed to participate at all."],
    ["She is determined to win the tournament's grand prize for herself.", "She is determined to become Gilbert's new squire instead of competing."],
    ["It shows that dragons are just as capable as knights in battle.", "It shows that kings should choose knights based on family, not skill."],
  ],
  "kw-08": [
    ["Lucas falls asleep on the beach and dreams about mermaids.", "Lucas dives into the sea on purpose to search for mermaids."],
    ["He sees a group of pirates burying treasure on the ocean floor.", "He sees a school of glowing fish leading him toward a whirlpool."],
    ["He tells Lucas the mermaids are dangerous and should be avoided.", "He tells Lucas that mermaids are only a legend and don't really exist."],
    ["Lucas agrees completely and never thinks about the mermaids again.", "Lucas tells Clara they should forget about it and focus on something else."],
    ["Whether Lucas can convince the mermaids to become his friends.", "Whether Clara can prove mermaids exist to the whole kingdom."],
  ],
  "kw-09": [
    ["He does not want to go to his sword-fighting lessons.", "He does not want to attend the kingdom's annual feast."],
    ["A famous knight visits and tries to convince Lucas to train harder.", "A young wizard named André visits and offers to teach Lucas a spell."],
    ["He tells of a princess who was rescued using nothing but a magic ring.", "He tells of a dragon who was tamed using nothing but a gentle song."],
    ["They discover a hidden treasure chest buried beneath an old oak tree.", "They come across Ruskin, who has wandered off and gotten lost."],
    ["He decides he would rather learn swordsmanship instead of music.", "He asks his father to cancel his lessons since he already proved himself brave."],
  ],
  "kw-10": [
    ["He wishes for a new dragon to keep him company.", "He wishes that Clara could live at the castle with him."],
    ["The royal jewels have mysteriously disappeared from the treasury.", "The castle's fountain has mysteriously stopped flowing."],
    ["They ask Grom the wizard directly, and he tells them the answer.", "They ask the gnomes of the Stone Forest, who point them toward the sky."],
    ["They set a trap using Ruskin's scales as bait near the castle gates.", "They leave a trail of berries leading all the way to the castle."],
    ["They must teach the pegasus to breathe fire like a dragon.", "They must convince the king to let the pegasus live at the castle forever."],
  ],
  "kw-11": [
    ["All of Primlox's flowers wilt and turn to stone overnight.", "Every fairy on Primlox suddenly grows human-sized wings."],
    ["Falsk is the fairy queen, who has ruled Primlox for a hundred years.", "Falsk is Clara's fairy godmother, who has watched over her since birth."],
    ["They must defeat a dragon that has been terrorizing Primlox.", "They must solve a riddle that will instantly bring the fairies back."],
    ["Because Falsk has openly admitted she works for an enemy of Wrenly.", "Because Falsk demands payment in gold before she'll help them at all."],
    ["It teaches that magic always comes with a hidden price.", "It teaches that fairies can never truly be trusted by humans."],
  ],
  "kw-12": [
    ["The trees themselves have started walking away from the forest.", "A drought has dried up every stream running through Trellis."],
    ["They team up with a group of talking animals native to Trellis.", "They team up with the Witch of Bogburp, who owes them a favor."],
    ["A giant that has been terrorizing travelers passing through the woods.", "A pack of wolves that has grown unusually large and aggressive."],
    ["It represents the sorcerer's fear of losing his magical powers.", "It represents jealousy the sorcerer feels toward the royal family."],
    ["By trapping it inside a magical mirror forever.", "By having every animal in the forest chase it away at once."],
  ],
  "kw-13": [
    ["They are a secret society of retired knights who train new recruits.", "They are the personal bodyguards assigned only to King Caleb."],
    ["They want to retire and need someone to take over their duties.", "One of their members has been lost, so they need a replacement."],
    ["The winner must be the strongest fighter, nothing else matters.", "The winner must be royalty, since only nobles may join the Spires."],
    ["She decides she would rather train Ruskin than compete herself.", "She decides to help Lucas prepare instead of competing herself."],
    ["It is simply a fun tradition held once every hundred years.", "It only matters to the twelve current Spires, not the wider kingdom."],
  ],
  "kw-14": [
    ["Furniture rearranges itself and food disappears from the kitchen.", "Doors lock themselves and the castle bell rings at random hours."],
    ["They become convinced a troll has snuck into the castle to hide.", "They become convinced Grom the wizard is playing a prank on them."],
    ["They must catch the ghost before it scares away all the castle staff.", "They must prove to the king that the ghost isn't dangerous."],
    ["The ghost is actually the spirit of a long-dead king of Wrenly.", "The ghost is secretly Clara's ancestor, watching over the castle."],
    ["They must search the dungeons for a hidden treasure the ghost left behind.", "They must perform a spell at midnight to send the ghost away for good."],
  ],
  "kw-15": [
    ["They find a wounded baby dragon hiding beneath a fallen log.", "They find a family of foxes that has been chased from its den."],
    ["They are considered rare because they can turn invisible at will.", "They are considered rare because they only live for a single year."],
    ["Sir Hugh the knight accompanies them to protect against danger.", "Clara's mother comes along since she once studied wolves herself."],
    ["They learn the wolves can transform into humans during the day.", "They learn the wolves have been secretly guarding the kingdom's border."],
    ["Rival gnomes who want to drive the wolves out of the forest.", "A dragon that sees the wolf pack as competition for territory."],
  ],
  "kw-16": [
    ["A floating island that only appears once every hundred years.", "A hidden library that contains every book ever written in Wrenly."],
    ["Ruskin accidentally swallows one of the witch's magic potions.", "Ruskin gets lost while flying too close to Bogburb's swamps."],
    ["They must convince the Witch of Bogburp to help break the spell.", "They must find three magic keys hidden throughout the kingdom."],
    ["It can turn anyone who enters it permanently invisible.", "It can transport people instantly to any island in the kingdom."],
    ["They need the help of every wizard in Hobsgrove to succeed.", "They need to recite an ancient spell perfectly on the first try."],
  ],
  "kw-17": [
    ["They lost a war against the trolls of Burth long ago.", "They were banished from Wrenly after attacking the royal family."],
    ["They have kidnapped Clara's mother in exchange for their old powers.", "They have kidnapped King Caleb, demanding their magic be restored."],
    ["An old goblin chief who wants to make peace with the wizards.", "A goblin who used to be a wizard himself before being cursed."],
    ["Whether to give the goblins new magic powers in exchange for peace.", "Whether to tell the king about the goblin before rescuing the wizards."],
    ["That goblins are always more dangerous than they first appear.", "That old rivalries are impossible to ever truly resolve."],
  ],
  "kw-18": [
    ["A traveling wizard who is testing a brand-new invisibility spell.", "A jealous rival of Clara's who curses her out of spite."],
    ["The spell instead turns Lucas and Clara temporarily invisible.", "The spell instead gives Lucas and Clara each other's voices."],
    ["They must reverse it before the next full moon, weeks away.", "They must reverse it before sunrise the very next morning."],
    ["They will be trapped as statues until someone breaks the curse.", "They will slowly begin to forget who they really are."],
    ["It's a story about learning magic spells the right way.", "It's a mystery about finding out who cursed them in the first place."],
  ],
  "kw-19": [
    ["Trolls live in the Stone Forest, and their tools have gone missing.", "Wizards live in the Stone Forest, and their spells have stopped working."],
    ["They team up with the Witch of Bogburp, who studies gemstones.", "They team up with Grom the wizard, who has a theory about curses."],
    ["The gems power the castle's lights, so all of Wrenly could go dark.", "The gems are the gnomes' only source of food, so they could starve."],
    ["They must trade the gnomes a piece of the royal treasury for new gems.", "They must travel to Flatfrost to mine brand-new gems from the ice."],
    ["It shows Lucas and Clara becoming rulers of the Stone Forest.", "It shows the gnomes deciding to move away from Wrenly for good."],
  ],
  "kw-20": [
    ["A giant sea serpent has been spotted circling the harbor at night.", "A mysterious fire has been burning warehouses along the docks."],
    ["A baby dragon that hatched unexpectedly in the royal treasury.", "An injured griffin that Ruskin found while flying near the coast."],
    ["They immediately suspect it is dangerous and want to send it away.", "They are afraid of it and refuse to go anywhere near its cage."],
    ["They learn that magical creatures always repay kindness with loyalty.", "They learn that every magical creature in Wrenly can be trusted completely."],
    ["Whether Ruskin is strong enough to fight off the pirates alone.", "Whether the missing royal ship will ever be found at all."],
  ],
};

export default kingdomOfWrenlyDistractors;
