import type { DistractorMap } from "./index";

const percyJacksonDistractors: DistractorMap = {
  "pj-01-ch-01": [
    ["They go to the Museum of Natural History to see dinosaur bones.", "They go to a science museum to see a space exhibit."],
    ["She falls down a flight of museum stairs and has to go to the hospital.", "She gets locked inside an exhibit room and has to be rescued by security."],
    ["He throws Percy a Greek shield from the museum display.", "He throws Percy his own wheelchair cane to use as a weapon."],
    ["Everyone remembers Mrs. Dodds perfectly but refuses to talk about the attack.", "Everyone believes Percy made up the whole story to get attention."],
    ["Percy feels excited because he loves studying pre-algebra.", "Percy feels proud because he's the top student in his class."],
  ],
  "pj-01-ch-02": [
    ["He overhears them planning a surprise party for his birthday.", "He overhears them arguing about Percy's low grades in Latin class."],
    ["Percy is expelled for fighting with Nancy Bobofit.", "Percy chooses to leave early because he misses his mom."],
    ["Grover admits he was paid by the school to spy on Percy.", "Grover admits he's actually failing all of his classes too."],
    ["The women offer Percy and Grover free fruit and a ride home.", "The women warn Percy that his bus is about to break down."],
    ["Percy feels relieved because Grover finally explains everything clearly.", "Percy feels bored because nothing unusual happens on the bus ride."],
  ],
  "pj-01-ch-03": [
    ["She takes him to visit his grandparents in another state.", "She takes him camping in the mountains for the weekend."],
    ["He dreams about Mrs. Dodds chasing him through the museum again.", "He dreams about winning a big pre-algebra competition at school."],
    ["Gabe shows up unexpectedly and demands they come home.", "The police arrive looking for Percy about the museum incident."],
    ["Percy notices Grover has a cast on his leg from an injury.", "Percy notices Grover is wearing several layers of extra clothing."],
    ["Sally laughs it off and tells Grover to calm down.", "Sally calls Gabe to come pick them up instead of driving herself."],
  ],
  "pj-01-ch-04": [
    ["Grover explains that he's actually a runaway prince from a foreign country.", "Grover explains that Mr. Brunner is secretly a famous spy."],
    ["A giant serpent with multiple heads attacks them.", "A pack of wild wolves surrounds the wrecked car."],
    ["She is knocked unconscious but Percy manages to carry her to safety.", "She hides inside the wrecked car until the monster leaves."],
    ["Percy traps the Minotaur inside the wrecked car and lets it explode.", "Percy distracts the Minotaur with a flashlight until it wanders off a cliff."],
    ["He sees his mother waving to him from a car driving away.", "He sees a group of police officers rushing toward him."],
  ],
  "pj-01-ch-05": [
    ["Percy wakes up in a hospital bed in New York City.", "Percy wakes up back in his old bedroom at his mom's apartment."],
    ["Grover feeds him ordinary hospital soup and crackers.", "Grover feeds him a strange bitter medicine that tastes terrible."],
    ["Percy meets Clarisse and Luke playing cards together.", "Percy meets his mother and Grover's uncle at the card table."],
    ["Mr. D reveals he used to be Percy's father's best friend.", "Mr. D reveals he is actually Grover's long-lost uncle."],
    ["Mr. Brunner reveals he is actually a retired Greek soldier.", "Mr. Brunner reveals he can turn invisible whenever he wants."],
  ],
  "pj-01-ch-06": [
    ["Chiron shows Percy a hidden library full of ancient weapons.", "Chiron shows Percy an underground tunnel leading to the ocean."],
    ["Cabin Eleven is simply the only cabin with an empty bed.", "Percy is assigned there as a punishment for arriving late."],
    ["Clarisse succeeds in dunking Percy, embarrassing him in front of everyone.", "Percy fights back and gets both of them sent to see Chiron."],
    ["Clarisse is Chiron's daughter and helps run the camp.", "Clarisse is from Cabin Eleven, just like Percy."],
    ["Annabeth says she wants to be his training partner for sword fighting.", "Annabeth says she wants him to help her fix the camp's boundary magic."],
  ],
  "pj-01-ch-07": [
    ["Annabeth tells Percy both of her parents are ordinary mortals.", "Annabeth tells Percy her father is a famous war general."],
    ["Annabeth reveals that a camper stole gold from the camp's treasury.", "Annabeth reveals that Mr. D's throne was destroyed in a fire."],
    ["Luke tells Percy that he has never been allowed to go on a quest.", "Luke tells Percy that his quest was actually a huge success."],
    ["Campers write letters to the gods and mail them overnight.", "Campers sing a song in ancient Greek before eating."],
    ["Mr. D gives a warm, heartfelt speech welcoming Percy to camp.", "Mr. D refuses to acknowledge Percy in front of the other campers at all."],
  ],
  "pj-01-ch-08": [
    ["Grover tells Percy that the Big Three gods never speak to each other anymore.", "Grover tells Percy that the Big Three gods are actually all brothers of Chiron."],
    ["Percy is captured and has to be rescued by Annabeth's team.", "Percy loses the fight and is knocked out of the game."],
    ["A swarm of giant hornets attacks the players in the woods.", "A pack of wild wolves interrupts the game near the flag."],
    ["A glowing lightning bolt symbol appears above Percy's head.", "A glowing owl symbol appears above Percy's head."],
    ["Clarisse's team captures the flag despite losing the fight with Percy.", "Percy personally captures the flag right after being claimed."],
  ],
  "pj-01-ch-09": [
    ["Percy is moved there as punishment for the bathroom incident.", "Percy asks to be moved because he doesn't get along with Luke."],
    ["They tell him that Camp Half-Blood is about to run out of money.", "They tell him that Chiron's centaur family has gone missing."],
    ["Percy visits a temple deep in the strawberry fields.", "Percy is taken to a hidden cave beneath the dining pavilion."],
    ["The prophecy tells Percy he will become the next ruler of Olympus.", "The prophecy tells Percy he must never leave camp again."],
    ["Percy refuses the quest and asks Chiron to send someone else instead.", "Percy asks for more time to think it over before deciding."],
  ],
  "pj-01-ch-10": [
    ["Percy chooses Clarisse and Luke to accompany him.", "Percy decides to go completely alone to keep his friends safe."],
    ["Percy receives a suit of golden armor and a chariot.", "Percy receives a map that shows exactly where the bolt is hidden."],
    ["Clarisse secretly follows them and boards the same bus.", "A group of reporters recognize Percy and board to interview him."],
    ["Percy takes the cap and escapes out the emergency exit alone.", "Percy gives the cap to Grover so he can escape instead."],
    ["The bus breaks down and simply refuses to start again.", "The bus driver crashes it into a ditch trying to escape the monsters."],
  ],
  "pj-01-ch-11": [
    ["The garden gnomes are all wearing tiny Camp Half-Blood shirts.", "The garden gnomes are actually robots in disguise."],
    ["Grover recognizes a statue of his own mother among the gnomes.", "Grover recognizes a statue of Chiron among the gnomes."],
    ["Aunty Em turns out to be one of the three Furies in disguise.", "Aunty Em turns out to be Clarisse's mother in disguise."],
    ["Percy closes his eyes completely and swings his sword blindly.", "Percy throws sand in Medusa's face to blind her before attacking."],
    ["Percy buries Medusa's head so no one can ever find it.", "Percy keeps Medusa's head as a trophy to bring back to camp."],
  ],
  "pj-01-ch-12": [
    ["Grover uses a magic whistle to communicate with the poodle.", "Grover reads the poodle's mind using a spell Annabeth taught him."],
    ["The family gives them a car instead of a cash reward.", "The poodle leads them straight to the stolen lightning bolt."],
    ["Percy notices an article announcing that Gabe has been arrested.", "Percy notices an article about a school reunion at Yancy Academy."],
    ["Percy sees a group of satyrs playing music in a field.", "Percy sees a giant eagle carrying off a farm animal."],
    ["Percy sees Clarisse's face reflected in the train window.", "Percy sees a shadowy figure that looks exactly like Luke."],
  ],
  "pj-01-ch-13": [
    ["Annabeth insists on visiting a famous art museum in St. Louis.", "Annabeth insists on visiting an ancient Greek exhibit at a library."],
    ["Percy is left alone with a tour guide and a park ranger.", "Percy is left alone with two mysterious teenagers his age."],
    ["The woman turns out to be one of the Furies in a new disguise.", "The woman turns out to be Medusa's twin sister."],
    ["Percy's sword turns back into a harmless pen mid-fight.", "Percy accidentally drops his sword down the elevator shaft."],
    ["Echidna dares Percy to fight the Chimera bare-handed.", "Echidna dares Percy to hand over his invisibility cap."],
  ],
  "pj-01-ch-14": [
    ["Percy gets swept far downstream and has to swim for hours to shore.", "Percy loses consciousness underwater and wakes up on the riverbank."],
    ["Percy meets his father, Poseidon, in person underwater.", "Percy meets a talking dolphin who guides him back to shore."],
    ["News reports say the Arch has been closed for routine repairs.", "News reports praise Percy as a hero for saving tourists."],
    ["A fish delivers the sword back to Percy in its mouth.", "Percy has to buy a brand new sword once he reaches shore."],
    ["They head straight back to New York to check on Percy's mother.", "They decide to hide out in St. Louis until things calm down."],
  ],
  "pj-01-ch-15": [
    ["Grover mails a letter using regular postal mail.", "Grover borrows a stranger's phone to call Chiron directly."],
    ["A kind waitress secretly covers the bill for them.", "Annabeth pays using drachmas she had saved from camp."],
    ["The stranger turns out to be Luke's father in disguise.", "The stranger turns out to be Dionysus checking up on Percy."],
    ["Ares offers to fight Percy's battles for him for the rest of the quest.", "Ares offers to reveal exactly who stole the master bolt."],
    ["The shield is guarded by a real, live hellhound.", "The shield simply isn't there, and they find an empty pedestal instead."],
  ],
  "pj-01-ch-16": [
    ["Ares gives Percy a magical shield that can never be broken.", "Ares gives Percy a map showing exactly where the lightning bolt is."],
    ["Percy quietly reports the truck driver to the police instead.", "Percy convinces the animals to stay put until help arrives."],
    ["The doorman leads them to a free hotel meant for stranded travelers.", "The doorman leads them to a secret meeting with Chiron."],
    ["Percy realizes the casino is run by Medusa's family.", "Percy realizes the casino card he was given is completely fake."],
    ["They leave because security starts chasing them for cheating at games.", "They leave because Clarisse suddenly shows up at the casino."],
  ],
  "pj-01-ch-17": [
    ["The store is run by a disguised version of Ares.", "The store is run by an ordinary salesman with no myth connection at all."],
    ["Crusty tries to sell them beds at an unfairly high price.", "Crusty locks Annabeth and Grover in a storage room."],
    ["Percy convinces Crusty to let his friends go through negotiation.", "Percy simply outruns Crusty and escapes with his friends."],
    ["Percy finds a hidden map showing the way back to Camp Half-Blood.", "Percy finds a letter revealing that Ares stole the master bolt himself."],
    ["It means they can finally return home without finishing the quest.", "It means they no longer need to worry about the missing lightning bolt."],
  ],
  "pj-01-ch-18": [
    ["The sea spirit gives Percy a new, stronger sword.", "The sea spirit gives Percy a map straight to his father's palace."],
    ["They defeat Charon in a sword fight to get past him.", "They sneak past Charon using Annabeth's invisibility cap the whole way."],
    ["Cerberus refuses to let anyone through no matter what they try.", "Cerberus chases them all the way back to the entrance."],
    ["Annabeth sings a lullaby that puts Cerberus to sleep instantly.", "Annabeth offers Cerberus food until he loses interest in them."],
    ["They turn back, deciding the risk is too great to continue.", "They wait at the entrance for Chiron to catch up with them."],
  ],
  "pj-01-ch-19": [
    ["Hades accuses Percy of freeing souls from the Underworld.", "Hades accuses Percy of stealing his throne."],
    ["Percy finds Hades's helm of darkness inside his backpack.", "Percy finds a letter from Luke inside his backpack."],
    ["It reveals conclusively that Luke stole both items himself.", "It reveals that Ares definitely stole both items on his own."],
    ["Hades threatens to turn Percy's mother into a ghost permanently.", "Hades threatens to send Percy's mother to fight in the arena."],
    ["They escape by convincing Charon to ferry them back across the river.", "They escape through a secret tunnel that Annabeth discovers."],
  ],
  "pj-01-ch-20": [
    ["The pearls carry them straight back to Camp Half-Blood.", "The pearls carry them to the top of the Empire State Building."],
    ["Ares confesses that he actually stole the bolt for Zeus as a test.", "Ares confesses that Chiron secretly helped plan the whole scheme."],
    ["Ares sends a pack of hellhounds after Percy.", "Ares sends the Chimera to attack Percy again."],
    ["Percy defeats Ares by tricking him into stepping into quicksand.", "Percy defeats Ares by using Medusa's head to turn him to stone."],
    ["Percy finds the master bolt buried in the sand instead of the helm.", "Percy buries the helm again so no one can ever use it."],
  ],
  "pj-01-ch-21": [
    ["The manhunt is called off because Percy turned eighteen.", "The manhunt is called off because Ares confessed publicly to the police."],
    ["Percy sends his friends home and quits the quest entirely.", "Percy insists all three of them go together to see Zeus."],
    ["Percy mails the bolt back to Olympus using Hermes Express.", "Percy meets Zeus at Camp Half-Blood to hand over the bolt."],
    ["Percy suspects that Mr. D orchestrated the whole plot.", "Percy suspects that Chiron secretly orchestrated the whole plot."],
    ["Poseidon tells Percy his mother has decided to move to Camp Half-Blood.", "Poseidon tells Percy his mother has lost all her memories of him."],
  ],
  "pj-01-ch-22": [
    ["The camp holds a quiet ceremony with no celebration at all.", "The camp punishes Percy for taking too long to complete the quest."],
    ["Luke reveals that he is actually Percy's older half-brother.", "Luke reveals that he plans to leave camp and become a mortal."],
    ["Luke admits he told Ares to steal the shield from Waterland.", "Luke admits he tipped off Echidna about their location at the Arch."],
    ["Luke leaves Percy to be captured by camp security instead.", "Luke leaves Percy stranded outside the camp's magic borders."],
    ["Poseidon explains that Kronos is actually Luke's real father.", "Poseidon explains that Kronos is a monster Percy already defeated on his quest."],
  ],
  "pj-02-ch-01": [
    ["Percy dreams that he is fighting the Minotaur again on Half-Blood Hill.", "Percy dreams that Annabeth is trapped inside a maze guarded by a dragon."],
    ["Grover whispers Percy's name over and over in fear.", "Grover whispers that Camp Half-Blood has already been destroyed."],
    ["It's the day of Percy's final exam in Ancient Greek mythology class.", "It's the first day of a brand new school Percy just transferred to."],
    ["Percy has been attacked by monsters constantly, worse than ever before.", "Percy has already been expelled once already this year."],
    ["The monster spots Grover's reflection in a store window and charges through the glass.", "The monster follows a trail of enchanted acorns that Grover dropped by accident."],
  ],
  "pj-02-ch-02": [
    ["They face a team of ghost warriors summoned by Luke.", "They face Clarisse's cabin in a prank battle."],
    ["The dodgeballs are frozen solid and can knock someone out cold.", "The dodgeballs are covered in poison that causes sleep."],
    ["Tyson calls camp counselors on his phone for backup.", "Tyson uses a magic wand he found earlier that day."],
    ["Annabeth tells Percy that Chiron has quit being a teacher forever.", "Annabeth tells Percy that his mother has been kidnapped."],
    ["They are rescued by a flying chariot sent by Zeus.", "A teacher steps in and scares the giants away."],
  ],
  "pj-02-ch-03": [
    ["They call in a favor from a friendly satyr with a truck.", "They flag down a New York City subway conductor who knows shortcuts."],
    ["The taxi can only drive backwards the whole way.", "The taxi randomly teleports passengers to the wrong cities."],
    ["They each wear a magic contact lens that copies the eye's vision.", "They use the eye only to check makeup, never to actually drive."],
    ["Percy has to pay them with a bag of golden drachmas up front.", "Percy has to solve a riddle before they'll open the car doors."],
    ["The taxi breaks down halfway and strands them in a forest.", "The taxi accidentally takes them to Olympus instead of camp."],
  ],
  "pj-02-ch-04": [
    ["They find camp completely abandoned with no one there.", "They find camp has been rebuilt as a fortress."],
    ["Tyson turns out to be a gifted musician who calms monsters with songs.", "Tyson turns out to be an expert swimmer who never needs to breathe."],
    ["Every camper immediately treats Tyson like a celebrity.", "The campers ignore Tyson completely and never speak to him."],
    ["Percy feels completely thrilled and brags about Tyson to everyone.", "Percy feels nothing at all and barely thinks about Tyson."],
    ["The worry is that camp is about to run out of food for the summer.", "The worry is that Chiron is planning to shut the camp down forever."],
  ],
  "pj-02-ch-05": [
    ["Tyson is revealed to be a son of Hephaestus who ran away from his forge.", "Tyson is revealed to be an ordinary mortal orphan with no godly parent."],
    ["Percy feels proud right away and shows Tyson off to everyone.", "Percy feels nothing because he already knew the truth."],
    ["Tyson is given his own private cabin built just for Cyclopes.", "Tyson is sent to live with the satyrs in the woods."],
    ["Chiron has retired happily to travel the world.", "Chiron has been promoted to run all of Mount Olympus."],
    ["A budget cut has forced camp to turn off its magical defenses.", "The gods have decided to remove camp's protection on purpose."],
  ],
  "pj-02-ch-06": [
    ["Tantalus brings back an old sword-fighting tournament, and it's during that event that trouble breaks out.", "Tantalus starts a new cooking competition, and monsters crash the judging."],
    ["A swarm of giant metal wasps attacks the chariots mid-race.", "A flock of harpies attacks the dining pavilion during the race."],
    ["Tantalus praises Percy, Annabeth, and Tyson for defending the camp so bravely.", "Tantalus cancels the chariot races permanently out of fear."],
    ["Percy sprays the birds with a hose until they fly off.", "Percy tricks the birds into chasing Tantalus instead of the campers."],
    ["It shows that camp has never been safer or happier than under Tantalus.", "It shows that the demon pigeons were secretly working for Chiron all along."],
  ],
  "pj-02-ch-07": [
    ["The god Apollo visits Percy disguised as a school bus driver.", "The goddess Hera visits Percy disguised as a lunch lady."],
    ["Hermes is worried about losing his job as messenger god.", "Hermes is worried about a package he lost somewhere in the mortal world."],
    ["Hermes asks Percy to arrest Luke and bring him straight to Olympus.", "Hermes asks Percy to forget Luke ever existed."],
    ["Hermes leaves Percy a suit of golden armor.", "Hermes leaves Percy a map that shows the location of every monster in the world."],
    ["Percy feels bored and wishes the conversation would end quickly.", "Percy feels angry that Hermes interrupted his training."],
  ],
  "pj-02-ch-08": [
    ["The Princess Andromeda is Poseidon's underwater palace.", "The Princess Andromeda is a camp transport ship run by Chiron."],
    ["They board because they've been officially invited to a peace summit.", "They board because it's the only ferry available to reach the Fleece's island."],
    ["Grover has been given the official quest to find the Golden Fleece.", "Annabeth has been given the official quest to find the Golden Fleece."],
    ["They are given VIP passes disguised as ordinary tourists.", "They fly onto the deck using borrowed winged sandals."],
    ["The ship feels festive, like an ordinary vacation cruise.", "The ship feels completely empty and abandoned."],
  ],
  "pj-02-ch-09": [
    ["They overhear that Grover has already been captured and brought aboard.", "They overhear that Clarisse secretly works for Luke too."],
    ["A cage holding several campers Luke has kidnapped.", "A wall covered in maps marking Camp Half-Blood's defenses."],
    ["Luke admits that Kronos ordered him to kidnap Annabeth's mother.", "Luke admits that he was the one who cursed Chiron to be stuck as a teacher forever."],
    ["Luke bursts into tears and says he misses his father terribly.", "Luke agrees to stop his plans if Hermes apologizes to him."],
    ["They convince Luke's crew to let them leave peacefully by boat.", "They use Percy's water powers to swim the whole way to shore instantly."],
  ],
  "pj-02-ch-10": [
    ["They are rescued by a modern Coast Guard cutter.", "They are rescued by a pirate ship crewed by living sailors."],
    ["The ghostly crew immediately tries to throw them overboard.", "The ghostly crew begs Percy to free them from a curse right away."],
    ["The ship takes them straight back to Camp Half-Blood immediately.", "The ship turns out to be another trap set by Luke."],
    ["The ship is loud and modern, full of blaring music and lights.", "The ship is bright and cheerful, decorated for a party."],
    ["They feel completely relaxed, treating it like an ordinary cruise.", "They feel angry and try to fight the ghostly crew right away."],
  ],
  "pj-02-ch-11": [
    ["They encounter a rival ship of the Hunters of Artemis.", "They encounter a Roman legion's warship."],
    ["Clarisse's ship is threatened by a giant kraken summoned by Kronos.", "Clarisse's ship is threatened by an army of sea nymphs loyal to Luke."],
    ["Clarisse's ship makes it through completely undamaged.", "Clarisse's ship is captured intact by Luke's forces."],
    ["Clarisse panics and hides below deck the whole time.", "Clarisse abandons her crew to save herself first."],
    ["Percy and his friends are captured alongside Clarisse.", "Percy and his friends manage to rescue Clarisse and continue together."],
  ],
  "pj-02-ch-12": [
    ["They wash up on Polyphemus's island right away.", "They wash up back on the shore near Camp Half-Blood."],
    ["Circe secretly turns male visitors into golden statues.", "Circe secretly puts male visitors into an endless magical sleep."],
    ["Percy resists the magic completely and is never affected.", "Percy is turned into a small bird instead of a guinea pig."],
    ["Annabeth immediately sees through Circe's tricks and fights her.", "Annabeth is locked in a cage the moment they arrive."],
    ["Percy stays trapped as a guinea pig until the very end of the book.", "Percy is rescued only because Clarisse arrives just in time."],
  ],
  "pj-02-ch-13": [
    ["Annabeth is completely unaffected and eager to continue the quest right away.", "Annabeth has lost her memory entirely."],
    ["Annabeth tries to steal a boat and sail back to Luke's ship.", "Annabeth tries to fly home using borrowed winged sandals."],
    ["Percy lets Annabeth go without saying anything.", "Percy orders Tyson to physically drag Annabeth back by force."],
    ["Annabeth is worried that her mother Athena has abandoned her forever.", "Annabeth is worried that she's about to be kicked out of camp."],
    ["They decide to give up the quest and head straight home.", "They split up permanently, each continuing separately."],
  ],
  "pj-02-ch-14": [
    ["They find a dragon guarding the Golden Fleece.", "They find Luke himself guarding the Golden Fleece."],
    ["The sheep can talk and warn intruders about traps.", "The sheep breathe fire whenever strangers approach."],
    ["Percy discovers Chiron, who was kidnapped weeks earlier.", "Percy discovers Clarisse, who was captured after her ship wrecked."],
    ["Polyphemus believes Grover is a spy sent by Poseidon.", "Polyphemus believes Grover is a runaway slave he needs to punish."],
    ["They charge straight at Polyphemus without any plan.", "They immediately reveal themselves and demand the Fleece."],
  ],
  "pj-02-ch-15": [
    ["Tyson explains that Poseidon personally rescued him from the ocean floor.", "Tyson explains that Clarisse's crew picked him up and hid him."],
    ["Tyson followed a trail of magic drachmas left by Annabeth.", "Tyson was guided by a message from Chiron sent through Iris."],
    ["Percy carries Annabeth away from the island immediately without using the Fleece.", "Percy calls on Poseidon to heal Annabeth instead of using the Fleece."],
    ["Percy convinces Polyphemus that Tyson is actually a ghost.", "Percy convinces Polyphemus that the Fleece was stolen by Luke."],
    ["They accidentally kill Polyphemus in the struggle.", "Polyphemus surrenders peacefully and lets them sail away untouched."],
  ],
  "pj-02-ch-16": [
    ["They cling to floating wreckage until a passing fishing boat spots them.", "They are pulled to shore by Circe's magic."],
    ["A pod of friendly dolphins sent by Poseidon carries them to safety.", "Luke's own crew rescues them out of guilt."],
    ["They wash up back at Camp Half-Blood's own beach.", "They wash up on a deserted island with no name."],
    ["Annabeth realizes they accidentally left the Fleece behind on the sunken ship.", "Annabeth realizes that Tyson is missing again."],
    ["They must return the Fleece within a month or lose Poseidon's favor.", "They must find Chiron before sunrise or camp will be shut down."],
  ],
  "pj-02-ch-17": [
    ["They realize they only have one hour before the beach floods with the tide.", "They realize Camp Half-Blood has already been destroyed while they were away."],
    ["Clarisse refuses to speak to them and storms off down the beach.", "Clarisse immediately hands over the Fleece without any argument."],
    ["Percy decides to keep the Fleece and deliver it himself for the credit.", "Percy decides to hide the Fleece on the beach until they can all travel together."],
    ["Annabeth pays using golden drachmas she'd been saving the whole trip.", "They convince the airline to let Clarisse fly for free."],
    ["A group of Hunters of Artemis surrounds them, mistaking them for monsters.", "A hurricane suddenly sweeps in and scatters everyone across the beach."],
  ],
  "pj-02-ch-18": [
    ["Percy refuses to fight and begs Luke for mercy instead.", "Percy hides below deck and waits for a rescue instead of fighting."],
    ["A squad of camp counselors arrives by helicopter.", "Artemis and her Hunters arrive to join the fight."],
    ["Chiron explains that Grover led him straight there using his empathy link.", "Chiron explains that he simply got lucky spotting the ship from shore."],
    ["Tyson hides below deck until the fighting is completely over.", "Tyson tries to make peace with Luke's soldiers instead of fighting."],
    ["Chiron reveals that he used to be Luke's secret teacher before camp.", "Chiron reveals that he is actually immortal because Zeus cursed him."],
  ],
  "pj-02-ch-19": [
    ["They arrive to find the tree already fully healed by Chiron.", "They arrive too late and the tree has already died."],
    ["Chiron announces that camp is cancelling all activities for safety.", "Chiron announces that Tantalus will be racing in the chariot competition."],
    ["Percy teams up with Clarisse to build the fastest chariot at camp.", "Percy competes completely alone with no teammates."],
    ["Tyson builds a chariot that can fly a few feet off the ground.", "Tyson builds invisible wheels that make no sound."],
    ["Percy's team crashes and comes in last place.", "Clarisse's team wins the race instead of Percy's."],
  ],
  "pj-02-ch-20": [
    ["The tree grows so large it becomes a threat to the camp's cabins.", "The tree's magic accidentally spreads and heals every plant in the state."],
    ["Tantalus is promoted to a permanent position on Mount Olympus.", "Tantalus stays in charge and nothing changes for him."],
    ["Dionysus is reinstated as camp's full-time leader.", "Luke is invited back and forgiven by the campers."],
    ["Clarisse is punished for losing her original ship during the quest.", "Percy is given all the credit instead of Clarisse."],
    ["Thalia's tree is destroyed completely, undoing all the earlier rescue efforts.", "Thalia's spirit appears as a ghost but cannot fully return to life."],
  ],
  "pj-03-ch-01": [
    ["They went to rescue Annabeth, who had been kidnapped from the school earlier that week.", "They went because Chiron ordered them to spy on a new camp for young monsters being built nearby."],
    ["They are two satyrs training alongside Grover to search for new demigods.", "They are teachers at Westover Hall who secretly work for Camp Half-Blood."],
    ["They forged transfer papers on Annabeth's laptop the night before.", "Chiron called ahead and enrolled them officially as exchange students."],
    ["Dr. Thorn kept insisting he had met Percy's mother somewhere before.", "Dr. Thorn was secretly wearing a Camp Half-Blood necklace under his suit."],
    ["Grover told them Pan had finally been found hiding in the school basement.", "Grover told them Annabeth's father worked as a teacher at the school."],
  ],
  "pj-03-ch-02": [
    ["Dr. Thorn turns out to be a minor Titan in disguise, testing the young heroes.", "Dr. Thorn turns out to be a cyclops working secretly for Luke."],
    ["A squad of satyrs led by Grover's uncle bursts in to help.", "Chiron gallops in on his horse half to join the fight personally."],
    ["Annabeth is captured and locked inside the school by Dr. Thorn's assistants.", "Annabeth chases the manticore into the woods and gets lost overnight."],
    ["The manticore breathes a cloud of poisonous gas to knock everyone out.", "The manticore summons a pack of skeleton warriors to fight alongside it."],
    ["They feel triumphant because they captured Dr. Thorn and can question him.", "They feel relieved because Grover confirms he saw Annabeth escape safely."],
  ],
  "pj-03-ch-03": [
    ["Percy's father Poseidon rises out of a nearby lake to explain everything.", "Dr. Thorn's twin brother arrives to confess what really happened."],
    ["Bianca has to decide whether to return to Westover Hall or move to Camp Half-Blood.", "Bianca has to decide whether to tell Nico that their father is a Greek god."],
    ["Bianca decides to stay with Nico and refuses to join the Hunters.", "Bianca decides to go home to her family instead of joining any group."],
    ["Nico is thrilled and immediately asks to join the Hunters too.", "Nico runs away from the group in anger and disappears into the woods."],
    ["Percy feels confident that everything is under control and no longer worries about Annabeth.", "Percy feels angry at Bianca for choosing to join the Hunters over her brother."],
  ],
  "pj-03-ch-04": [
    ["Chiron sends a flying chariot pulled by pegasi to pick them up.", "They call Percy's mom, who drives for hours to come get them."],
    ["Thalia doesn't have her license yet, so she isn't legally allowed to drive.", "Thalia is afraid of water and refuses to drive near the coast."],
    ["She accidentally drives them into the ocean and they have to swim to shore.", "She gets them lost for days trying to find the right highway."],
    ["They run out of fuel in the middle of a forest, far from camp.", "Police officers pull them over and end the ride early."],
    ["Thalia feels bored and unimpressed by the whole trip.", "Thalia feels excited and asks to drive again right away."],
  ],
  "pj-03-ch-05": [
    ["Percy uses a special phone Chiron gives him to text the gods directly.", "Percy borrows Apollo's chariot to fly down to the ocean floor."],
    ["Percy speaks directly with Zeus about the missing goddess Artemis.", "Percy talks with Dr. Thorn, who tries to trick him with false information."],
    ["He learns that Poseidon has decided to leave Olympus completely.", "He learns that the ocean's monsters have joined forces with Artemis."],
    ["He hears that Bianca has changed her mind and left the Hunters already.", "He hears that Dr. Thorn has been captured and imprisoned by the gods."],
    ["Percy feels completely calm, believing all of his problems are now solved.", "Percy feels ready to give up the search for Annabeth entirely."],
  ],
  "pj-03-ch-06": [
    ["Percy finds a letter Annabeth wrote saying she planned to run away from camp.", "Percy finds Annabeth's dagger buried near the cabins."],
    ["Dr. Thorn crashes the game, still disguised as a teacher.", "Grover shows up riding the Erymanthian Boar in the middle of the field."],
    ["The Oracle delivers a letter from Poseidon addressed to Percy.", "The Oracle delivers a warning that Camp Half-Blood is about to be destroyed."],
    ["They laugh it off, assuming someone is playing a prank in a costume.", "They cheer, thinking it means the quest is already finished successfully."],
    ["Because Percy officially becomes the camp's new activities director.", "Because Percy learns for certain that Annabeth has already been found safe."],
  ],
  "pj-03-ch-07": [
    ["Because Chiron bans him from camp activities for a week.", "Because the other campers vote him out of his cabin."],
    ["Percy dreams that Bianca has secretly betrayed the Hunters.", "Percy dreams that his mother has gone missing along with Annabeth."],
    ["Tyson shows up in person to help Percy sneak onto the quest.", "Dr. Thorn's shadow appears at the edge of camp, spying on Percy."],
    ["He feels relieved, since he was hoping for a break from questing.", "He feels proud that Zoe finally trusts him completely."],
    ["The General is revealed in the dream to be Dr. Thorn's older brother.", "The General is shown clearly to be the Titan lord Kronos himself."],
  ],
  "pj-03-ch-08": [
    ["They fly off together to spy on Dr. Thorn's hideout.", "They race across camp to warn Chiron about an attack."],
    ["Nico asks Percy to promise never to tell anyone about their father.", "Nico asks Percy to promise to bring him along on the quest too."],
    ["He disguises himself as one of the Hunters to sneak onto the team.", "He convinces Chiron to order Zoe to add him to the group."],
    ["Bessie is a baby sea dragon that belongs to Poseidon's palace.", "Bessie is a disguised Hunter who got turned into an animal by a curse."],
    ["Because keeping the promise means Percy has to break a sacred camp rule.", "Because the promise requires Percy to give up his own godly parent's protection."],
  ],
  "pj-03-ch-09": [
    ["He hides inside one of the Hunters' supply crates on their van.", "He disguises his voice using a magic item borrowed from Annabeth."],
    ["He watches Luke building a fake Camp Half-Blood to trick new demigods.", "He watches the General freeing Kronos from the underworld."],
    ["He convinces the skeleton warriors that he's on their side.", "He transforms into water and slips away through a drainpipe."],
    ["Percy grabs one of the dragon's teeth as proof of what he saw.", "Percy grabs a map showing the location of Mount Olympus."],
    ["He decides to keep what he saw a secret from everyone, including Thalia.", "He goes straight back to camp instead of warning the quest group."],
  ],
  "pj-03-ch-10": [
    ["Percy finds them hiding inside a cave near Camp Half-Blood.", "Percy finds them already fighting Dr. Thorn on a rooftop."],
    ["A giant scorpion made of bronze attacks from inside a display case.", "A pack of skeleton warriors ambushes them right in the museum halls."],
    ["They trap the lion inside a rocket ship display and launch it away.", "They discover a hidden weak spot behind the lion's ear."],
    ["Zoe gives Percy her personal silver hunting bow as a reward.", "Zoe gives Percy a map showing exactly where Annabeth is being held."],
    ["Percy is named the new leader of the quest, replacing Zoe.", "Percy is sent back to camp as punishment for following the group."],
  ],
  "pj-03-ch-11": [
    ["A giant eagle sent by Zeus tracks their every move.", "Dr. Thorn himself pilots a small plane right above them."],
    ["They borrow Professor Chase's private plane to fly west.", "They ride on the back of the Erymanthian Boar the whole way."],
    ["They meet Hades disguised as a train conductor.", "They meet Annabeth's father, who happens to be riding the same train."],
    ["He tells them Annabeth is being held at the bottom of a lake.", "He tells them Bianca secretly still wants to leave the Hunters."],
    ["They feel completely safe, certain nothing can catch up to a moving train.", "They feel ready to give up the quest and head back to camp early."],
  ],
  "pj-03-ch-12": [
    ["An avalanche nearly buries the whole group in snow.", "Dr. Thorn ambushes them disguised as a ski instructor."],
    ["A massive griffin swoops down to help fight the skeletons.", "The Nemean Lion returns for a rematch against Zoe."],
    ["Grover tames the boar by feeding it enchanted acorns from camp.", "Grover uses a rope lasso to force the boar to carry them."],
    ["Grover realizes the boar was actually sent by Dr. Thorn as a trap.", "Grover realizes the boar escaped from a nearby traveling circus."],
    ["It's a calm, quiet ride since the boar moves slowly and carefully.", "It's a sad moment because the boar gets hurt and can't continue."],
  ],
  "pj-03-ch-13": [
    ["The boar brings them straight to the gates of Mount Olympus.", "The boar brings them to a hidden Hunters of Artemis campsite."],
    ["Bianca takes a golden apple meant for the Hunters' garden.", "Bianca takes a silver arrow that once belonged to Zoe."],
    ["A sleeping Titan buried under the scrap metal wakes up.", "An army of skeleton warriors bursts out from beneath the junk piles."],
    ["Bianca climbs onto Talos's shoulder and tries to pull out its wiring.", "Bianca lures Talos toward the boar so it gets crushed instead."],
    ["Bianca is captured by Talos and carried away, still alive but missing.", "Bianca manages to escape at the last second, badly hurt but safe."],
  ],
  "pj-03-ch-14": [
    ["They hitch a ride on a passing freight train once again.", "They fly the rest of the way using Blackjack and other pegasi."],
    ["They meet a mortal tour guide who turns out to be Apollo again.", "They meet another demigod who has been secretly living at the dam."],
    ["Dr. Thorn ambushes them disguised as a cafeteria worker.", "The Nemean Lion's ghost appears and traps them inside."],
    ["Rachel Elizabeth Dare distracts the guards so they can slip away.", "Grover charms the skeleton warriors into falling asleep with his pipes."],
    ["Zoe reveals that Percy's sword was actually a gift from Luke.", "Zoe reveals that the sword once belonged to Dr. Thorn before he became a monster."],
  ],
  "pj-03-ch-15": [
    ["The statues drop them off right at the base of Mount Tamalpais.", "The statues drop them off at Professor Chase's front door."],
    ["Percy has to wrestle Luke to get information about Annabeth.", "Percy has to wrestle a giant sea serpent guarding the harbor."],
    ["Nereus reveals that Annabeth is being kept prisoner nearby in San Francisco.", "Nereus reveals that Zoe secretly wants to quit the Hunters."],
    ["Luke shows up alone, offering to switch sides and help them.", "The Nemean Lion's mate arrives seeking revenge."],
    ["Percy tricks Nereus by offering him a trade of golden treasure.", "Percy convinces Nereus using a message sent from Poseidon."],
  ],
  "pj-03-ch-16": [
    ["Grover decides to stay behind and guard Professor Chase's house.", "Grover heads off to search for Pan on his own instead."],
    ["They visit Luke's father, hoping he can talk his son out of fighting them.", "They visit Dr. Thorn's old teaching colleague for information."],
    ["A giant scorpion the size of a house guards the garden entrance.", "A pack of skeleton warriors stands watch at the garden gates."],
    ["Zoe reveals that the General is secretly her long-lost brother.", "Zoe reveals that the General is actually Luke's father in disguise."],
    ["Zoe uses a magic flute to lull the dragon to sleep.", "Zoe offers the dragon a golden apple as a bribe to let them pass."],
  ],
  "pj-03-ch-17": [
    ["They find Artemis chained up inside a cave, unable to move at all.", "They find Artemis has already escaped and left the mountain."],
    ["Chiron is found captive there, having been kidnapped days earlier.", "Nico is discovered there, having secretly followed the group."],
    ["Luke tries to convince Thalia to free Atlas from his Titan prison.", "Luke tries to convince Thalia to abandon Percy on the mountain."],
    ["Percy tricks Atlas into a wrestling match to distract him completely.", "Percy uses Riptide to cut through the chains holding Artemis in place."],
    ["Artemis defeats Atlas by calling down lightning from her father, Zeus.", "Artemis defeats Atlas by trapping him inside the dragon Ladon's lair."],
  ],
  "pj-03-ch-18": [
    ["Zoe refuses all healing because she believes it's against the Hunters' code.", "Zoe hides her injuries at first, so nobody realizes how badly hurt she is."],
    ["Thalia and Zoe argue one final time about who is to blame for the battle.", "Zoe asks Thalia to take her place as leader of the Titans instead."],
    ["Zoe confesses that she always secretly worked for Atlas.", "Zoe confesses that she knew all along that Bianca wouldn't survive."],
    ["Artemis brings Zoe back to life using a hidden immortality potion.", "Artemis names a new Hunter cabin at camp after Zoe."],
    ["They feel triumphant and mostly forget about Zoe quickly, eager to celebrate.", "They feel angry at Artemis for not saving Zoe sooner."],
  ],
  "pj-03-ch-19": [
    ["They suggest banning Percy from ever visiting Camp Half-Blood again.", "They suggest taking away Percy's ability to control water."],
    ["The gods punish Percy by turning him into a minor forest spirit for a year.", "The gods decide to erase Percy's memory of the entire quest."],
    ["The gods decide the Ophiotaurus must be sacrificed immediately for safety.", "The gods decide to release the Ophiotaurus back into the wild ocean."],
    ["Thalia decides to become a full Olympian goddess herself.", "Thalia decides to leave the group entirely and live as a mortal."],
    ["It means the prophecy is now completely canceled and will never happen.", "It means Nico instead becomes the one the prophecy is definitely about."],
  ],
  "pj-03-ch-20": [
    ["Percy has to tell Nico that Bianca decided to stay with the Hunters forever.", "Percy has to tell Nico that their father wants nothing to do with him."],
    ["Nico calmly accepts the news and thanks Percy for trying his best.", "Nico refuses to believe it and runs off to search for Bianca himself."],
    ["Nico summons a wave of water strong enough to wash the warriors away.", "Nico calls down a bolt of lightning to destroy the warriors instantly."],
    ["Percy figures out that Nico is secretly one of the Hunters in disguise.", "Percy figures out that Nico has been working with Luke all along."],
    ["Grover announces that he has found a whole new herd of satyrs to join camp.", "Grover announces that Dr. Thorn has been spotted again nearby."],
  ],
  "pj-04-ch-01": [
    ["At a summer camp reunion picnic near the lake", "On a school bus heading to a museum field trip"],
    ["She reveals that she's secretly a daughter of a minor god", "She says she can talk to animals the way Grover can"],
    ["The school principal and the gym coach turn out to be disguised monsters", "Two of Percy's classmates turn out to be secret half-bloods working for Luke"],
    ["Percy defeats both monsters and captures them for questioning", "Tammi runs away and is never seen again in this chapter"],
    ["Kelli tells Percy exactly when and how Luke's army will attack the camp", "Kelli warns Percy that Grover has already been captured"],
  ],
  "pj-04-ch-02": [
    ["Percy meets a new camp director named Quintus who owns a fire-breathing horse", "Percy meets Clarisse's cousin, who brought along a pack of wild wolves"],
    ["The Council tells Grover he has already lost his license and can never search again", "The Council promotes Grover to Lord of the Wild immediately"],
    ["Percy reunites with his father, Poseidon, who is visiting camp", "Percy reunites with Nico di Angelo, who has come back to camp"],
    ["Percy gets a message from his mother warning him to come home immediately", "Percy gets a message from Annabeth saying she has found Daedalus"],
    ["Because the ghost directly says it plans to attack camp that same night", "Because the ghost tells Percy that Grover is in immediate danger"],
  ],
  "pj-04-ch-03": [
    ["A pack of hellhounds breaks through the camp's magical barrier", "Kronos's army launches its first real invasion of camp"],
    ["They've been secretly training a group of new campers for battle", "They've been searching the ocean for a way to reach Daedalus"],
    ["They want a hidden stash of ambrosia and nectar", "They want to free Kronos's original body, which they believe is buried in the maze"],
    ["They are ambushed by a group of Luke's demigods", "They fall into a pit trap set up during the evening war game"],
    ["They discover an old, empty demigod grave", "They discover a stash of weapons left behind by Luke's spies"],
  ],
  "pj-04-ch-04": [
    ["Percy dreams about Luke's army marching toward camp", "Percy dreams about Quintus fighting Kronos in an arena"],
    ["Chiron confirms that Daedalus died centuries ago and cannot be found", "Chiron announces that Pan has already been found"],
    ["Annabeth proposes a quest to rescue Nico from the Underworld", "Annabeth receives a prophecy that names Quintus as a traitor"],
    ["She decides to go on the quest completely alone, against Chiron's orders", "She invites a mortal guide before anyone else has even agreed to it"],
    ["Juniper tells Percy that Quintus secretly talked to Luke on the phone", "Juniper says she saw Quintus disappear into thin air"],
  ],
  "pj-04-ch-05": [
    ["Percy dreams that Kronos has already fully risen and defeated the gods", "Percy dreams that Luke has decided to betray Kronos"],
    ["It shows Annabeth already inside the Labyrinth searching without them", "It shows Grover finding Pan in a forest"],
    ["Nico summons the ghost of King Minos", "Nico summons the ghost of his sister, Bianca"],
    ["Theseus warns Nico that Percy cannot be trusted at all", "Theseus warns Nico that the Labyrinth has already collapsed"],
    ["The vision ends peacefully when Nico says goodnight", "Kronos appears in the fountain and speaks directly to Percy"],
  ],
  "pj-04-ch-06": [
    ["They find a modern gymnasium full of training dummies", "They find Daedalus's actual workshop full of blueprints"],
    ["They find the skeleton of a fallen demigod hero", "They find a cage holding a sleeping monster"],
    ["They meet Hermes, who asks Annabeth to deliver a hidden message", "They meet Morpheus, who tries to trap them all in a dream"],
    ["Chiron appears through a message to guide them", "Grover's satyr friends arrive to rescue them"],
    ["She tells them exactly where Daedalus's workshop is located", "She warns them that Quintus cannot be trusted"],
  ],
  "pj-04-ch-07": [
    ["They find themselves inside an ancient Greek dungeon", "They find themselves back at Camp Half-Blood's brig"],
    ["They find Tyson's long-lost Cyclops father", "They find Ethan Nakamura, chained up by Luke's forces"],
    ["Kampê is a former camp counselor who betrayed Chiron", "Kampê is Geryon's pet monster that guards his ranch"],
    ["Percy threatens Briares with his sword until he agrees to move", "Annabeth uses her invisibility cap to trick Briares into following her"],
    ["Grover charms Kampê to sleep with his reed pipes", "Briares scares Kampê away using his hundred hands"],
  ],
  "pj-04-ch-08": [
    ["Briares confesses that he secretly works for Luke", "Briares admits he doesn't trust Tyson"],
    ["They find one of Nico's black robes hanging on a rock", "They find a note written in ancient Greek addressed to Percy"],
    ["They emerge into the middle of Times Square in New York City", "They emerge onto a beach where Calypso lives"],
    ["Geryon is a three-headed dog who guards the ranch entrance", "Geryon is a former camp counselor who now works for Luke"],
    ["Percy agrees to fight Geryon's prize monster in exchange for their freedom", "Percy agrees to give Geryon his sword, Riptide, in trade for Nico"],
  ],
  "pj-04-ch-09": [
    ["Percy recalls that Theseus once cleaned a maze full of monsters", "Percy recalls that Jason once tamed fire-breathing bulls"],
    ["The naiad happily floods the stables herself", "The naiad refuses to speak to Percy at all and disappears"],
    ["Percy uses Riptide to dig a giant trench that drains the mess into the sea", "Percy convinces the monstrous horses to clean up after themselves"],
    ["Geryon happily lets everyone go as promised", "Geryon offers Percy a job managing the ranch"],
    ["Percy drowns Geryon using a giant wave", "Percy tricks Geryon into falling into his own manure pit"],
  ],
  "pj-04-ch-10": [
    ["Nico casts a spell that accidentally summons Kronos", "Nico's ritual accidentally wakes up Geryon's ghost"],
    ["Minos warns Nico that Pan has already died", "Minos warns Nico that Quintus is secretly a god"],
    ["Bianca tells Nico exactly how to bring her back to life", "Bianca warns Nico that Annabeth cannot be trusted"],
    ["Nico decides to join the quest group for the rest of the journey", "Grover announces he has already found Pan"],
    ["A talking eagle leads them straight to Daedalus's workshop", "They find a magic map that shows the entire Labyrinth at once"],
  ],
  "pj-04-ch-11": [
    ["They meet Daedalus himself, working at his true forge", "They meet Ares, guarding his personal armory"],
    ["He wants Percy to give up Riptide", "He wants them to defeat Kronos before he'll help"],
    ["Rachel and Nico head off to find Daedalus alone", "Chiron and Clarisse head back to camp for reinforcements"],
    ["They discover a group of runaway satyrs", "They discover Luke himself, working the forge in secret"],
    ["Annabeth pulls him out using a rope at the last second", "Hephaestus rescues Percy personally"],
  ],
  "pj-04-ch-12": [
    ["He wakes up back at Camp Half-Blood in the infirmary", "He wakes up in Hephaestus's workshop"],
    ["She's stuck there because she made a bad deal with Kronos", "She's stuck there because she lost a bet with Hermes"],
    ["He must choose between fighting a monster or fleeing the island", "He must choose whether to trust Calypso or turn her in to the gods"],
    ["Percy decides to stay on the island forever", "Percy escapes the island by swimming all the way back to camp"],
    ["She asks him to send her a letter every week", "She asks him to bring her back a gift from Camp Half-Blood"],
  ],
  "pj-04-ch-13": [
    ["Camp is celebrating the end of the war against Kronos", "Camp is holding a going-away party for Quintus"],
    ["He learns Quintus was captured by Luke's forces", "He learns Quintus has been promoted to run the whole camp"],
    ["Grover and Tyson have already returned safely to camp", "Grover has officially been given the title Lord of the Wild"],
    ["They disagree about whether to abandon the quest completely", "They disagree about whether Quintus can be trusted"],
    ["Percy recruits Clarisse, since she has already scouted parts of the maze", "Percy recruits Nico, since he can sense the dead"],
  ],
  "pj-04-ch-14": [
    ["Geryon's soldiers capture them and drag them back to the ranch", "Kampê and her monster army capture them"],
    ["Antaeus is actually Tyson's long-lost twin", "Antaeus was once a camper at Camp Half-Blood alongside Percy"],
    ["Percy takes Ethan prisoner and hands him over to Luke", "Percy lets Ethan go free but refuses to speak to him"],
    ["Percy drowns Antaeus using a wave of water", "Percy tricks Antaeus into fighting Ethan instead"],
    ["Rachel uses her mortal connections to call in help", "Annabeth uses her invisibility cap to sneak everyone out unnoticed"],
  ],
  "pj-04-ch-15": [
    ["It forces them into Hephaestus's forge again", "It forces them back to Geryon's ranch"],
    ["Quintus reveals that he has secretly been working for Kronos the whole time", "Quintus reveals that he is actually Percy's long-lost uncle"],
    ["He admits he sold Nico to Kronos's forces", "He admits he destroyed the entrance to the Labyrinth"],
    ["Grover arrives in chains, having just been captured by satyrs loyal to Kronos", "Rachel arrives in chains after being kidnapped by Kelli"],
    ["The group defeats all the monsters and calmly walks out the front door", "The group is trapped inside the workshop as it collapses"],
  ],
  "pj-04-ch-16": [
    ["They land in the ocean near Ogygia", "They crash into Camp Half-Blood's strawberry fields"],
    ["She uses her artistic talent to draw a map of the tunnels from memory", "She calls her father, who sends a helicopter to find the entrance"],
    ["He finds a room full of ancient scrolls about the Labyrinth", "He finds Daedalus's real, mortal body sleeping peacefully"],
    ["Inside is an empty coffin with nothing but dust", "Inside is Kronos's full, golden body already reassembled"],
    ["They scream that their master has been murdered", "They immediately attack Percy without saying a word"],
  ],
  "pj-04-ch-17": [
    ["Grover has been searching for his missing father", "Grover has been searching for a way to defeat Kronos"],
    ["They find Pan strong and ready to fight in the war", "They find Pan trapped in a cage by Luke's forces"],
    ["Pan tells Grover the exact location of Daedalus's workshop", "Pan tells Grover that Kronos cannot be defeated"],
    ["Pan transforms into a mortal and joins the group's quest", "Pan is captured and taken away by monsters"],
    ["Grover feels relieved that his search is finally over and goes back to normal life", "Grover feels angry at Percy for not helping him search sooner"],
  ],
  "pj-04-ch-18": [
    ["They emerge inside Camp Half-Blood's dining pavilion", "They emerge in Central Park, where Chiron is waiting with an army"],
    ["Grover tells Silenus that he's quitting as a satyr entirely", "Grover tells Silenus that Pan has been found alive and well"],
    ["Juniper's tree is chopped down by enemy soldiers", "Juniper's tree grows so large it blocks the Labyrinth entrance"],
    ["They successfully break through camp's defenses", "They surrender peacefully and are taken prisoner"],
    ["Percy says goodbye to Tyson, who returns to the ocean permanently", "Percy says goodbye to Nico, who leaves camp for good"],
  ],
  "pj-04-ch-19": [
    ["They immediately celebrate Grover as a hero", "They ask Grover to lead a new search party right away"],
    ["Poseidon returns, grieving over Percy's near-death experience", "Chiron returns from a long trip, upset about losing the war council vote"],
    ["Dionysus votes in favor of exiling Grover immediately", "Dionysus refuses to get involved and leaves the trial"],
    ["Grover is formally exiled and stripped of his searcher's license", "Grover is declared the new Lord of the Wild by unanimous vote"],
    ["He decides to give up being a satyr and live as a regular teenager", "He starts training to become a full-time camp sword instructor"],
  ],
  "pj-04-ch-20": [
    ["Hermes arrives to warn Percy about a message from Luke", "Athena arrives to warn Percy about Annabeth's safety"],
    ["He realizes the body actually belonged to Ethan Nakamura all along", "He realizes the sarcophagus was completely empty the whole time"],
    ["Daedalus chooses to flee into hiding forever", "Daedalus chooses to join Luke's army instead"],
    ["He spends the entire evening training for the next battle", "He spends the evening writing letters to Camp Half-Blood"],
    ["He throws the necklace away, feeling done with camp forever", "He gives the necklace to Tyson as a keepsake"],
  ],
  "pj-05-ch-01": [
    ["It was Grover Underwood coming to invite Percy to a satyr meeting.", "It was Nico di Angelo bringing news about the Underworld."],
    ["They were trying to rescue campers being held prisoner belowdecks.", "They were sent to steal Kronos's scythe while everyone slept."],
    ["He froze the fountain water solid and shattered the crab's shell.", "He tricked the crab into snapping at its own reflection in a mirror."],
    ["Percy managed to knock Kronos's helmet off before more monsters arrived.", "Kronos refused to fight and ordered the giants to attack instead."],
    ["He convinced them he was actually a kitchen worker delivering snacks.", "He hid the real bombs inside a fake wooden crate labeled \"Toys.\""],
  ],
  "pj-05-ch-02": [
    ["He woke up in the Big House infirmary at Camp Half-Blood.", "He woke up on Blackjack's back, flying back to camp."],
    ["Beckendorf had been captured and was being held prisoner by Kronos.", "Beckendorf had washed ashore safely on Long Island."],
    ["Poseidon had disguised himself as an old man so enemy spies wouldn't recognize him.", "A curse from Amphitrite had temporarily transformed his appearance."],
    ["Triton is Poseidon's loyal dolphin messenger who happily welcomed Percy.", "Triton is an enemy Titan who had infiltrated the palace in disguise."],
    ["Poseidon asked Percy to find Triton and convince him to retreat.", "Poseidon asked Percy to bring Tyson back to camp with him."],
  ],
  "pj-05-ch-03": [
    ["Everyone cheered wildly, thinking the mission was a total success.", "Chiron immediately banned Percy from going on future missions."],
    ["They were arguing about who should lead the next mission to find Kronos.", "They were arguing over whose cabin had the best decorations for the summer."],
    ["They showed him a hidden map that revealed where Kronos's ship was hiding.", "They introduced him to a brand-new camper who had just arrived."],
    ["The line about \"endless sleep\" made him worry the whole camp would be put under a spell forever.", "The line about \"eldest gods\" made him think his father was going to disappear."],
    ["They saw Kronos's army building a second cruise ship to replace the destroyed one.", "They saw the Empire State Building already collapsing in ruins."],
  ],
  "pj-05-ch-04": [
    ["She painted a peaceful beach scene of their upcoming vacation to St. Thomas.", "She painted a portrait of Chiron guarding Camp Half-Blood."],
    ["They discovered a secret tunnel underneath the Poseidon cabin.", "They found out the Ares cabin had been secretly recruiting new campers."],
    ["They argued about who should be named the new camp leader.", "They argued over how to punish the Stoll brothers for a prank."],
    ["They burned old camp banners to make room for new ones.", "They burned a model of the Princess Andromeda to celebrate its destruction."],
    ["She said her cabin was too injured from a recent battle to help.", "She demanded that Percy apologize for something he'd said the summer before."],
  ],
  "pj-05-ch-05": [
    ["He found Clarisse crying about the argument over the chariot.", "He found Annabeth searching for a lost map of the Labyrinth."],
    ["Nico said Beckendorf's ghost was angry and wanted revenge on Kronos.", "Nico said he couldn't find any trace of Beckendorf's spirit at all."],
    ["Nico revealed he had found Kronos's hidden throne room.", "Nico revealed that Chiron was secretly working with the enemy."],
    ["Percy decided to give up fighting and take Rachel's vacation offer instead.", "Percy decided to challenge Clarisse to a duel to force her cabin back into the war."],
    ["They flew there on Blackjack the pegasus.", "They borrowed Paul's car and drove there themselves."],
  ],
  "pj-05-ch-06": [
    ["The house was actually abandoned and completely empty inside.", "The house was filled with weapons she had collected to fight monsters herself."],
    ["She said Luke asked her for money to buy a new sword.", "She said Luke brought her a gift from Camp Half-Blood as an apology."],
    ["She suddenly remembered exactly where Luke was hiding and gave them directions.", "She fainted from exhaustion after baking too many cookies."],
    ["Hestia was a camp counselor who scolded them for running off without permission.", "Hestia was Annabeth's mother in disguise, checking up on Percy."],
    ["Sally forbade Percy from doing anything dangerous and grounded him.", "Sally insisted on coming along to protect Percy herself."],
  ],
  "pj-05-ch-07": [
    ["They found Grover awake and camping out, hiding from monsters on purpose.", "They found Grover had turned into a full satyr elder and could no longer speak."],
    ["They took Charon's ferry from Los Angeles like Percy had before.", "Mrs. O'Leary dug a tunnel straight down through the ground."],
    ["Nico had agreed to steal Percy's sword and give it to Hades.", "Nico had promised to convince Percy to fight for the Underworld army instead of the gods."],
    ["Hades revealed that Nico and Bianca were actually adopted, not his real children.", "Hades revealed that their mother was still alive somewhere in the mortal world."],
    ["Hades challenged Percy to a duel to test his strength.", "Hades sent Percy back to camp with a stern warning."],
  ],
  "pj-05-ch-08": [
    ["Achilles warned Percy never to use Riptide again after entering the river.", "Achilles warned that only campers born after a certain year could survive the ritual."],
    ["He chose his left shoulder, and he thought of his mother's voice to survive.", "He chose the back of his neck, and he thought of Grover's music to survive."],
    ["Percy immediately collapsed and had to be carried out by Mrs. O'Leary.", "Kronos himself appeared to finish Percy off before he could recover."],
    ["Percy and Hades shook hands and agreed to team up against Kronos.", "Hades apologized and released Percy from his earlier punishment."],
    ["Percy told Nico to stay hidden in the Underworld until the war was over.", "Percy told Nico to warn Chiron that Hades could not be trusted at all."],
  ],
  "pj-05-ch-09": [
    ["Chiron was too injured from a recent battle to travel with them.", "Chiron secretly didn't trust the campers and stayed behind to guard camp instead."],
    ["Ares greeted them and offered to lead the defense himself.", "Nobody came at all, and the campers were left completely alone in the throne room."],
    ["Hermes was angry that Annabeth had lost his favorite winged sandals.", "Hermes accused Annabeth of stealing his caduceus staff."],
    ["Hestia showed him a vision of Beckendorf still alive and hiding somewhere.", "Hestia showed him exactly where Kronos's army was hiding in New Jersey."],
    ["They discovered the whole city had been evacuated by the police.", "They discovered the Empire State Building itself was crumbling apart."],
  ],
  "pj-05-ch-10": [
    ["She used a magic mirror that Athena had given her that morning.", "She used binoculars borrowed from a nearby camera shop."],
    ["He kept every camper together in one big group at the Empire State Building.", "He sent all the campers home to protect Camp Half-Blood instead."],
    ["It was a code word that would summon Zeus himself to help.", "It was a hidden escape tunnel underneath the city."],
    ["He challenged them both to an underwater wrestling match and won.", "He promised to introduce them to Poseidon in person if they helped."],
    ["She reported that Clarisse had finally agreed to bring the Ares cabin to help.", "She reported that Rachel had arrived safely at camp."],
  ],
  "pj-05-ch-11": [
    ["Percy tricked the Minotaur into charging off the bridge by himself.", "Annabeth distracted the Minotaur while Percy snuck up from behind."],
    ["Percy recognized Beckendorf, very much alive and fighting for Kronos.", "Percy recognized Luke's old friend Chris Rodriguez among the enemy."],
    ["Grover blocked the blow with his reed pipes at the last second.", "The strike missed completely because Percy's new invincibility protected him everywhere."],
    ["He asked the river gods to flood the entire bridge and wash the army away.", "He convinced the Party Ponies to charge in and scatter the enemy."],
    ["Michael Yew was seen flying safely back toward camp on a chariot.", "Michael Yew called Percy on the phone to say he was okay."],
  ],
  "pj-05-ch-12": [
    ["He told her he was thinking about accepting immortality from the gods.", "He told her that Beckendorf's ghost had spoken to him in a dream."],
    ["She admitted that she used to secretly work as a spy for Luke.", "She admitted that Luke had once tried to steal her invisibility cap."],
    ["He reported that all the satyrs had abandoned their posts and fled the city.", "He reported that Juniper had been captured by enemy forces."],
    ["He learned the Oracle chose on its own never to speak again after a bad prophecy.", "He learned Zeus destroyed the original Oracle out of jealousy."],
    ["Rachel discovered she could suddenly talk to animals and used that to warn her father.", "Rachel discovered a hidden treasure map and used it to bargain with her father."],
  ],
  "pj-05-ch-13": [
    ["Ares arrived to demand the campers surrender their weapons.", "Luke himself arrived, asking to speak with Percy alone."],
    ["He explained that Kronos had rescued him from a monster attack as a child.", "He explained that he lost his eye fighting alongside Percy the previous summer."],
    ["He saw a vision of Kronos being defeated by the original Olympian gods.", "He saw a vision of Beckendorf's final moments on the Princess Andromeda."],
    ["He gave Percy a map showing every hiding spot of Kronos's forces.", "He gave Percy a magic shield that could block any weapon."],
    ["A fight broke out and Percy chased Prometheus away.", "Prometheus agreed to switch sides and help the campers instead."],
  ],
  "pj-05-ch-14": [
    ["The battle took place at the Empire State Building lobby, against Kronos himself.", "The battle took place at the Brooklyn Bridge, against a new army of giants."],
    ["They convinced Hyperion to switch sides and fight for the campers instead.", "They used Greek fire to burn Hyperion until he retreated."],
    ["He sent a fully armored army of skeleton warriors.", "He sent Typhon himself early to attack New York."],
    ["He lured the pig into the East River, where the river god drowned it.", "He used his sword to cut off its wings so it couldn't fly anymore."],
    ["Kronos openly admitted defeat and offered to surrender to the gods.", "Kronos revealed the exact location of Percy's one weak spot."],
  ],
  "pj-05-ch-15": [
    ["Poseidon arrived personally to fight alongside the campers.", "Clarisse finally arrived with the whole Ares cabin."],
    ["Typhon had defeated Zeus and taken over Mount Olympus already.", "Typhon had captured Poseidon's underwater palace."],
    ["Dionysus warned that the campers should surrender immediately to save lives.", "Dionysus warned that Percy's mother was in danger back home."],
    ["He found a secret note from Luke warning him about a trap.", "He found that Blackjack had been hiding there the whole time."],
    ["Rachel arrived riding on the back of a hippocampus.", "Rachel walked in calmly through the front doors of the Plaza Hotel."],
  ],
  "pj-05-ch-16": [
    ["Percy used his water powers to gently guide the helicopter down.", "Chiron flew up and towed the helicopter safely to the ground."],
    ["She warned him that Annabeth was secretly working against him.", "She warned him that Chiron was planning to retreat from the city."],
    ["The Minotaur returned for a second attack on the city.", "The Clazmonian Sow came back for revenge."],
    ["It was Annabeth, wearing borrowed Ares armor to surprise the enemy.", "It was Thalia, who had swapped armor with Clarisse as a trick."],
    ["It turned out to be Rachel Dare, who had secretly joined the fight.", "It turned out to be Ethan Nakamura, who had switched sides to help them."],
  ],
  "pj-05-ch-17": [
    ["She revealed that Clarisse had asked her to wear the armor as part of a prank.", "She revealed that she had secretly been planning to switch sides back to the campers all along."],
    ["Clarisse quietly returned to camp, too devastated to keep fighting.", "Clarisse blamed Percy for Silena's death and refused to speak to him."],
    ["She admitted that she wanted to give up architecture and become a warrior instead.", "She admitted she had known about Silena's secret the whole time."],
    ["Percy opened the jar to see what would happen, just out of curiosity.", "Percy threw the jar into the Hudson River to get rid of it for good."],
    ["He asked Poseidon to make him a god right there on the spot.", "He asked Poseidon to send Tyson home to safety immediately."],
  ],
  "pj-05-ch-18": [
    ["Chiron defeated Kronos single-handedly and ended the battle early.", "Chiron retreated safely once his arrows ran out."],
    ["Poseidon arrived with an army of Cyclopes and mermen.", "Chiron's centaur army returned with reinforcements from every state."],
    ["He collapsed the elevator shaft so no one could reach Olympus at all.", "He turned the whole building invisible so mortals couldn't see the fight."],
    ["They stayed safely hidden in their car the entire time.", "They called the police to handle the monsters instead of fighting themselves."],
    ["He asked her to guard Percy's parents at the barrier's edge.", "He asked her to carry Silena's shroud back to camp."],
  ],
  "pj-05-ch-19": [
    ["He knocked Kronos's scythe into the hearth fire, melting it instantly.", "He convinced Kronos to fight Annabeth instead so he could rest."],
    ["Ethan refused to fight at all and simply walked away from the battle.", "Ethan struck Percy anyway but missed by accident."],
    ["Grover's music finally broke the spell holding Luke under Kronos's control.", "Drinking a potion from Chiron restored Luke's mind instantly."],
    ["Percy chose to throw the knife into the hearth instead of using it.", "Percy chose to strike Kronos himself while Luke was distracted."],
    ["Luke tricked Kronos into falling into the hearth fire and escaped unharmed.", "Luke defeated Kronos but then flew away to recover somewhere secret."],
  ],
  "pj-05-ch-20": [
    ["He realized it meant Riptide would eventually have to be destroyed forever.", "He realized it meant Kronos's scythe would one day kill a god."],
    ["He asked for fireworks to be set off over the whole city.", "He asked Zeus to send a message directly to Rachel's family."],
    ["Annabeth was made a goddess, and Grover was given Poseidon's trident to guard.", "Annabeth was sent to guard the Underworld, and Grover was made a Party Pony general."],
    ["Percy accepted immediately and became the newest Olympian god.", "Percy asked to be made king of the Cyclopes instead."],
    ["He asked that Camp Half-Blood be moved somewhere safer, far from New York.", "He asked that Kronos be completely destroyed once and for all, with no chance of returning."],
  ],
  "pj-05-ch-21": [
    ["Hermes confirmed that Kronos had been permanently destroyed and could never return.", "Hermes said Kronos had been imprisoned again in Tartarus for good."],
    ["He asked Percy to adopt one of his unclaimed children personally.", "He asked Percy to keep the list a secret from Chiron."],
    ["Athena thanked him warmly and offered him a permanent seat on Olympus.", "Athena ignored him completely and walked away without a word."],
    ["He reunited with Beckendorf, who had somehow survived after all.", "He reunited with Silena, who had recovered from her injuries."],
    ["Nico reported that Kronos's scattered dust had already started to reform.", "Nico reported that Clarisse had been badly hurt and needed help."],
  ],
  "pj-05-ch-22": [
    ["They borrowed a car and drove straight up the highway.", "They flew there together on the back of Mrs. O'Leary."],
    ["Rachel decided to enroll at Camp Half-Blood as a full-time camper.", "Rachel challenged Clarisse to a duel to prove she belonged at camp."],
    ["She said, \"A single choice shall end his days,\" repeating the old prophecy.", "She predicted the exact day Kronos would return to attack again."],
    ["It turned out Percy was actually turning seventeen, not sixteen.", "It turned out Percy shared his birthday with Grover."],
    ["They had a big argument and didn't speak for the rest of the night.", "They announced they were both leaving camp for good."],
  ],
  "pj-05-ch-23": [
    ["The camp was shrinking because so many campers had decided to leave for good.", "The camp was being moved to a brand-new location outside New York."],
    ["Poseidon asked Percy to move permanently to his underwater palace.", "Poseidon revealed that Triton would be visiting camp very soon."],
    ["It showed a picture of the Princess Andromeda exploding at sea.", "It showed Rachel's face as a tribute to the new Oracle."],
    ["Both girls decided to stay at Camp Half-Blood all year round.", "Rachel and Annabeth were both moving away to California together."],
    ["The book ends with Percy accepting the gods' offer of immortality after all.", "The book ends with Kronos reappearing to attack the camp one more time."],
  ],
};

export default percyJacksonDistractors;
