import type { DistractorMap } from "./index";

const percyJacksonDistractors: DistractorMap = {
  "pj-01-ch-01": [
    ["They go to the Museum of Natural History to see dinosaur bones.", "They go to a science museum to see a space exhibit."],
    ["She falls down a flight of museum stairs and has to go to the hospital.", "She gets locked inside an exhibit room and has to be rescued by security."],
    ["He throws Percy a Greek shield from the museum display.", "He throws Percy his own wheelchair cane to use as a weapon."],
    ["Everyone remembers Mrs. Dodds perfectly but refuses to talk about the attack.", "Everyone believes Percy made up the whole story to get attention."],
    ["Percy feels excited because he loves studying pre-algebra.", "Percy feels proud because he's the top student in his class."],
  ],
  "pj-01-ch-02": [
    ["He overhears them planning a surprise party for his birthday.", "He overhears them arguing about Percy's low grades in Latin class."],
    ["Percy is expelled for fighting with Nancy Bobofit.", "Percy chooses to leave early because he misses his mom."],
    ["Grover admits he was paid by the school to spy on Percy.", "Grover admits he's actually failing all of his classes too."],
    ["The women offer Percy and Grover free fruit and a ride home.", "The women warn Percy that his bus is about to break down."],
    ["Percy feels relieved because Grover finally explains everything clearly.", "Percy feels bored because nothing unusual happens on the bus ride."],
  ],
  "pj-01-ch-03": [
    ["She takes him to visit his grandparents in another state.", "She takes him camping in the mountains for the weekend."],
    ["He dreams about Mrs. Dodds chasing him through the museum again.", "He dreams about winning a big pre-algebra competition at school."],
    ["Gabe shows up unexpectedly and demands they come home.", "The police arrive looking for Percy about the museum incident."],
    ["Percy notices Grover has a cast on his leg from an injury.", "Percy notices Grover is wearing several layers of extra clothing."],
    ["Sally laughs it off and tells Grover to calm down.", "Sally calls Gabe to come pick them up instead of driving herself."],
  ],
  "pj-01-ch-04": [
    ["Grover explains that he's actually a runaway prince from a foreign country.", "Grover explains that Mr. Brunner is secretly a famous spy."],
    ["A giant serpent with multiple heads attacks them.", "A pack of wild wolves surrounds the wrecked car."],
    ["She is knocked unconscious but Percy manages to carry her to safety.", "She hides inside the wrecked car until the monster leaves."],
    ["Percy traps the Minotaur inside the wrecked car and lets it explode.", "Percy distracts the Minotaur with a flashlight until it wanders off a cliff."],
    ["He sees his mother waving to him from a car driving away.", "He sees a group of police officers rushing toward him."],
  ],
  "pj-01-ch-05": [
    ["Percy wakes up in a hospital bed in New York City.", "Percy wakes up back in his old bedroom at his mom's apartment."],
    ["Grover feeds him ordinary hospital soup and crackers.", "Grover feeds him a strange bitter medicine that tastes terrible."],
    ["Percy meets Clarisse and Luke playing cards together.", "Percy meets his mother and Grover's uncle at the card table."],
    ["Mr. D reveals he used to be Percy's father's best friend.", "Mr. D reveals he is actually Grover's long-lost uncle."],
    ["Mr. Brunner reveals he is actually a retired Greek soldier.", "Mr. Brunner reveals he can turn invisible whenever he wants."],
  ],
  "pj-01-ch-06": [
    ["Chiron shows Percy a hidden library full of ancient weapons.", "Chiron shows Percy an underground tunnel leading to the ocean."],
    ["Cabin Eleven is simply the only cabin with an empty bed.", "Percy is assigned there as a punishment for arriving late."],
    ["Clarisse succeeds in dunking Percy, embarrassing him in front of everyone.", "Percy fights back and gets both of them sent to see Chiron."],
    ["Clarisse is Chiron's daughter and helps run the camp.", "Clarisse is from Cabin Eleven, just like Percy."],
    ["Annabeth says she wants to be his training partner for sword fighting.", "Annabeth says she wants him to help her fix the camp's boundary magic."],
  ],
  "pj-01-ch-07": [
    ["Annabeth tells Percy both of her parents are ordinary mortals.", "Annabeth tells Percy her father is a famous war general."],
    ["Annabeth reveals that a camper stole gold from the camp's treasury.", "Annabeth reveals that Mr. D's throne was destroyed in a fire."],
    ["Luke tells Percy that he has never been allowed to go on a quest.", "Luke tells Percy that his quest was actually a huge success."],
    ["Campers write letters to the gods and mail them overnight.", "Campers sing a song in ancient Greek before eating."],
    ["Mr. D gives a warm, heartfelt speech welcoming Percy to camp.", "Mr. D refuses to acknowledge Percy in front of the other campers at all."],
  ],
  "pj-01-ch-08": [
    ["Grover tells Percy that the Big Three gods never speak to each other anymore.", "Grover tells Percy that the Big Three gods are actually all brothers of Chiron."],
    ["Percy is captured and has to be rescued by Annabeth's team.", "Percy loses the fight and is knocked out of the game."],
    ["A swarm of giant hornets attacks the players in the woods.", "A pack of wild wolves interrupts the game near the flag."],
    ["A glowing lightning bolt symbol appears above Percy's head.", "A glowing owl symbol appears above Percy's head."],
    ["Clarisse's team captures the flag despite losing the fight with Percy.", "Percy personally captures the flag right after being claimed."],
  ],
  "pj-01-ch-09": [
    ["Percy is moved there as punishment for the bathroom incident.", "Percy asks to be moved because he doesn't get along with Luke."],
    ["They tell him that Camp Half-Blood is about to run out of money.", "They tell him that Chiron's centaur family has gone missing."],
    ["Percy visits a temple deep in the strawberry fields.", "Percy is taken to a hidden cave beneath the dining pavilion."],
    ["The prophecy tells Percy he will become the next ruler of Olympus.", "The prophecy tells Percy he must never leave camp again."],
    ["Percy refuses the quest and asks Chiron to send someone else instead.", "Percy asks for more time to think it over before deciding."],
  ],
  "pj-01-ch-10": [
    ["Percy chooses Clarisse and Luke to accompany him.", "Percy decides to go completely alone to keep his friends safe."],
    ["Percy receives a suit of golden armor and a chariot.", "Percy receives a map that shows exactly where the bolt is hidden."],
    ["Clarisse secretly follows them and boards the same bus.", "A group of reporters recognize Percy and board to interview him."],
    ["Percy takes the cap and escapes out the emergency exit alone.", "Percy gives the cap to Grover so he can escape instead."],
    ["The bus breaks down and simply refuses to start again.", "The bus driver crashes it into a ditch trying to escape the monsters."],
  ],
  "pj-01-ch-11": [
    ["The garden gnomes are all wearing tiny Camp Half-Blood shirts.", "The garden gnomes are actually robots in disguise."],
    ["Grover recognizes a statue of his own mother among the gnomes.", "Grover recognizes a statue of Chiron among the gnomes."],
    ["Aunty Em turns out to be one of the three Furies in disguise.", "Aunty Em turns out to be Clarisse's mother in disguise."],
    ["Percy closes his eyes completely and swings his sword blindly.", "Percy throws sand in Medusa's face to blind her before attacking."],
    ["Percy buries Medusa's head so no one can ever find it.", "Percy keeps Medusa's head as a trophy to bring back to camp."],
  ],
  "pj-01-ch-12": [
    ["Grover uses a magic whistle to communicate with the poodle.", "Grover reads the poodle's mind using a spell Annabeth taught him."],
    ["The family gives them a car instead of a cash reward.", "The poodle leads them straight to the stolen lightning bolt."],
    ["Percy notices an article announcing that Gabe has been arrested.", "Percy notices an article about a school reunion at Yancy Academy."],
    ["Percy sees a group of satyrs playing music in a field.", "Percy sees a giant eagle carrying off a farm animal."],
    ["Percy sees Clarisse's face reflected in the train window.", "Percy sees a shadowy figure that looks exactly like Luke."],
  ],
  "pj-01-ch-13": [
    ["Annabeth insists on visiting a famous art museum in St. Louis.", "Annabeth insists on visiting an ancient Greek exhibit at a library."],
    ["Percy is left alone with a tour guide and a park ranger.", "Percy is left alone with two mysterious teenagers his age."],
    ["The woman turns out to be one of the Furies in a new disguise.", "The woman turns out to be Medusa's twin sister."],
    ["Percy's sword turns back into a harmless pen mid-fight.", "Percy accidentally drops his sword down the elevator shaft."],
    ["Echidna dares Percy to fight the Chimera bare-handed.", "Echidna dares Percy to hand over his invisibility cap."],
  ],
  "pj-01-ch-14": [
    ["Percy gets swept far downstream and has to swim for hours to shore.", "Percy loses consciousness underwater and wakes up on the riverbank."],
    ["Percy meets his father, Poseidon, in person underwater.", "Percy meets a talking dolphin who guides him back to shore."],
    ["News reports say the Arch has been closed for routine repairs.", "News reports praise Percy as a hero for saving tourists."],
    ["A fish delivers the sword back to Percy in its mouth.", "Percy has to buy a brand new sword once he reaches shore."],
    ["They head straight back to New York to check on Percy's mother.", "They decide to hide out in St. Louis until things calm down."],
  ],
  "pj-01-ch-15": [
    ["Grover mails a letter using regular postal mail.", "Grover borrows a stranger's phone to call Chiron directly."],
    ["A kind waitress secretly covers the bill for them.", "Annabeth pays using drachmas she had saved from camp."],
    ["The stranger turns out to be Luke's father in disguise.", "The stranger turns out to be Dionysus checking up on Percy."],
    ["Ares offers to fight Percy's battles for him for the rest of the quest.", "Ares offers to reveal exactly who stole the master bolt."],
    ["The shield is guarded by a real, live hellhound.", "The shield simply isn't there, and they find an empty pedestal instead."],
  ],
  "pj-01-ch-16": [
    ["Ares gives Percy a magical shield that can never be broken.", "Ares gives Percy a map showing exactly where the lightning bolt is."],
    ["Percy quietly reports the truck driver to the police instead.", "Percy convinces the animals to stay put until help arrives."],
    ["The doorman leads them to a free hotel meant for stranded travelers.", "The doorman leads them to a secret meeting with Chiron."],
    ["Percy realizes the casino is run by Medusa's family.", "Percy realizes the casino card he was given is completely fake."],
    ["They leave because security starts chasing them for cheating at games.", "They leave because Clarisse suddenly shows up at the casino."],
  ],
  "pj-01-ch-17": [
    ["The store is run by a disguised version of Ares.", "The store is run by an ordinary salesman with no myth connection at all."],
    ["Crusty tries to sell them beds at an unfairly high price.", "Crusty locks Annabeth and Grover in a storage room."],
    ["Percy convinces Crusty to let his friends go through negotiation.", "Percy simply outruns Crusty and escapes with his friends."],
    ["Percy finds a hidden map showing the way back to Camp Half-Blood.", "Percy finds a letter revealing that Ares stole the master bolt himself."],
    ["It means they can finally return home without finishing the quest.", "It means they no longer need to worry about the missing lightning bolt."],
  ],
  "pj-01-ch-18": [
    ["The sea spirit gives Percy a new, stronger sword.", "The sea spirit gives Percy a map straight to his father's palace."],
    ["They defeat Charon in a sword fight to get past him.", "They sneak past Charon using Annabeth's invisibility cap the whole way."],
    ["Cerberus refuses to let anyone through no matter what they try.", "Cerberus chases them all the way back to the entrance."],
    ["Annabeth sings a lullaby that puts Cerberus to sleep instantly.", "Annabeth offers Cerberus food until he loses interest in them."],
    ["They turn back, deciding the risk is too great to continue.", "They wait at the entrance for Chiron to catch up with them."],
  ],
  "pj-01-ch-19": [
    ["Hades accuses Percy of freeing souls from the Underworld.", "Hades accuses Percy of stealing his throne."],
    ["Percy finds Hades's helm of darkness inside his backpack.", "Percy finds a letter from Luke inside his backpack."],
    ["It reveals conclusively that Luke stole both items himself.", "It reveals that Ares definitely stole both items on his own."],
    ["Hades threatens to turn Percy's mother into a ghost permanently.", "Hades threatens to send Percy's mother to fight in the arena."],
    ["They escape by convincing Charon to ferry them back across the river.", "They escape through a secret tunnel that Annabeth discovers."],
  ],
  "pj-01-ch-20": [
    ["The pearls carry them straight back to Camp Half-Blood.", "The pearls carry them to the top of the Empire State Building."],
    ["Ares confesses that he actually stole the bolt for Zeus as a test.", "Ares confesses that Chiron secretly helped plan the whole scheme."],
    ["Ares sends a pack of hellhounds after Percy.", "Ares sends the Chimera to attack Percy again."],
    ["Percy defeats Ares by tricking him into stepping into quicksand.", "Percy defeats Ares by using Medusa's head to turn him to stone."],
    ["Percy finds the master bolt buried in the sand instead of the helm.", "Percy buries the helm again so no one can ever use it."],
  ],
  "pj-01-ch-21": [
    ["The manhunt is called off because Percy turned eighteen.", "The manhunt is called off because Ares confessed publicly to the police."],
    ["Percy sends his friends home and quits the quest entirely.", "Percy insists all three of them go together to see Zeus."],
    ["Percy mails the bolt back to Olympus using Hermes Express.", "Percy meets Zeus at Camp Half-Blood to hand over the bolt."],
    ["Percy suspects that Mr. D orchestrated the whole plot.", "Percy suspects that Chiron secretly orchestrated the whole plot."],
    ["Poseidon tells Percy his mother has decided to move to Camp Half-Blood.", "Poseidon tells Percy his mother has lost all her memories of him."],
  ],
  "pj-01-ch-22": [
    ["The camp holds a quiet ceremony with no celebration at all.", "The camp punishes Percy for taking too long to complete the quest."],
    ["Luke reveals that he is actually Percy's older half-brother.", "Luke reveals that he plans to leave camp and become a mortal."],
    ["Luke admits he told Ares to steal the shield from Waterland.", "Luke admits he tipped off Echidna about their location at the Arch."],
    ["Luke leaves Percy to be captured by camp security instead.", "Luke leaves Percy stranded outside the camp's magic borders."],
    ["Poseidon explains that Kronos is actually Luke's real father.", "Poseidon explains that Kronos is a monster Percy already defeated on his quest."],
  ],
  "pj-02-ch-01": [
    ["Percy dreams that he is fighting the Minotaur again on top of Half-Blood Hill.", "Percy dreams that Annabeth is trapped inside a maze guarded by a dragon."],
    ["It's the day of Percy's final exam in Ancient Greek mythology class.", "It's the first day of a brand new school Percy just transferred to."],
    ["She tells him that Camp Half-Blood has been closed down permanently by Mr. D.", "She tells him that Grover has already been kicked out of camp for good."],
    ["He notices Tyson sleeping on the sidewalk outside his building.", "He notices a bronze bull statue that seems to be watching him."],
    ["The monster spots Grover's reflection in a store window and charges through the glass.", "The monster follows a trail of enchanted acorns that Grover dropped by accident."],
  ],
  "pj-02-ch-02": [
    ["Tyson is a new exchange student from Greece who nobody has met before.", "Tyson is Percy's cousin who just moved in with Percy's family."],
    ["The dodgeballs turn out to be cursed and start chasing kids around the gym on their own.", "Matt Sloan is revealed to be a monster in disguise who attacks Percy."],
    ["Tyson pulls out a hidden sword and starts fighting like a trained warrior.", "Tyson suddenly speaks fluent Ancient Greek to command the monsters to stop."],
    ["Grover shows up playing his reed pipes to calm the monsters down.", "Chiron gallops into the gym in full centaur form to fight the monsters."],
    ["The gym catches fire and the whole school has to be evacuated for the day.", "The gym floor cracks open into a hole leading straight to the Underworld."],
  ],
  "pj-02-ch-03": [
    ["They hail a taxi driven by a friendly satyr who moonlights as a cab driver.", "They call on Chiron to send a camp van to pick them up."],
    ["The sisters drive with their eyes completely closed because they trust the taxi's magic to steer.", "The sisters use a single enchanted mirror instead of an eye to see where they're going."],
    ["They hand Percy a detailed treasure map showing exactly where the Golden Fleece is hidden.", "They tell Percy exactly which day and hour Camp Half-Blood will fall if he doesn't act."],
    ["Tyson calmly reads a book the entire ride, unbothered by the chaos.", "Tyson falls asleep immediately and misses the whole ride."],
    ["The taxi drops them off at the airport so they can catch a flight to Florida.", "The taxi breaks down halfway there, forcing them to walk the rest of the way."],
  ],
  "pj-02-ch-04": [
    ["They find that lightning has struck the tree and burned it completely to ash.", "They discover that someone has chopped the tree down overnight."],
    ["A pack of hellhounds surrounds them and tries to drag them into the woods.", "A giant fire-breathing dragon guarding the camp's treasure attacks them."],
    ["Tyson uses a magic shield Chiron gave him earlier to block the bull's fire.", "Tyson tricks the bull into chasing its own tail until it short-circuits."],
    ["Percy suspects Tyson has been secretly training with the Ares cabin for years.", "Percy suspects Tyson is actually a god in disguise testing him."],
    ["Camp Half-Blood is announced to be completely safe again once the bull is defeated.", "Camp Half-Blood is evacuated entirely and everyone moves to a new secret location."],
  ],
  "pj-02-ch-05": [
    ["All the campers immediately throw Tyson a huge welcome party.", "The campers ignore Tyson completely and pretend he isn't there."],
    ["A glowing owl appears above Tyson's head, marking him as a child of Athena.", "A golden laurel wreath appears above Tyson's head, marking him as a child of Apollo."],
    ["Tyson is given his own private cabin built specially for cyclopes.", "Tyson is sent to live in the Hermes cabin with the unclaimed campers."],
    ["Percy is furious and immediately demands that Tyson be sent away from camp.", "Percy feels nothing at all and barely notices Tyson moving in."],
    ["Chiron announces that the campfire sing-alongs are being canceled for the summer.", "Chiron reveals that Mr. D has quit and left camp for good."],
  ],
  "pj-02-ch-06": [
    ["A swarm of giant metal bees attacks the camp's apple orchard.", "A flock of harpies attacks the camp's dining pavilion during dinner."],
    ["The birds are alarming because they can only be killed with a rare golden arrow no one has.", "The birds are alarming because they specifically target the camp's food supply and nothing else."],
    ["They lure the birds away using a giant magnet borrowed from the Hephaestus cabin.", "They trap all the birds inside the camp's climbing wall cave."],
    ["Tyson hides in his cabin the whole time, too frightened to help.", "Tyson uses a magic whistle to command the birds to fly away peacefully."],
    ["It becomes clear that the birds were actually sent by Chiron as a training exercise.", "It becomes clear that camp is no longer in any danger since the birds were easily beaten."],
  ],
  "pj-02-ch-07": [
    ["Chiron chooses Annabeth to lead the quest all on her own.", "Chiron announces that no one will be sent on a quest this time."],
    ["Percy's father Poseidon rises out of a nearby lake to hand him a magic trident.", "Chiron secretly sneaks off camp grounds to deliver the gifts himself."],
    ["Percy receives an invisible cloak and a set of enchanted throwing knives.", "Percy receives a magic map that shows the exact location of the Golden Fleece."],
    ["Hermes asks Percy to deliver a secret letter to Zeus on Mount Olympus.", "Hermes asks Percy to bring Clarisse back to camp safely no matter what."],
    ["Percy feels annoyed and ungrateful, wishing he'd been given better gifts.", "Percy feels completely unaffected and quickly forgets about the whole meeting."],
  ],
  "pj-02-ch-08": [
    ["They swim the entire distance with help from friendly dolphins.", "They ride on the back of a giant hippocampus the whole way there."],
    ["The Princess Andromeda is an old shipwreck haunted by ghostly sailors.", "The Princess Andromeda is a floating amusement park built by Hermes."],
    ["They discover a locked cage holding dozens of captured campers.", "They discover a room full of duplicate Golden Fleeces meant to trick heroes."],
    ["The ship's alarm system goes off automatically the moment they step aboard.", "A camp counselor spots them right away and forces them to leave."],
    ["It reveals that Luke has actually given up his plans and wants to return to camp.", "It reveals that the ship is simply a decoy with nothing important on board."],
  ],
  "pj-02-ch-09": [
    ["Ares confronts Percy, furious about Clarisse's quest being interrupted.", "Mr. D confronts Percy after tracking him down using magic."],
    ["Luke reveals he was cursed by a monster and has no control over his own actions.", "Luke reveals he's actually working undercover to spy on the gods for Chiron."],
    ["The ship is crewed entirely by robotic sailors built by the Hephaestus cabin.", "The ship is crewed by ghosts of ancient Greek sailors under Luke's command."],
    ["Luke apologizes and lets them all walk off the ship peacefully.", "Chiron arrives just in time to arrest Luke and end the standoff."],
    ["They convince Luke's crew to give them a ride back to shore in a helicopter.", "They use Percy's flying shoes to fly the entire way back to camp instantly."],
  ],
  "pj-02-ch-10": [
    ["They encounter a modern navy ship that rescues them and radios for help.", "They encounter a floating island made entirely of driftwood and seaweed."],
    ["The ghost sailors constantly try to warn Percy about the Golden Fleece's true location.", "The ghost sailors immediately attack Percy and his friends on sight."],
    ["The ghost captain refuses to help unless they pay with real gold coins.", "The ghost captain locks them in the ship's brig until they prove they're heroes."],
    ["They're glad because the ghost ship has a full kitchen serving warm meals.", "They're glad because the ghost ship can fly them straight to camp."],
    ["It suggests the waters are actually completely safe once you know the right paths.", "It suggests they have accidentally traveled back in time to the Civil War."],
  ],
  "pj-02-ch-11": [
    ["They run into Grover, who has escaped from the island on his own.", "They run into Luke, who tries to make peace with them."],
    ["Clarisse is thrilled and immediately asks Percy to take over leading the quest.", "Clarisse doesn't recognize Percy at first and treats him like a stranger."],
    ["Clarisse's weapons turn out to be duds that don't work at all in battle.", "Clarisse accidentally sets off a trap that summons an army of skeletons."],
    ["Their ship is repaired instantly by a passing group of friendly nymphs.", "Their ship is confiscated by the Coast Guard for questioning."],
    ["Percy and Clarisse become instant best friends after the explosion.", "Percy and Clarisse decide to abandon their quests entirely and go home."],
  ],
  "pj-02-ch-12": [
    ["They discover an abandoned military base hidden inside a volcano.", "They discover a small fishing village that welcomes shipwrecked sailors."],
    ["Annabeth is turned away completely because the resort only accepts boys.", "Annabeth is locked in a room while only Percy receives spa treatments."],
    ["Percy discovers the resort is actually a hidden training camp for young monsters.", "Percy discovers the staff are all ghosts pretending to be alive."],
    ["The resort is run by a retired Olympian god looking for peace and quiet.", "The resort is run by Clarisse's mother, who is secretly a witch."],
    ["Percy begins to suspect the whole island is just an elaborate dream he's having.", "Percy begins to suspect that Clarisse secretly owns and runs the resort."],
  ],
  "pj-02-ch-13": [
    ["Percy is saved when Grover suddenly appears and breaks the spell with his pipes.", "Percy is saved because guinea pigs are immune to salt water, so a wave washes the curse away."],
    ["Annabeth is upset because Percy accidentally left her favorite dagger behind on the island.", "Annabeth is upset because Tyson accidentally broke one of her books."],
    ["Annabeth tries to fly home using Percy's magical winged shoes without asking.", "Annabeth tries to summon her mother, Athena, to take her home immediately."],
    ["Percy lets her go, deciding it's her choice to make alone.", "Percy calls Chiron to come pick Annabeth up and send her home."],
    ["It reveals that Annabeth secretly wants to quit being a demigod forever.", "It reveals that Annabeth has been working against Percy the whole time."],
  ],
  "pj-02-ch-14": [
    ["They find the island guarded by a three-headed dog chained to a golden gate.", "They find the island empty, with the Fleece completely unguarded."],
    ["The ranch is run by Ares, who is testing heroes who try to reach the Fleece.", "The ranch is run by Circe's twin sister, using the same magic as the spa island."],
    ["They spot Luke, disguised as one of the ranch hands working for Polyphemus.", "They spot Clarisse, who arrived on the island before them."],
    ["Polyphemus captured Grover after catching him trying to steal sheep.", "Polyphemus thinks Grover is a spy sent by the other Olympian gods."],
    ["They realize the Fleece isn't actually on this island at all and they must leave.", "They realize Polyphemus already knows exactly who they are and is expecting them."],
  ],
  "pj-02-ch-15": [
    ["Their plan is to challenge Polyphemus to a fair wrestling match for the Fleece.", "Their plan is to trade one of Clarisse's weapons for the Fleece peacefully."],
    ["Polyphemus simply lets them go without any trouble at all.", "Polyphemus turns out to be secretly on their side and helps them escape."],
    ["Their boat gets caught in a sudden, freezing blizzard out of nowhere.", "Their boat is attacked by a school of enormous sharks."],
    ["Tyson safely swims to shore with the Fleece held tightly above his head.", "Tyson throws the Fleece to Annabeth just before calmly climbing aboard the boat himself."],
    ["The chapter ends with a joyful celebration back at camp with the Fleece in hand.", "The chapter ends with Polyphemus giving up and inviting them all to stay for dinner."],
  ],
  "pj-02-ch-16": [
    ["Percy sends Annabeth alone to search while he stays safely on the boat.", "Percy prays to Zeus for a lightning bolt to part the whirlpool."],
    ["The Princess Andromeda docks safely at Camp Half-Blood's private harbor.", "The Princess Andromeda is repaired by Luke's crew and sails away unharmed."],
    ["A pod of friendly killer whales agrees to help after Percy speaks to them in Greek.", "Chiron dives into the water in full centaur form to help search."],
    ["Percy discovers that Grover was the one who actually rescued Tyson earlier.", "Percy discovers that the Fleece was destroyed, but Tyson survived unharmed."],
    ["It resolves the cliffhanger by revealing that Tyson decided to stay behind in the ocean forever.", "It resolves the cliffhanger by showing that the Fleece was actually a fake all along."],
  ],
  "pj-02-ch-17": [
    ["They wash up on the shores of Camp Half-Blood itself.", "They wash up on a deserted island far from any city."],
    ["They run into Luke, who has decided to surrender and join their side.", "They run into Percy's mom, Sally, who came looking for him herself."],
    ["Percy decides to keep the Fleece for himself so he gets all the credit.", "Percy decides to destroy the Fleece rather than let anyone take credit."],
    ["Clarisse immediately bursts into tears of joy and hugs everyone.", "Clarisse pretends not to recognize any of them at all."],
    ["They decide to take a relaxing vacation on the beach before heading back.", "They decide to abandon the Fleece and start an entirely new quest."],
  ],
  "pj-02-ch-18": [
    ["The Party Ponies are actual ponies from a circus that escaped nearby.", "The Party Ponies are a group of satyrs disguised as party clowns."],
    ["They need the Party Ponies to help them defeat Polyphemus once and for all.", "They need the Party Ponies to translate an ancient prophecy for them."],
    ["The Party Ponies each carry one hero on their backs, galloping the whole way.", "The Party Ponies summon a magical portal that teleports everyone instantly."],
    ["The Party Ponies bring a somber, serious tone, warning everyone of doom.", "The Party Ponies bring strict military discipline to the rescue mission."],
    ["They're racing to catch a flight before airport security closes for the night.", "They're racing back to the spa island to rescue more trapped guests."],
  ],
  "pj-02-ch-19": [
    ["Camp Half-Blood is peacefully hosting its annual summer festival.", "Camp Half-Blood has already been evacuated with no one left to fight."],
    ["A rival summer camp attacks in a prank war that gets out of hand.", "Mr. D leads an attack after being possessed by an angry spirit."],
    ["Clarisse refuses to fight at all, still upset about her earlier quest troubles.", "Clarisse accidentally fights on the wrong side during the confusion."],
    ["A firework display planned for the chariot race accidentally goes off.", "Mr. D casts a spell that causes fireworks to shoot from his fingers for fun."],
    ["Only the outcome of a friendly sports competition is at stake.", "Only Clarisse's personal reputation is at stake during the attack."],
  ],
  "pj-02-ch-20": [
    ["They decide to keep the Fleece locked away in the Big House instead of using it.", "They give the Fleece to Mr. D to wear as a decoration."],
    ["The tree begins to shrink until it disappears completely.", "The tree catches fire briefly before finally healing."],
    ["The Fleece's magic accidentally turns the whole forest into gold.", "The Fleece's magic causes every tree at camp to come alive and start talking."],
    ["Camp Half-Blood decides to close down permanently despite being saved.", "Camp Half-Blood blames Percy and his friends for everything that went wrong."],
    ["Tyson decides camp isn't for him and chooses to leave for good.", "Tyson is sent away by Chiron despite everything he did to help."],
  ],
  "pj-03-ch-01": [
    ["They went to rescue Annabeth, who had been kidnapped from the school earlier that week.", "They went because Chiron ordered them to spy on a new camp for young monsters being built nearby."],
    ["They are two satyrs training alongside Grover to search for new demigods.", "They are teachers at Westover Hall who secretly work for Camp Half-Blood."],
    ["They forged transfer papers on Annabeth's laptop the night before.", "Chiron called ahead and enrolled them officially as exchange students."],
    ["Dr. Thorn kept insisting he had met Percy's mother somewhere before.", "Dr. Thorn was secretly wearing a Camp Half-Blood necklace under his suit."],
    ["Grover told them Pan had finally been found hiding in the school basement.", "Grover told them Annabeth's father worked as a teacher at the school."],
  ],
  "pj-03-ch-02": [
    ["Dr. Thorn turns out to be a minor Titan in disguise, testing the young heroes.", "Dr. Thorn turns out to be a cyclops working secretly for Luke."],
    ["A squad of satyrs led by Grover's uncle bursts in to help.", "Chiron gallops in on his horse half to join the fight personally."],
    ["Annabeth is captured and locked inside the school by Dr. Thorn's assistants.", "Annabeth chases the manticore into the woods and gets lost overnight."],
    ["The manticore breathes a cloud of poisonous gas to knock everyone out.", "The manticore summons a pack of skeleton warriors to fight alongside it."],
    ["They feel triumphant because they captured Dr. Thorn and can question him.", "They feel relieved because Grover confirms he saw Annabeth escape safely."],
  ],
  "pj-03-ch-03": [
    ["Percy's father Poseidon rises out of a nearby lake to explain everything.", "Dr. Thorn's twin brother arrives to confess what really happened."],
    ["Bianca has to decide whether to return to Westover Hall or move to Camp Half-Blood.", "Bianca has to decide whether to tell Nico that their father is a Greek god."],
    ["Bianca decides to stay with Nico and refuses to join the Hunters.", "Bianca decides to go home to her family instead of joining any group."],
    ["Nico is thrilled and immediately asks to join the Hunters too.", "Nico runs away from the group in anger and disappears into the woods."],
    ["Percy feels confident that everything is under control and no longer worries about Annabeth.", "Percy feels angry at Bianca for choosing to join the Hunters over her brother."],
  ],
  "pj-03-ch-04": [
    ["Chiron sends a flying chariot pulled by pegasi to pick them up.", "They call Percy's mom, who drives for hours to come get them."],
    ["Thalia doesn't have her license yet, so she isn't legally allowed to drive.", "Thalia is afraid of water and refuses to drive near the coast."],
    ["She accidentally drives them into the ocean and they have to swim to shore.", "She gets them lost for days trying to find the right highway."],
    ["They run out of fuel in the middle of a forest, far from camp.", "Police officers pull them over and end the ride early."],
    ["Thalia feels bored and unimpressed by the whole trip.", "Thalia feels excited and asks to drive again right away."],
  ],
  "pj-03-ch-05": [
    ["Percy uses a special phone Chiron gives him to text the gods directly.", "Percy borrows Apollo's chariot to fly down to the ocean floor."],
    ["Percy speaks directly with Zeus about the missing goddess Artemis.", "Percy talks with Dr. Thorn, who tries to trick him with false information."],
    ["He learns that Poseidon has decided to leave Olympus completely.", "He learns that the ocean's monsters have joined forces with Artemis."],
    ["He hears that Bianca has changed her mind and left the Hunters already.", "He hears that Dr. Thorn has been captured and imprisoned by the gods."],
    ["Percy feels completely calm, believing all of his problems are now solved.", "Percy feels ready to give up the search for Annabeth entirely."],
  ],
  "pj-03-ch-06": [
    ["Percy finds a letter Annabeth wrote saying she planned to run away from camp.", "Percy finds Annabeth's dagger buried near the cabins."],
    ["Dr. Thorn crashes the game, still disguised as a teacher.", "Grover shows up riding the Erymanthian Boar in the middle of the field."],
    ["The Oracle delivers a letter from Poseidon addressed to Percy.", "The Oracle delivers a warning that Camp Half-Blood is about to be destroyed."],
    ["They laugh it off, assuming someone is playing a prank in a costume.", "They cheer, thinking it means the quest is already finished successfully."],
    ["Because Percy officially becomes the camp's new activities director.", "Because Percy learns for certain that Annabeth has already been found safe."],
  ],
  "pj-03-ch-07": [
    ["Because Chiron bans him from camp activities for a week.", "Because the other campers vote him out of his cabin."],
    ["Percy dreams that Bianca has secretly betrayed the Hunters.", "Percy dreams that his mother has gone missing along with Annabeth."],
    ["Tyson shows up in person to help Percy sneak onto the quest.", "Dr. Thorn's shadow appears at the edge of camp, spying on Percy."],
    ["He feels relieved, since he was hoping for a break from questing.", "He feels proud that Zoe finally trusts him completely."],
    ["The General is revealed in the dream to be Dr. Thorn's older brother.", "The General is shown clearly to be the Titan lord Kronos himself."],
  ],
  "pj-03-ch-08": [
    ["They fly off together to spy on Dr. Thorn's hideout.", "They race across camp to warn Chiron about an attack."],
    ["Nico asks Percy to promise never to tell anyone about their father.", "Nico asks Percy to promise to bring him along on the quest too."],
    ["He disguises himself as one of the Hunters to sneak onto the team.", "He convinces Chiron to order Zoe to add him to the group."],
    ["Bessie is a baby sea dragon that belongs to Poseidon's palace.", "Bessie is a disguised Hunter who got turned into an animal by a curse."],
    ["Because keeping the promise means Percy has to break a sacred camp rule.", "Because the promise requires Percy to give up his own godly parent's protection."],
  ],
  "pj-03-ch-09": [
    ["He hides inside one of the Hunters' supply crates on their van.", "He disguises his voice using a magic item borrowed from Annabeth."],
    ["He watches Luke building a fake Camp Half-Blood to trick new demigods.", "He watches the General freeing Kronos from the underworld."],
    ["He convinces the skeleton warriors that he's on their side.", "He transforms into water and slips away through a drainpipe."],
    ["Percy grabs one of the dragon's teeth as proof of what he saw.", "Percy grabs a map showing the location of Mount Olympus."],
    ["He decides to keep what he saw a secret from everyone, including Thalia.", "He goes straight back to camp instead of warning the quest group."],
  ],
  "pj-03-ch-10": [
    ["Percy finds them hiding inside a cave near Camp Half-Blood.", "Percy finds them already fighting Dr. Thorn on a rooftop."],
    ["A giant scorpion made of bronze attacks from inside a display case.", "A pack of skeleton warriors ambushes them right in the museum halls."],
    ["They trap the lion inside a rocket ship display and launch it away.", "They discover a hidden weak spot behind the lion's ear."],
    ["Zoe gives Percy her personal silver hunting bow as a reward.", "Zoe gives Percy a map showing exactly where Annabeth is being held."],
    ["Percy is named the new leader of the quest, replacing Zoe.", "Percy is sent back to camp as punishment for following the group."],
  ],
  "pj-03-ch-11": [
    ["A giant eagle sent by Zeus tracks their every move.", "Dr. Thorn himself pilots a small plane right above them."],
    ["They borrow Professor Chase's private plane to fly west.", "They ride on the back of the Erymanthian Boar the whole way."],
    ["They meet Hades disguised as a train conductor.", "They meet Annabeth's father, who happens to be riding the same train."],
    ["He tells them Annabeth is being held at the bottom of a lake.", "He tells them Bianca secretly still wants to leave the Hunters."],
    ["They feel completely safe, certain nothing can catch up to a moving train.", "They feel ready to give up the quest and head back to camp early."],
  ],
  "pj-03-ch-12": [
    ["An avalanche nearly buries the whole group in snow.", "Dr. Thorn ambushes them disguised as a ski instructor."],
    ["A massive griffin swoops down to help fight the skeletons.", "The Nemean Lion returns for a rematch against Zoe."],
    ["Grover tames the boar by feeding it enchanted acorns from camp.", "Grover uses a rope lasso to force the boar to carry them."],
    ["Grover realizes the boar was actually sent by Dr. Thorn as a trap.", "Grover realizes the boar escaped from a nearby traveling circus."],
    ["It's a calm, quiet ride since the boar moves slowly and carefully.", "It's a sad moment because the boar gets hurt and can't continue."],
  ],
  "pj-03-ch-13": [
    ["The boar brings them straight to the gates of Mount Olympus.", "The boar brings them to a hidden Hunters of Artemis campsite."],
    ["Bianca takes a golden apple meant for the Hunters' garden.", "Bianca takes a silver arrow that once belonged to Zoe."],
    ["A sleeping Titan buried under the scrap metal wakes up.", "An army of skeleton warriors bursts out from beneath the junk piles."],
    ["Bianca climbs onto Talos's shoulder and tries to pull out its wiring.", "Bianca lures Talos toward the boar so it gets crushed instead."],
    ["Bianca is captured by Talos and carried away, still alive but missing.", "Bianca manages to escape at the last second, badly hurt but safe."],
  ],
  "pj-03-ch-14": [
    ["They hitch a ride on a passing freight train once again.", "They fly the rest of the way using Blackjack and other pegasi."],
    ["They meet a mortal tour guide who turns out to be Apollo again.", "They meet another demigod who has been secretly living at the dam."],
    ["Dr. Thorn ambushes them disguised as a cafeteria worker.", "The Nemean Lion's ghost appears and traps them inside."],
    ["Rachel Elizabeth Dare distracts the guards so they can slip away.", "Grover charms the skeleton warriors into falling asleep with his pipes."],
    ["Zoe reveals that Percy's sword was actually a gift from Luke.", "Zoe reveals that the sword once belonged to Dr. Thorn before he became a monster."],
  ],
  "pj-03-ch-15": [
    ["The statues drop them off right at the base of Mount Tamalpais.", "The statues drop them off at Professor Chase's front door."],
    ["Percy has to wrestle Luke to get information about Annabeth.", "Percy has to wrestle a giant sea serpent guarding the harbor."],
    ["Nereus reveals that Annabeth is being kept prisoner nearby in San Francisco.", "Nereus reveals that Zoe secretly wants to quit the Hunters."],
    ["Luke shows up alone, offering to switch sides and help them.", "The Nemean Lion's mate arrives seeking revenge."],
    ["Percy tricks Nereus by offering him a trade of golden treasure.", "Percy convinces Nereus using a message sent from Poseidon."],
  ],
  "pj-03-ch-16": [
    ["Grover decides to stay behind and guard Professor Chase's house.", "Grover heads off to search for Pan on his own instead."],
    ["They visit Luke's father, hoping he can talk his son out of fighting them.", "They visit Dr. Thorn's old teaching colleague for information."],
    ["A giant scorpion the size of a house guards the garden entrance.", "A pack of skeleton warriors stands watch at the garden gates."],
    ["Zoe reveals that the General is secretly her long-lost brother.", "Zoe reveals that the General is actually Luke's father in disguise."],
    ["Zoe uses a magic flute to lull the dragon to sleep.", "Zoe offers the dragon a golden apple as a bribe to let them pass."],
  ],
  "pj-03-ch-17": [
    ["They find Artemis chained up inside a cave, unable to move at all.", "They find Artemis has already escaped and left the mountain."],
    ["Chiron is found captive there, having been kidnapped days earlier.", "Nico is discovered there, having secretly followed the group."],
    ["Luke tries to convince Thalia to free Atlas from his Titan prison.", "Luke tries to convince Thalia to abandon Percy on the mountain."],
    ["Percy tricks Atlas into a wrestling match to distract him completely.", "Percy uses Riptide to cut through the chains holding Artemis in place."],
    ["Artemis defeats Atlas by calling down lightning from her father, Zeus.", "Artemis defeats Atlas by trapping him inside the dragon Ladon's lair."],
  ],
  "pj-03-ch-18": [
    ["Zoe refuses all healing because she believes it's against the Hunters' code.", "Zoe hides her injuries at first, so nobody realizes how badly hurt she is."],
    ["Thalia and Zoe argue one final time about who is to blame for the battle.", "Zoe asks Thalia to take her place as leader of the Titans instead."],
    ["Zoe confesses that she always secretly worked for Atlas.", "Zoe confesses that she knew all along that Bianca wouldn't survive."],
    ["Artemis brings Zoe back to life using a hidden immortality potion.", "Artemis names a new Hunter cabin at camp after Zoe."],
    ["They feel triumphant and mostly forget about Zoe quickly, eager to celebrate.", "They feel angry at Artemis for not saving Zoe sooner."],
  ],
  "pj-03-ch-19": [
    ["They suggest banning Percy from ever visiting Camp Half-Blood again.", "They suggest taking away Percy's ability to control water."],
    ["The gods punish Percy by turning him into a minor forest spirit for a year.", "The gods decide to erase Percy's memory of the entire quest."],
    ["The gods decide the Ophiotaurus must be sacrificed immediately for safety.", "The gods decide to release the Ophiotaurus back into the wild ocean."],
    ["Thalia decides to become a full Olympian goddess herself.", "Thalia decides to leave the group entirely and live as a mortal."],
    ["It means the prophecy is now completely canceled and will never happen.", "It means Nico instead becomes the one the prophecy is definitely about."],
  ],
  "pj-03-ch-20": [
    ["Percy has to tell Nico that Bianca decided to stay with the Hunters forever.", "Percy has to tell Nico that their father wants nothing to do with him."],
    ["Nico calmly accepts the news and thanks Percy for trying his best.", "Nico refuses to believe it and runs off to search for Bianca himself."],
    ["Nico summons a wave of water strong enough to wash the warriors away.", "Nico calls down a bolt of lightning to destroy the warriors instantly."],
    ["Percy figures out that Nico is secretly one of the Hunters in disguise.", "Percy figures out that Nico has been working with Luke all along."],
    ["Grover announces that he has found a whole new herd of satyrs to join camp.", "Grover announces that Dr. Thorn has been spotted again nearby."],
  ],
  "pj-04-ch-01": [
    ["At a summer camp reunion picnic near the lake", "On a school bus heading to a museum field trip"],
    ["She reveals that she's secretly a daughter of a minor god", "She says she can talk to animals the way Grover can"],
    ["The school principal and the gym coach turn out to be disguised monsters", "Two of Percy's classmates turn out to be secret half-bloods working for Luke"],
    ["Percy defeats both monsters and captures them for questioning", "Tammi runs away and is never seen again in this chapter"],
    ["Kelli tells Percy exactly when and how Luke's army will attack the camp", "Kelli warns Percy that Grover has already been captured"],
  ],
  "pj-04-ch-02": [
    ["Percy meets a new camp director named Quintus who owns a fire-breathing horse", "Percy meets Clarisse's cousin, who brought along a pack of wild wolves"],
    ["The Council tells Grover he has already lost his license and can never search again", "The Council promotes Grover to Lord of the Wild immediately"],
    ["Percy reunites with his father, Poseidon, who is visiting camp", "Percy reunites with Nico di Angelo, who has come back to camp"],
    ["Percy gets a message from his mother warning him to come home immediately", "Percy gets a message from Annabeth saying she has found Daedalus"],
    ["Because the ghost directly says it plans to attack camp that same night", "Because the ghost tells Percy that Grover is in immediate danger"],
  ],
  "pj-04-ch-03": [
    ["A pack of hellhounds breaks through the camp's magical barrier", "Kronos's army launches its first real invasion of camp"],
    ["They've been secretly training a group of new campers for battle", "They've been searching the ocean for a way to reach Daedalus"],
    ["They want a hidden stash of ambrosia and nectar", "They want to free Kronos's original body, which they believe is buried in the maze"],
    ["They are ambushed by a group of Luke's demigods", "They fall into a pit trap set up during the evening war game"],
    ["They discover an old, empty demigod grave", "They discover a stash of weapons left behind by Luke's spies"],
  ],
  "pj-04-ch-04": [
    ["Percy dreams about Luke's army marching toward camp", "Percy dreams about Quintus fighting Kronos in an arena"],
    ["Chiron confirms that Daedalus died centuries ago and cannot be found", "Chiron announces that Pan has already been found"],
    ["Annabeth proposes a quest to rescue Nico from the Underworld", "Annabeth receives a prophecy that names Quintus as a traitor"],
    ["She decides to go on the quest completely alone, against Chiron's orders", "She invites a mortal guide before anyone else has even agreed to it"],
    ["Juniper tells Percy that Quintus secretly talked to Luke on the phone", "Juniper says she saw Quintus disappear into thin air"],
  ],
  "pj-04-ch-05": [
    ["Percy dreams that Kronos has already fully risen and defeated the gods", "Percy dreams that Luke has decided to betray Kronos"],
    ["It shows Annabeth already inside the Labyrinth searching without them", "It shows Grover finding Pan in a forest"],
    ["Nico summons the ghost of King Minos", "Nico summons the ghost of his sister, Bianca"],
    ["Theseus warns Nico that Percy cannot be trusted at all", "Theseus warns Nico that the Labyrinth has already collapsed"],
    ["The vision ends peacefully when Nico says goodnight", "Kronos appears in the fountain and speaks directly to Percy"],
  ],
  "pj-04-ch-06": [
    ["They find a modern gymnasium full of training dummies", "They find Daedalus's actual workshop full of blueprints"],
    ["They find the skeleton of a fallen demigod hero", "They find a cage holding a sleeping monster"],
    ["They meet Hermes, who asks Annabeth to deliver a hidden message", "They meet Morpheus, who tries to trap them all in a dream"],
    ["Chiron appears through a message to guide them", "Grover's satyr friends arrive to rescue them"],
    ["She tells them exactly where Daedalus's workshop is located", "She warns them that Quintus cannot be trusted"],
  ],
  "pj-04-ch-07": [
    ["They find themselves inside an ancient Greek dungeon", "They find themselves back at Camp Half-Blood's brig"],
    ["They find Tyson's long-lost Cyclops father", "They find Ethan Nakamura, chained up by Luke's forces"],
    ["Kampê is a former camp counselor who betrayed Chiron", "Kampê is Geryon's pet monster that guards his ranch"],
    ["Percy threatens Briares with his sword until he agrees to move", "Annabeth uses her invisibility cap to trick Briares into following her"],
    ["Grover charms Kampê to sleep with his reed pipes", "Briares scares Kampê away using his hundred hands"],
  ],
  "pj-04-ch-08": [
    ["Briares confesses that he secretly works for Luke", "Briares admits he doesn't trust Tyson"],
    ["They find one of Nico's black robes hanging on a rock", "They find a note written in ancient Greek addressed to Percy"],
    ["They emerge into the middle of Times Square in New York City", "They emerge onto a beach where Calypso lives"],
    ["Geryon is a three-headed dog who guards the ranch entrance", "Geryon is a former camp counselor who now works for Luke"],
    ["Percy agrees to fight Geryon's prize monster in exchange for their freedom", "Percy agrees to give Geryon his sword, Riptide, in trade for Nico"],
  ],
  "pj-04-ch-09": [
    ["Percy recalls that Theseus once cleaned a maze full of monsters", "Percy recalls that Jason once tamed fire-breathing bulls"],
    ["The naiad happily floods the stables herself", "The naiad refuses to speak to Percy at all and disappears"],
    ["Percy uses Riptide to dig a giant trench that drains the mess into the sea", "Percy convinces the monstrous horses to clean up after themselves"],
    ["Geryon happily lets everyone go as promised", "Geryon offers Percy a job managing the ranch"],
    ["Percy drowns Geryon using a giant wave", "Percy tricks Geryon into falling into his own manure pit"],
  ],
  "pj-04-ch-10": [
    ["Nico casts a spell that accidentally summons Kronos", "Nico's ritual accidentally wakes up Geryon's ghost"],
    ["Minos warns Nico that Pan has already died", "Minos warns Nico that Quintus is secretly a god"],
    ["Bianca tells Nico exactly how to bring her back to life", "Bianca warns Nico that Annabeth cannot be trusted"],
    ["Nico decides to join the quest group for the rest of the journey", "Grover announces he has already found Pan"],
    ["A talking eagle leads them straight to Daedalus's workshop", "They find a magic map that shows the entire Labyrinth at once"],
  ],
  "pj-04-ch-11": [
    ["They meet Daedalus himself, working at his true forge", "They meet Ares, guarding his personal armory"],
    ["He wants Percy to give up Riptide", "He wants them to defeat Kronos before he'll help"],
    ["Rachel and Nico head off to find Daedalus alone", "Chiron and Clarisse head back to camp for reinforcements"],
    ["They discover a group of runaway satyrs", "They discover Luke himself, working the forge in secret"],
    ["Annabeth pulls him out using a rope at the last second", "Hephaestus rescues Percy personally"],
  ],
  "pj-04-ch-12": [
    ["He wakes up back at Camp Half-Blood in the infirmary", "He wakes up in Hephaestus's workshop"],
    ["She's stuck there because she made a bad deal with Kronos", "She's stuck there because she lost a bet with Hermes"],
    ["He must choose between fighting a monster or fleeing the island", "He must choose whether to trust Calypso or turn her in to the gods"],
    ["Percy decides to stay on the island forever", "Percy escapes the island by swimming all the way back to camp"],
    ["She asks him to send her a letter every week", "She asks him to bring her back a gift from Camp Half-Blood"],
  ],
  "pj-04-ch-13": [
    ["Camp is celebrating the end of the war against Kronos", "Camp is holding a going-away party for Quintus"],
    ["He learns Quintus was captured by Luke's forces", "He learns Quintus has been promoted to run the whole camp"],
    ["Grover and Tyson have already returned safely to camp", "Grover has officially been given the title Lord of the Wild"],
    ["They disagree about whether to abandon the quest completely", "They disagree about whether Quintus can be trusted"],
    ["Percy recruits Clarisse, since she has already scouted parts of the maze", "Percy recruits Nico, since he can sense the dead"],
  ],
  "pj-04-ch-14": [
    ["Geryon's soldiers capture them and drag them back to the ranch", "Kampê and her monster army capture them"],
    ["Antaeus is actually Tyson's long-lost twin", "Antaeus was once a camper at Camp Half-Blood alongside Percy"],
    ["Percy takes Ethan prisoner and hands him over to Luke", "Percy lets Ethan go free but refuses to speak to him"],
    ["Percy drowns Antaeus using a wave of water", "Percy tricks Antaeus into fighting Ethan instead"],
    ["Rachel uses her mortal connections to call in help", "Annabeth uses her invisibility cap to sneak everyone out unnoticed"],
  ],
  "pj-04-ch-15": [
    ["It forces them into Hephaestus's forge again", "It forces them back to Geryon's ranch"],
    ["Quintus reveals that he has secretly been working for Kronos the whole time", "Quintus reveals that he is actually Percy's long-lost uncle"],
    ["He admits he sold Nico to Kronos's forces", "He admits he destroyed the entrance to the Labyrinth"],
    ["Grover arrives in chains, having just been captured by satyrs loyal to Kronos", "Rachel arrives in chains after being kidnapped by Kelli"],
    ["The group defeats all the monsters and calmly walks out the front door", "The group is trapped inside the workshop as it collapses"],
  ],
  "pj-04-ch-16": [
    ["They land in the ocean near Ogygia", "They crash into Camp Half-Blood's strawberry fields"],
    ["She uses her artistic talent to draw a map of the tunnels from memory", "She calls her father, who sends a helicopter to find the entrance"],
    ["He finds a room full of ancient scrolls about the Labyrinth", "He finds Daedalus's real, mortal body sleeping peacefully"],
    ["Inside is an empty coffin with nothing but dust", "Inside is Kronos's full, golden body already reassembled"],
    ["They scream that their master has been murdered", "They immediately attack Percy without saying a word"],
  ],
  "pj-04-ch-17": [
    ["Grover has been searching for his missing father", "Grover has been searching for a way to defeat Kronos"],
    ["They find Pan strong and ready to fight in the war", "They find Pan trapped in a cage by Luke's forces"],
    ["Pan tells Grover the exact location of Daedalus's workshop", "Pan tells Grover that Kronos cannot be defeated"],
    ["Pan transforms into a mortal and joins the group's quest", "Pan is captured and taken away by monsters"],
    ["Grover feels relieved that his search is finally over and goes back to normal life", "Grover feels angry at Percy for not helping him search sooner"],
  ],
  "pj-04-ch-18": [
    ["They emerge inside Camp Half-Blood's dining pavilion", "They emerge in Central Park, where Chiron is waiting with an army"],
    ["Grover tells Silenus that he's quitting as a satyr entirely", "Grover tells Silenus that Pan has been found alive and well"],
    ["Juniper's tree is chopped down by enemy soldiers", "Juniper's tree grows so large it blocks the Labyrinth entrance"],
    ["They successfully break through camp's defenses", "They surrender peacefully and are taken prisoner"],
    ["Percy says goodbye to Tyson, who returns to the ocean permanently", "Percy says goodbye to Nico, who leaves camp for good"],
  ],
  "pj-04-ch-19": [
    ["They immediately celebrate Grover as a hero", "They ask Grover to lead a new search party right away"],
    ["Poseidon returns, grieving over Percy's near-death experience", "Chiron returns from a long trip, upset about losing the war council vote"],
    ["Dionysus votes in favor of exiling Grover immediately", "Dionysus refuses to get involved and leaves the trial"],
    ["Grover is formally exiled and stripped of his searcher's license", "Grover is declared the new Lord of the Wild by unanimous vote"],
    ["He decides to give up being a satyr and live as a regular teenager", "He starts training to become a full-time camp sword instructor"],
  ],
  "pj-04-ch-20": [
    ["Hermes arrives to warn Percy about a message from Luke", "Athena arrives to warn Percy about Annabeth's safety"],
    ["He realizes the body actually belonged to Ethan Nakamura all along", "He realizes the sarcophagus was completely empty the whole time"],
    ["Daedalus chooses to flee into hiding forever", "Daedalus chooses to join Luke's army instead"],
    ["He spends the entire evening training for the next battle", "He spends the evening writing letters to Camp Half-Blood"],
    ["He throws the necklace away, feeling done with camp forever", "He gives the necklace to Tyson as a keepsake"],
  ],
  "pj-05-ch-01": [
    ["It was Grover Underwood coming to invite Percy to a satyr meeting.", "It was Nico di Angelo bringing news about the Underworld."],
    ["They were trying to rescue campers being held prisoner belowdecks.", "They were sent to steal Kronos's scythe while everyone slept."],
    ["He froze the fountain water solid and shattered the crab's shell.", "He tricked the crab into snapping at its own reflection in a mirror."],
    ["Percy managed to knock Kronos's helmet off before more monsters arrived.", "Kronos refused to fight and ordered the giants to attack instead."],
    ["He convinced them he was actually a kitchen worker delivering snacks.", "He hid the real bombs inside a fake wooden crate labeled \"Toys.\""],
  ],
  "pj-05-ch-02": [
    ["He woke up in the Big House infirmary at Camp Half-Blood.", "He woke up on Blackjack's back, flying back to camp."],
    ["Beckendorf had been captured and was being held prisoner by Kronos.", "Beckendorf had washed ashore safely on Long Island."],
    ["Poseidon had disguised himself as an old man so enemy spies wouldn't recognize him.", "A curse from Amphitrite had temporarily transformed his appearance."],
    ["Triton is Poseidon's loyal dolphin messenger who happily welcomed Percy.", "Triton is an enemy Titan who had infiltrated the palace in disguise."],
    ["Poseidon asked Percy to find Triton and convince him to retreat.", "Poseidon asked Percy to bring Tyson back to camp with him."],
  ],
  "pj-05-ch-03": [
    ["Everyone cheered wildly, thinking the mission was a total success.", "Chiron immediately banned Percy from going on future missions."],
    ["They were arguing about who should lead the next mission to find Kronos.", "They were arguing over whose cabin had the best decorations for the summer."],
    ["They showed him a hidden map that revealed where Kronos's ship was hiding.", "They introduced him to a brand-new camper who had just arrived."],
    ["The line about \"endless sleep\" made him worry the whole camp would be put under a spell forever.", "The line about \"eldest gods\" made him think his father was going to disappear."],
    ["They saw Kronos's army building a second cruise ship to replace the destroyed one.", "They saw the Empire State Building already collapsing in ruins."],
  ],
  "pj-05-ch-04": [
    ["She painted a peaceful beach scene of their upcoming vacation to St. Thomas.", "She painted a portrait of Chiron guarding Camp Half-Blood."],
    ["They discovered a secret tunnel underneath the Poseidon cabin.", "They found out the Ares cabin had been secretly recruiting new campers."],
    ["They argued about who should be named the new camp leader.", "They argued over how to punish the Stoll brothers for a prank."],
    ["They burned old camp banners to make room for new ones.", "They burned a model of the Princess Andromeda to celebrate its destruction."],
    ["She said her cabin was too injured from a recent battle to help.", "She demanded that Percy apologize for something he'd said the summer before."],
  ],
  "pj-05-ch-05": [
    ["He found Clarisse crying about the argument over the chariot.", "He found Annabeth searching for a lost map of the Labyrinth."],
    ["Nico said Beckendorf's ghost was angry and wanted revenge on Kronos.", "Nico said he couldn't find any trace of Beckendorf's spirit at all."],
    ["Nico revealed he had found Kronos's hidden throne room.", "Nico revealed that Chiron was secretly working with the enemy."],
    ["Percy decided to give up fighting and take Rachel's vacation offer instead.", "Percy decided to challenge Clarisse to a duel to force her cabin back into the war."],
    ["They flew there on Blackjack the pegasus.", "They borrowed Paul's car and drove there themselves."],
  ],
  "pj-05-ch-06": [
    ["The house was actually abandoned and completely empty inside.", "The house was filled with weapons she had collected to fight monsters herself."],
    ["She said Luke asked her for money to buy a new sword.", "She said Luke brought her a gift from Camp Half-Blood as an apology."],
    ["She suddenly remembered exactly where Luke was hiding and gave them directions.", "She fainted from exhaustion after baking too many cookies."],
    ["Hestia was a camp counselor who scolded them for running off without permission.", "Hestia was Annabeth's mother in disguise, checking up on Percy."],
    ["Sally forbade Percy from doing anything dangerous and grounded him.", "Sally insisted on coming along to protect Percy herself."],
  ],
  "pj-05-ch-07": [
    ["They found Grover awake and camping out, hiding from monsters on purpose.", "They found Grover had turned into a full satyr elder and could no longer speak."],
    ["They took Charon's ferry from Los Angeles like Percy had before.", "Mrs. O'Leary dug a tunnel straight down through the ground."],
    ["Nico had agreed to steal Percy's sword and give it to Hades.", "Nico had promised to convince Percy to fight for the Underworld army instead of the gods."],
    ["Hades revealed that Nico and Bianca were actually adopted, not his real children.", "Hades revealed that their mother was still alive somewhere in the mortal world."],
    ["Hades challenged Percy to a duel to test his strength.", "Hades sent Percy back to camp with a stern warning."],
  ],
  "pj-05-ch-08": [
    ["Achilles warned Percy never to use Riptide again after entering the river.", "Achilles warned that only campers born after a certain year could survive the ritual."],
    ["He chose his left shoulder, and he thought of his mother's voice to survive.", "He chose the back of his neck, and he thought of Grover's music to survive."],
    ["Percy immediately collapsed and had to be carried out by Mrs. O'Leary.", "Kronos himself appeared to finish Percy off before he could recover."],
    ["Percy and Hades shook hands and agreed to team up against Kronos.", "Hades apologized and released Percy from his earlier punishment."],
    ["Percy told Nico to stay hidden in the Underworld until the war was over.", "Percy told Nico to warn Chiron that Hades could not be trusted at all."],
  ],
  "pj-05-ch-09": [
    ["Chiron was too injured from a recent battle to travel with them.", "Chiron secretly didn't trust the campers and stayed behind to guard camp instead."],
    ["Ares greeted them and offered to lead the defense himself.", "Nobody came at all, and the campers were left completely alone in the throne room."],
    ["Hermes was angry that Annabeth had lost his favorite winged sandals.", "Hermes accused Annabeth of stealing his caduceus staff."],
    ["Hestia showed him a vision of Beckendorf still alive and hiding somewhere.", "Hestia showed him exactly where Kronos's army was hiding in New Jersey."],
    ["They discovered the whole city had been evacuated by the police.", "They discovered the Empire State Building itself was crumbling apart."],
  ],
  "pj-05-ch-10": [
    ["She used a magic mirror that Athena had given her that morning.", "She used binoculars borrowed from a nearby camera shop."],
    ["He kept every camper together in one big group at the Empire State Building.", "He sent all the campers home to protect Camp Half-Blood instead."],
    ["It was a code word that would summon Zeus himself to help.", "It was a hidden escape tunnel underneath the city."],
    ["He challenged them both to an underwater wrestling match and won.", "He promised to introduce them to Poseidon in person if they helped."],
    ["She reported that Clarisse had finally agreed to bring the Ares cabin to help.", "She reported that Rachel had arrived safely at camp."],
  ],
  "pj-05-ch-11": [
    ["Percy tricked the Minotaur into charging off the bridge by himself.", "Annabeth distracted the Minotaur while Percy snuck up from behind."],
    ["Percy recognized Beckendorf, very much alive and fighting for Kronos.", "Percy recognized Luke's old friend Chris Rodriguez among the enemy."],
    ["Grover blocked the blow with his reed pipes at the last second.", "The strike missed completely because Percy's new invincibility protected him everywhere."],
    ["He asked the river gods to flood the entire bridge and wash the army away.", "He convinced the Party Ponies to charge in and scatter the enemy."],
    ["Michael Yew was seen flying safely back toward camp on a chariot.", "Michael Yew called Percy on the phone to say he was okay."],
  ],
  "pj-05-ch-12": [
    ["He told her he was thinking about accepting immortality from the gods.", "He told her that Beckendorf's ghost had spoken to him in a dream."],
    ["She admitted that she used to secretly work as a spy for Luke.", "She admitted that Luke had once tried to steal her invisibility cap."],
    ["He reported that all the satyrs had abandoned their posts and fled the city.", "He reported that Juniper had been captured by enemy forces."],
    ["He learned the Oracle chose on its own never to speak again after a bad prophecy.", "He learned Zeus destroyed the original Oracle out of jealousy."],
    ["Rachel discovered she could suddenly talk to animals and used that to warn her father.", "Rachel discovered a hidden treasure map and used it to bargain with her father."],
  ],
  "pj-05-ch-13": [
    ["Ares arrived to demand the campers surrender their weapons.", "Luke himself arrived, asking to speak with Percy alone."],
    ["He explained that Kronos had rescued him from a monster attack as a child.", "He explained that he lost his eye fighting alongside Percy the previous summer."],
    ["He saw a vision of Kronos being defeated by the original Olympian gods.", "He saw a vision of Beckendorf's final moments on the Princess Andromeda."],
    ["He gave Percy a map showing every hiding spot of Kronos's forces.", "He gave Percy a magic shield that could block any weapon."],
    ["A fight broke out and Percy chased Prometheus away.", "Prometheus agreed to switch sides and help the campers instead."],
  ],
  "pj-05-ch-14": [
    ["The battle took place at the Empire State Building lobby, against Kronos himself.", "The battle took place at the Brooklyn Bridge, against a new army of giants."],
    ["They convinced Hyperion to switch sides and fight for the campers instead.", "They used Greek fire to burn Hyperion until he retreated."],
    ["He sent a fully armored army of skeleton warriors.", "He sent Typhon himself early to attack New York."],
    ["He lured the pig into the East River, where the river god drowned it.", "He used his sword to cut off its wings so it couldn't fly anymore."],
    ["Kronos openly admitted defeat and offered to surrender to the gods.", "Kronos revealed the exact location of Percy's one weak spot."],
  ],
  "pj-05-ch-15": [
    ["Poseidon arrived personally to fight alongside the campers.", "Clarisse finally arrived with the whole Ares cabin."],
    ["Typhon had defeated Zeus and taken over Mount Olympus already.", "Typhon had captured Poseidon's underwater palace."],
    ["Dionysus warned that the campers should surrender immediately to save lives.", "Dionysus warned that Percy's mother was in danger back home."],
    ["He found a secret note from Luke warning him about a trap.", "He found that Blackjack had been hiding there the whole time."],
    ["Rachel arrived riding on the back of a hippocampus.", "Rachel walked in calmly through the front doors of the Plaza Hotel."],
  ],
  "pj-05-ch-16": [
    ["Percy used his water powers to gently guide the helicopter down.", "Chiron flew up and towed the helicopter safely to the ground."],
    ["She warned him that Annabeth was secretly working against him.", "She warned him that Chiron was planning to retreat from the city."],
    ["The Minotaur returned for a second attack on the city.", "The Clazmonian Sow came back for revenge."],
    ["It was Annabeth, wearing borrowed Ares armor to surprise the enemy.", "It was Thalia, who had swapped armor with Clarisse as a trick."],
    ["It turned out to be Rachel Dare, who had secretly joined the fight.", "It turned out to be Ethan Nakamura, who had switched sides to help them."],
  ],
  "pj-05-ch-17": [
    ["She revealed that Clarisse had asked her to wear the armor as part of a prank.", "She revealed that she had secretly been planning to switch sides back to the campers all along."],
    ["Clarisse quietly returned to camp, too devastated to keep fighting.", "Clarisse blamed Percy for Silena's death and refused to speak to him."],
    ["She admitted that she wanted to give up architecture and become a warrior instead.", "She admitted she had known about Silena's secret the whole time."],
    ["Percy opened the jar to see what would happen, just out of curiosity.", "Percy threw the jar into the Hudson River to get rid of it for good."],
    ["He asked Poseidon to make him a god right there on the spot.", "He asked Poseidon to send Tyson home to safety immediately."],
  ],
  "pj-05-ch-18": [
    ["Chiron defeated Kronos single-handedly and ended the battle early.", "Chiron retreated safely once his arrows ran out."],
    ["Poseidon arrived with an army of Cyclopes and mermen.", "Chiron's centaur army returned with reinforcements from every state."],
    ["He collapsed the elevator shaft so no one could reach Olympus at all.", "He turned the whole building invisible so mortals couldn't see the fight."],
    ["They stayed safely hidden in their car the entire time.", "They called the police to handle the monsters instead of fighting themselves."],
    ["He asked her to guard Percy's parents at the barrier's edge.", "He asked her to carry Silena's shroud back to camp."],
  ],
  "pj-05-ch-19": [
    ["He knocked Kronos's scythe into the hearth fire, melting it instantly.", "He convinced Kronos to fight Annabeth instead so he could rest."],
    ["Ethan refused to fight at all and simply walked away from the battle.", "Ethan struck Percy anyway but missed by accident."],
    ["Grover's music finally broke the spell holding Luke under Kronos's control.", "Drinking a potion from Chiron restored Luke's mind instantly."],
    ["Percy chose to throw the knife into the hearth instead of using it.", "Percy chose to strike Kronos himself while Luke was distracted."],
    ["Luke tricked Kronos into falling into the hearth fire and escaped unharmed.", "Luke defeated Kronos but then flew away to recover somewhere secret."],
  ],
  "pj-05-ch-20": [
    ["He realized it meant Riptide would eventually have to be destroyed forever.", "He realized it meant Kronos's scythe would one day kill a god."],
    ["He asked for fireworks to be set off over the whole city.", "He asked Zeus to send a message directly to Rachel's family."],
    ["Annabeth was made a goddess, and Grover was given Poseidon's trident to guard.", "Annabeth was sent to guard the Underworld, and Grover was made a Party Pony general."],
    ["Percy accepted immediately and became the newest Olympian god.", "Percy asked to be made king of the Cyclopes instead."],
    ["He asked that Camp Half-Blood be moved somewhere safer, far from New York.", "He asked that Kronos be completely destroyed once and for all, with no chance of returning."],
  ],
  "pj-05-ch-21": [
    ["Hermes confirmed that Kronos had been permanently destroyed and could never return.", "Hermes said Kronos had been imprisoned again in Tartarus for good."],
    ["He asked Percy to adopt one of his unclaimed children personally.", "He asked Percy to keep the list a secret from Chiron."],
    ["Athena thanked him warmly and offered him a permanent seat on Olympus.", "Athena ignored him completely and walked away without a word."],
    ["He reunited with Beckendorf, who had somehow survived after all.", "He reunited with Silena, who had recovered from her injuries."],
    ["Nico reported that Kronos's scattered dust had already started to reform.", "Nico reported that Clarisse had been badly hurt and needed help."],
  ],
  "pj-05-ch-22": [
    ["They borrowed a car and drove straight up the highway.", "They flew there together on the back of Mrs. O'Leary."],
    ["Rachel decided to enroll at Camp Half-Blood as a full-time camper.", "Rachel challenged Clarisse to a duel to prove she belonged at camp."],
    ["She said, \"A single choice shall end his days,\" repeating the old prophecy.", "She predicted the exact day Kronos would return to attack again."],
    ["It turned out Percy was actually turning seventeen, not sixteen.", "It turned out Percy shared his birthday with Grover."],
    ["They had a big argument and didn't speak for the rest of the night.", "They announced they were both leaving camp for good."],
  ],
  "pj-05-ch-23": [
    ["The camp was shrinking because so many campers had decided to leave for good.", "The camp was being moved to a brand-new location outside New York."],
    ["Poseidon asked Percy to move permanently to his underwater palace.", "Poseidon revealed that Triton would be visiting camp very soon."],
    ["It showed a picture of the Princess Andromeda exploding at sea.", "It showed Rachel's face as a tribute to the new Oracle."],
    ["Both girls decided to stay at Camp Half-Blood all year round.", "Rachel and Annabeth were both moving away to California together."],
    ["The book ends with Percy accepting the gods' offer of immortality after all.", "The book ends with Kronos reappearing to attack the camp one more time."],
  ],
};

export default percyJacksonDistractors;
