import type { Series } from "./types";

const percyJackson: Series = {
  id: "percy-jackson",
  title: "Percy Jackson & the Olympians",
  author: "Rick Riordan",
  description: "A boy discovers he's the son of a Greek god and must battle monsters, titans, and the forces of darkness to save Olympus.",
  recommendedAge: "9-12",
  themeColor: "#1565C0",
  books: [
    // ─────────────────────────────────────────────
    // BOOK 1: THE LIGHTNING THIEF
    // ─────────────────────────────────────────────
    {
      id: "pj-01",
      number: 1,
      title: "The Lightning Thief",
      color: "#1976D2",
      listenFor: "Percy discovers who his father really is",
      verified: false,
      questions: [],
      chapters: [
        {
          id: "ch-01",
          number: 1,
          title: "The Museum Attack",
          listenFor: "What does Percy's pen actually turn into?",
          questions: [
            { q: "Where was Percy's class on a field trip when Mrs. Dodds attacked him?", a: "At the Metropolitan Museum of Art in New York City." },
            { q: "What did Percy's maths teacher Mrs. Dodds transform into?", a: "A Fury — a winged monster from the Underworld with leathery wings and claws." },
            { q: "What weapon did Percy use to defend himself, and where did it come from?", a: "A bronze sword called Riptide, which had been disguised as a ballpoint pen given to him by Mr. Brunner." },
            { q: "What happened to Mrs. Dodds when Percy struck her with the sword?", a: "She exploded into golden dust and disappeared completely." },
            { q: "What was strange about how Percy's classmates behaved after the attack?", a: "Everyone acted as though Mrs. Dodds had never existed — no one remembered her at all." },
          ],
        },
        {
          id: "ch-02",
          number: 2,
          title: "The Three Fates",
          listenFor: "What do the three old women do with their scissors?",
          questions: [
            { q: "Who were the three old women Percy and Grover spotted near the roadside?", a: "The Fates — ancient goddesses who control the length of every person's life by spinning and cutting threads." },
            { q: "What did one of the old women do while staring straight at Percy?", a: "She cut a length of yarn with gold scissors — a sign that someone's life was about to end." },
            { q: "How did Grover react when he saw the three women?", a: "He went white with fear and started trembling — his reaction told Percy this was far more dangerous than it looked." },
            { q: "What news arrived at the end of the school year that affected Percy's future?", a: "He received word that he had been expelled from Yancy Academy and could not return." },
            { q: "What plan did Sally, Percy's mother, make once she found out he was expelled?", a: "She decided to take Percy to the family's holiday cabin at Montauk Beach for a few days before deciding what to do next." },
          ],
        },
        {
          id: "ch-03",
          number: 3,
          title: "The Storm at Montauk",
          listenFor: "What secret does Percy's mum finally tell him about his father?",
          questions: [
            { q: "What was unusual about the storm that rolled in while Percy and his mother were at the cabin?", a: "It came in impossibly fast and felt unnatural — the sky turned black in minutes with no warning." },
            { q: "Who arrived at the cabin unexpectedly, soaking wet and in a panic?", a: "Grover appeared at the door, terrified — he had come to warn them that something dangerous was on its way." },
            { q: "What important secret did Percy's mother Sally finally reveal to him that night?", a: "She told Percy the truth about his father — that he was a Greek god, not just someone who had abandoned them." },
            { q: "Why had Sally kept Percy's true identity hidden from him his whole life?", a: "She was trying to protect him — knowing who he was would attract monsters, and she had been shielding him from that danger." },
            { q: "What decision did Sally and Grover make together about what to do next?", a: "They decided to drive Percy to Camp Half-Blood immediately, where he could be safe among others like him." },
          ],
        },
        {
          id: "ch-04",
          number: 4,
          title: "The Minotaur",
          listenFor: "How does Percy defeat the Minotaur?",
          questions: [
            { q: "What monster attacked Percy, his mother, and Grover on the hillside outside camp?", a: "The Minotaur — a massive creature with a man's body and the head of a bull — came charging through the darkness." },
            { q: "What happened to Percy's mother when the Minotaur seized her?", a: "She vanished in a blinding flash of golden light, taken away right in front of Percy's eyes." },
            { q: "How did Percy defeat the Minotaur even though he had no training?", a: "He grabbed the Minotaur's horn, snapped it off, and stabbed the monster with its own horn until it dissolved." },
            { q: "What happened to Percy immediately after he killed the Minotaur?", a: "He collapsed from exhaustion and woke up inside Camp Half-Blood, unsure how much time had passed." },
            { q: "Why was Percy devastated even after winning the fight against the Minotaur?", a: "His mother had been taken and he had no idea if she was alive — he had saved himself but lost her." },
          ],
        },
        {
          id: "ch-05",
          number: 5,
          title: "Camp Half-Blood",
          listenFor: "What is Mr. Brunner's big secret?",
          questions: [
            { q: "Who had been looking after Percy while he was unconscious after the Minotaur fight?", a: "Annabeth Chase, a daughter of Athena who was one of the most experienced campers at the camp." },
            { q: "What surprising truth did Percy learn about his teacher Mr. Brunner?", a: "Mr. Brunner was actually Chiron the centaur in disguise — half human, half horse — who had been watching over Percy." },
            { q: "What was Camp Half-Blood, and who lived there?", a: "A secret magical camp on Long Island where demigods — children of Greek gods and human parents — trained and stayed safe from monsters." },
            { q: "Why did monsters keep finding and attacking Percy even when he was at an ordinary school?", a: "His divine blood gave off a powerful scent that monsters could detect — the more powerful the demigod, the stronger the signal." },
            { q: "What were the cabins at Camp Half-Blood, and what did each one represent?", a: "Each cabin belonged to one of the Olympian gods, and campers lived in the cabin of their divine parent once they were officially claimed." },
          ],
        },
        {
          id: "ch-06",
          number: 6,
          title: "Capture the Flag",
          listenFor: "What glowing symbol appears above Percy's head?",
          questions: [
            { q: "Where did Percy sleep while no one knew which god was his parent?", a: "In the Hermes cabin, which took in all unclaimed demigods until their divine parent acknowledged them." },
            { q: "What happened to Percy's wounds when he fell into the creek during Capture the Flag?", a: "The water healed him instantly and filled him with energy — every injury vanished the moment he touched the stream." },
            { q: "Why was Percy's ability to be healed by water so significant?", a: "It was a sign of who his father was — only a son of Poseidon, god of the sea, would be strengthened and healed by water." },
            { q: "How did the whole camp find out who Percy's divine father was?", a: "A glowing green trident appeared floating above Percy's head — Poseidon was officially claiming him as his son." },
            { q: "Why did the news of Percy being a son of Poseidon make many campers uneasy?", a: "Poseidon had sworn not to have any more children — Percy's existence broke an ancient agreement and made the gods' tensions much worse." },
          ],
        },
        {
          id: "ch-07",
          number: 7,
          title: "The Oracle's Prophecy",
          listenFor: "What is the quest Percy is given?",
          questions: [
            { q: "What terrible news reached Camp Half-Blood that suddenly put everyone in danger?", a: "Zeus's master lightning bolt — the most powerful weapon in the world — had gone missing, and Percy was being blamed." },
            { q: "Why was the theft of the lightning bolt such a serious crisis?", a: "Zeus was furious and on the verge of declaring war on Poseidon, which could trigger a catastrophic war between all the Olympians." },
            { q: "What was the Oracle at Camp Half-Blood, and where did it live?", a: "An ancient prophetic spirit inside a mummified body kept in the attic of the Big House, which spoke riddles to heroes beginning a quest." },
            { q: "What did the Oracle's prophecy tell Percy he would have to do?", a: "Go west to find the stolen lightning bolt, face a god who had turned against Olympus, and return it before the summer solstice." },
            { q: "Who was chosen to go with Percy on his quest?", a: "Annabeth, daughter of Athena, and Grover the satyr would accompany him as his companions on the journey west." },
          ],
        },
        {
          id: "ch-08",
          number: 8,
          title: "Furies on the Bus",
          listenFor: "Who is chasing Percy and why?",
          questions: [
            { q: "How did Percy, Annabeth, and Grover begin their journey west?", a: "They boarded a Greyhound bus, using money Chiron had given them to travel towards their first destination." },
            { q: "Who appeared on the bus threatening the team?", a: "The three Furies in disguise — ancient monsters who served Hades — scanning each passenger until they spotted Percy." },
            { q: "How did the team escape from the Furies?", a: "They forced their way off the bus and fought the Furies long enough to flee, leaving the bus badly damaged behind them." },
            { q: "What did the attack by the Furies reveal about who was against Percy?", a: "It showed that Hades himself was hunting Percy — the Furies worked only for the god of the Underworld." },
            { q: "What did the team do after escaping to recover and plan their next move?", a: "They found shelter away from the road and regrouped — Annabeth reminded them to take the quest one step at a time." },
          ],
        },
        {
          id: "ch-09",
          number: 9,
          title: "Aunty Em's Garden",
          listenFor: "What trick does Percy use to fight without looking?",
          questions: [
            { q: "What was Aunty Em's Garden Gnome Emporium, and what was wrong with it?", a: "A roadside shop full of stone garden statues — but the statues were actually real people who had been turned to stone by the owner." },
            { q: "Who was Aunty Em really?", a: "She was Medusa — the ancient Gorgon whose gaze instantly turned anyone who looked at her directly into stone." },
            { q: "Why did Annabeth refuse to look at Medusa directly?", a: "Because anyone who met Medusa's gaze turned to stone — and Annabeth knew that, as a daughter of Athena who originally cursed Medusa, it felt especially dangerous." },
            { q: "How did Percy defeat Medusa without being turned to stone himself?", a: "He used his bronze shield as a mirror to see Medusa's reflection, then moved to behead her without ever looking at her directly." },
            { q: "What did Percy do with Medusa's severed head after the battle?", a: "He packaged it up and mailed it to Olympus as a bold message to the gods that he was real and taking his quest seriously." },
          ],
        },
        {
          id: "ch-10",
          number: 10,
          title: "The Gateway Arch",
          listenFor: "What surprising thing happens when Percy hits the water?",
          questions: [
            { q: "What happened when Percy and his friends went up the Gateway Arch in St. Louis?", a: "They were trapped at the top with Echidna and her pet Chimera — a fire-breathing creature made of mixed animal parts — who attacked them inside the observation deck." },
            { q: "How did Percy escape from the monster attack inside the Arch?", a: "He jumped through one of the Arch's windows and fell hundreds of feet into the Mississippi River far below." },
            { q: "What surprised Percy about hitting the river after falling from so high?", a: "He was completely unharmed — the water healed and protected him, and he discovered he could breathe underwater." },
            { q: "Who appeared to Percy while he was beneath the surface of the Mississippi?", a: "A river spirit sent by his father Poseidon, who delivered a brief message of encouragement and told Percy to trust himself." },
            { q: "What did Percy understand about his powers after the experience at the Arch?", a: "That water was his greatest source of strength — in or near it, he was faster, stronger, and virtually impossible to hurt." },
          ],
        },
        {
          id: "ch-11",
          number: 11,
          title: "Ares at the Diner",
          listenFor: "What is secretly hidden inside the backpack Ares gives Percy?",
          questions: [
            { q: "Who did Percy and his friends unexpectedly meet at a diner in Denver?", a: "Ares, the god of war, disguised as a huge intimidating biker with sunglasses hiding his burning eyes." },
            { q: "What deal did Ares offer the three heroes at the diner?", a: "He would arrange supplies and a way west if they went to a nearby waterpark and retrieved his shield, which he claimed to have left there." },
            { q: "What had the god Hephaestus set up inside the abandoned waterpark?", a: "A trap of mechanical spiders and automated weapons — he had rigged it to catch Ares and Aphrodite, who had been secretly meeting there." },
            { q: "What did Percy's team find inside the waterpark besides Ares's shield?", a: "A fully packed backpack that Ares had left for them, supposedly to help them continue their quest." },
            { q: "What was later revealed about the backpack Ares had given Percy?", a: "Zeus's stolen lightning bolt had been secretly hidden inside it — Ares had set Percy up to unknowingly carry it straight into the Underworld." },
          ],
        },
        {
          id: "ch-12",
          number: 12,
          title: "The Lotus Hotel",
          listenFor: "How does Percy finally manage to escape?",
          questions: [
            { q: "What was the Lotus Hotel and Casino in Las Vegas, and what made it dangerous?", a: "A luxurious hotel where magical lotus flowers were served as food, causing anyone who ate them to forget time and lose the will to leave." },
            { q: "How did the enchanted hotel trap Percy and his friends?", a: "The lotus food made everything feel wonderful — they played games and relaxed, completely forgetting their quest while days slipped by." },
            { q: "How did Percy break free from the hotel's spell when the others could not?", a: "He refused to keep eating the lotus food and used the memory of his trapped mother to force himself to focus on the urgency of the quest." },
            { q: "How long had they actually spent inside the hotel without realising it?", a: "Several days had passed in the real world, badly eating into the time they had before the summer solstice deadline." },
            { q: "What lesson did the Lotus Hotel teach Percy about the dangers they faced on the quest?", a: "That the most deadly traps were sometimes the ones that felt pleasant — not every danger came with claws and fangs." },
          ],
        },
        {
          id: "ch-13",
          number: 13,
          title: "The Underworld Entrance",
          listenFor: "Where is the entrance to the Underworld hidden?",
          questions: [
            { q: "Where was the secret entrance to the Underworld hidden in the modern world?", a: "In Los Angeles, disguised as a recording studio called DOA Recording Studios — a grim joke about death." },
            { q: "Who was Charon, and what was his role?", a: "The ancient ferryman of the dead who transported souls across the River Styx into the Underworld, and who demanded payment for the crossing." },
            { q: "How did Percy and his friends convince Charon to take them?", a: "They bribed him with golden drachmas — and Percy also mentioned Charon deserved a pay rise, which put him in a better mood." },
            { q: "What was the River Styx like when they crossed it?", a: "A dark, freezing river carrying the souls of the recently dead — grim and endless, with the sounds of misery echoing everywhere." },
            { q: "What animals guarded the far bank of the Styx that they had to get past?", a: "Cerberus — the gigantic three-headed dog who blocked the entrance to the deeper regions of the Underworld." },
          ],
        },
        {
          id: "ch-14",
          number: 14,
          title: "Through the Underworld",
          listenFor: "How does Annabeth get past Cerberus?",
          questions: [
            { q: "What was the Fields of Asphodel, and what kind of souls were found there?", a: "A vast grey plain where ordinary souls — neither heroic enough for Elysium nor evil enough for Tartarus — wandered for eternity." },
            { q: "How did Annabeth manage to get past the enormous three-headed dog Cerberus?", a: "She used a red rubber ball to play fetch and obedience games with him — the huge dog obeyed her commands like any dog wanting attention." },
            { q: "What did Percy notice about the Underworld that was different from what he had imagined?", a: "It was unimaginably vast — far bigger and older than he had pictured — and completely under Hades's control, making escape seem impossible." },
            { q: "What was Elysium, and why was it different from the Fields of Asphodel?", a: "It was the paradise section of the Underworld reserved for the truly heroic and noble — a place of beauty and peace, not grey misery." },
            { q: "How did Grover behave as they walked through the Underworld, and what did this show?", a: "He was terrified but kept going anyway — his loyalty to Percy was stronger than his fear of one of the worst places a satyr could be." },
          ],
        },
        {
          id: "ch-15",
          number: 15,
          title: "Facing Hades",
          listenFor: "What falls out of Percy's backpack in Hades's throne room?",
          questions: [
            { q: "How did Hades greet Percy when he arrived at the palace?", a: "With cold fury — he accused Percy of stealing both Zeus's lightning bolt and his own helm of darkness." },
            { q: "What shocking thing happened when Percy opened the backpack Ares had given him?", a: "Zeus's master lightning bolt fell out — it had been hidden inside all along, and Percy had unwittingly carried it into the Underworld." },
            { q: "What was Hades's missing helm of darkness, and why did he want it back?", a: "A magical helm that made the wearer invisible — it was his greatest symbol of power, and it had been stolen along with the lightning bolt." },
            { q: "What threat did Hades make when Percy protested he had been framed?", a: "He threatened to keep all three of them prisoner in the Underworld, using them as hostages in the war between the gods." },
            { q: "What did Percy start to piece together about who had actually set him up?", a: "He realised Hades hadn't stolen the bolt — someone else had hidden it in the backpack Ares gave him, meaning there was a third culprit behind everything." },
          ],
        },
        {
          id: "ch-16",
          number: 16,
          title: "Escape with the Pearls",
          listenFor: "Why can't Percy take his mother with him when they escape?",
          questions: [
            { q: "What magical items did Percy have that could get his team out of the Underworld?", a: "Three pearls sent to him earlier by a Nereid on behalf of his father Poseidon — each one would transport a person back to the surface when smashed." },
            { q: "What painful choice did Percy face about using the three pearls?", a: "There were exactly three pearls for three people — him, Annabeth, and Grover — which meant there was no pearl left for his mother." },
            { q: "How did the pearls work when Percy's team used them?", a: "They smashed the pearls at their feet and were instantly transported upward through the earth, bursting out onto Santa Monica Beach." },
            { q: "How did Percy feel about having to leave his mother behind in the Underworld?", a: "He was heartbroken — but he knew the only way to eventually free her was to stop the war between the gods first." },
            { q: "Who was waiting for them on the Santa Monica beach when they arrived?", a: "Ares — blocking their path, making it clear he was there to make sure Percy never successfully completed his quest." },
          ],
        },
        {
          id: "ch-17",
          number: 17,
          title: "The Fight with Ares",
          listenFor: "How does Percy actually wound a god?",
          questions: [
            { q: "What did Ares reveal about why he had really helped Percy on the quest?", a: "He had been working on orders to create chaos and start a war between the gods — Percy's quest was meant to fail, not succeed." },
            { q: "How did Percy manage to wound the god of war in their duel?", a: "He used the power of the nearby ocean to boost his speed, catching Ares off guard and slashing his ankle with Riptide." },
            { q: "What happened when Percy drew divine blood (golden ichor) from Ares?", a: "Ares was forced to back down — a god who loses a fight against a mortal must yield — though he cursed Percy furiously before leaving." },
            { q: "What chilling warning did Ares give Percy before disappearing?", a: "He told Percy that Kronos — the ancient Titan king — was rising from Tartarus and had been manipulating everything that had happened." },
            { q: "What did Percy find on the beach after Ares vanished that he still needed to return?", a: "Hades's helm of darkness, which had been nearby all along — he now had to return both it and the lightning bolt to their owners." },
          ],
        },
        {
          id: "ch-18",
          number: 18,
          title: "Mount Olympus",
          listenFor: "Where is Mount Olympus hidden in the modern world?",
          questions: [
            { q: "Where was the entrance to Mount Olympus hidden in the modern world?", a: "On the 600th floor of the Empire State Building in New York City — a floor that only gods and demigods could reach." },
            { q: "How did Zeus react when Percy arrived and returned the lightning bolt?", a: "He accepted it, still suspicious and cold — but acknowledged that Percy had not been the one to steal it originally." },
            { q: "What happened to Hades's stolen helm of darkness?", a: "Percy handed it to one of the Furies who appeared on Olympus, asking her to return it to Hades as a gesture of good faith." },
            { q: "What did Hades do in return when his helm was given back?", a: "He released Percy's mother from the Underworld — she reappeared in the mortal world, free and unharmed." },
            { q: "What did Poseidon say to Percy when they finally spoke face to face?", a: "That he was proud of Percy for what he had done — and that he was sorry for the dangerous situation Percy's existence had put him in." },
          ],
        },
        {
          id: "ch-19",
          number: 19,
          title: "Luke's Betrayal",
          listenFor: "Why is Luke so angry at the gods?",
          questions: [
            { q: "What did Luke confess to Percy when he met him alone in the woods at camp?", a: "That he was the one who had actually stolen Zeus's lightning bolt — he had done it to prove that the Olympian system was corrupt and should be destroyed." },
            { q: "Why was Luke so furious at the Olympian gods?", a: "He felt the gods were careless, neglectful parents who abandoned their children, and he was determined to help Kronos tear down Olympus as revenge." },
            { q: "What did Luke do to Percy after revealing the truth?", a: "He unleashed a poisonous pit scorpion on Percy — the sting was designed to kill a demigod within minutes." },
            { q: "How did Percy survive the scorpion's deadly sting?", a: "He managed to call for help before losing consciousness, and the camp healers reached him in time to administer an antidote." },
            { q: "What did Percy now understand about the threat they were all facing?", a: "That Kronos was manipulating everything from Tartarus and using bitter demigods like Luke as his agents — the real war had barely started." },
          ],
        },
        {
          id: "ch-20",
          number: 20,
          title: "Going Home",
          listenFor: "What does Percy decide about his future?",
          questions: [
            { q: "What happened when Percy returned to his mother's apartment after the quest?", a: "She was there, alive and free — Hades had released her as promised once his helm was returned, and she was overjoyed to see Percy safe." },
            { q: "How did Percy's mother react when she heard about everything Percy had been through?", a: "She was proud but frightened — it confirmed her worst fears about the dangers Percy would always face because of who his father was." },
            { q: "What did Percy know would be permanently different about his life going forward?", a: "He could never un-know what he was — a demigod — and that monsters and divine conflict would follow him wherever he went." },
            { q: "What did Percy decide about the following school year?", a: "He chose to go back to regular school for the year, returning to a normal life while planning to go back to camp the following summer." },
            { q: "What was Percy's biggest worry as the summer came to an end?", a: "That Kronos was still out there in Tartarus growing stronger, and that Luke's betrayal meant the coming war had only just begun." },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // BOOK 2: THE SEA OF MONSTERS
    // ─────────────────────────────────────────────
    {
      id: "pj-02",
      number: 2,
      title: "The Sea of Monsters",
      color: "#0277BD",
      listenFor: "Listen for what Tyson is hiding about himself",
      verified: false,
      questions: [],
      chapters: [
        {
          id: "ch-01",
          number: 1,
          title: "Dreams and a New School",
          listenFor: "What keeps appearing in Percy's nightmares?",
          questions: [
            { q: "What kept appearing in Percy's dreams at the start of the book?", a: "Visions of Grover trapped inside a cave on a monster's island, wearing a wedding veil and desperately sending an empathy link." },
            { q: "Who was Tyson, and what made him stand out at Percy's new school?", a: "A large, clumsy, gentle boy who seemed oddly out of place and was being bullied — Percy was the only person who showed him any kindness." },
            { q: "How had Percy's school year been different from previous ones?", a: "No monsters had attacked all year — it had been suspiciously quiet and uneventful, which turned out to be too good to last." },
            { q: "How did Percy treat Tyson even though other students avoided him?", a: "He befriended Tyson and defended him from bullies, letting him sit with him at lunch and standing up for him when others were unkind." },
            { q: "What event at the end of the school year shattered the calm and forced Percy back into the world of monsters?", a: "A dodgeball game turned deadly when the opposing team revealed themselves as Laistrygonian giants hurling flaming bronze cannonballs to kill him." },
          ],
        },
        {
          id: "ch-02",
          number: 2,
          title: "The Giant Dodgeball Attack",
          listenFor: "What is surprising about how Tyson fights?",
          questions: [
            { q: "What were the Laistrygonians, and what were they doing at Percy's school?", a: "Giant cannibals from Greek mythology who had disguised themselves as students and teachers to get close enough to Percy to attack." },
            { q: "What was unusual about the balls being thrown during the game?", a: "They were heavy bronze cannonballs that exploded on impact and set things on fire — not ordinary rubber balls at all." },
            { q: "Who arrived to help Percy fight off the giant attackers?", a: "Annabeth Chase appeared, armed and ready — she had been monitoring Percy and arrived just in time to help." },
            { q: "What did Tyson do during the attack that no one had expected?", a: "He fought back against the giants with surprising strength and toughness, shrugging off blows that would have seriously injured a normal person." },
            { q: "How did Annabeth react to Tyson after the fight, and why was this telling?", a: "She was cold and mistrustful toward him — she was clearly frightened of him for a reason she had not yet explained." },
          ],
        },
        {
          id: "ch-03",
          number: 3,
          title: "Camp in Danger",
          listenFor: "What secret is Tyson hiding about what he really is?",
          questions: [
            { q: "What was wrong with Camp Half-Blood when Percy and his friends arrived?", a: "Thalia's pine tree — which powered the magical border protecting the camp — had been poisoned and was dying." },
            { q: "What was the consequence of the poisoned tree for everyone at camp?", a: "The magical barrier keeping monsters out was weakening, meaning the camp was no longer truly safe for the demigods inside." },
            { q: "What shocking truth about Tyson was revealed when they arrived at camp?", a: "He was a Cyclops — a one-eyed giant — and the single eye he had hidden under his hair was now visible." },
            { q: "How was Tyson connected to Percy beyond just being a school friend?", a: "He was Percy's half-brother — also a son of Poseidon, though his mother was a nature spirit rather than a human." },
            { q: "How did Percy feel about having a Cyclops as a half-brother?", a: "He was embarrassed and conflicted — at camp, Cyclopes were seen as something shameful, and Percy felt guilty about how Tyson might be treated." },
          ],
        },
        {
          id: "ch-04",
          number: 4,
          title: "The Quest for the Fleece",
          listenFor: "Who gets chosen for the quest — and who doesn't?",
          questions: [
            { q: "What was the Golden Fleece, and why was it believed to be able to save Thalia's tree?", a: "The hide of a magical golden ram — an ancient artefact with the power to heal any sickness, including the tree's poisoning." },
            { q: "Who was officially chosen to go on the quest to retrieve the Fleece, and why did it frustrate Percy?", a: "Clarisse, the daughter of Ares and Percy's long-time rival, was chosen — and Percy was left behind despite caring more about the camp's safety." },
            { q: "Who was Tantalus, the new activities director, and why was he unpleasant to deal with?", a: "A spirit from the Underworld given a temporary body — he was petty and unhelpful, taking every chance to make things harder for Percy." },
            { q: "What was the empathy link between Percy and Grover, and why was it so worrying?", a: "A magical emotional connection between a satyr and their demigod charge — through it Percy could feel Grover was in serious danger and running out of time." },
            { q: "What plan did Percy, Annabeth, and Tyson hatch after Percy was denied the official quest?", a: "They decided to undertake their own unofficial quest — setting out to find the Fleece and rescue Grover whether they had permission or not." },
          ],
        },
        {
          id: "ch-05",
          number: 5,
          title: "Luke's Cruise Ship",
          listenFor: "What is on board the Princess Andromeda that terrifies Percy?",
          questions: [
            { q: "What was the Princess Andromeda, and what did it turn out to really be?", a: "It appeared to be an ordinary luxury cruise ship, but it was actually Luke's mobile base of operations, crammed with monsters loyal to Kronos." },
            { q: "What horrifying object did Percy discover inside one of the ship's ballrooms?", a: "A massive golden coffin — Kronos's sarcophagus — which was slowly regenerating the Titan king piece by piece as his followers fed it power." },
            { q: "How did Luke greet Percy when he discovered him on the ship?", a: "With cold contempt — he offered Percy a chance to join Kronos's side and seemed genuinely puzzled that Percy would refuse." },
            { q: "How did Percy and his friends escape from the Princess Andromeda?", a: "They jumped overboard into the sea, where Percy's powers protected them and let them put distance between themselves and the ship quickly." },
            { q: "What did the encounter with the Princess Andromeda confirm about the threat they were all facing?", a: "That Kronos had a real army — monsters and bitter demigods working together — and that this was an organised rebellion, not just one villain acting alone." },
          ],
        },
        {
          id: "ch-06",
          number: 6,
          title: "Circe's Island",
          listenFor: "What does Circe do to Percy?",
          questions: [
            { q: "What was Circe's island, and what did her spa actually do to visitors?", a: "It appeared to be a luxury retreat, but Circe was an ancient enchantress who used magic to transform her male visitors into guinea pigs." },
            { q: "What happened to Percy when he accepted Circe's hospitality?", a: "She transformed him into a guinea pig before he could do anything about it — he found himself tiny and trapped in a cage." },
            { q: "Why was Annabeth spared from Circe's transformation magic?", a: "Circe's spell only worked on males, which meant Annabeth was safe and had to figure out how to rescue Percy on her own." },
            { q: "What did Annabeth use to change Percy back to human?", a: "Hermes's multivitamins — special supplies given to them at the start of their quest — which reversed Circe's transformation magic." },
            { q: "What did Percy and Annabeth realise about the other guinea pigs in Circe's cages?", a: "They were other visitors — some of them had been stuck in guinea pig form for centuries, trapped there since ancient times." },
          ],
        },
        {
          id: "ch-07",
          number: 7,
          title: "The Sirens",
          listenFor: "What is Annabeth's fatal flaw?",
          questions: [
            { q: "What were the Sirens, and why were they so deadly to sailors?", a: "Creatures whose irresistible singing drove listeners mad with longing — anyone who heard them would throw themselves into the sea to reach them and drown." },
            { q: "Why did Annabeth want to hear the Sirens' song even knowing the danger?", a: "Her fatal flaw was hubris — excessive pride in her own abilities — and she believed she was strong enough to resist what had killed countless sailors." },
            { q: "What precaution did Annabeth take before listening to the Sirens?", a: "She had Percy seal his own ears with wax so he could not hear, and had herself tied securely to the mast of the boat." },
            { q: "What happened to Annabeth when the Sirens' song reached her?", a: "She was completely overwhelmed — she broke free of her ropes and dove into the water, swimming desperately toward the sound before Percy dragged her back." },
            { q: "What did Annabeth admit about herself after Percy pulled her out of the water?", a: "She confessed that her fatal flaw was hubris — overconfidence — and that it had nearly killed her by making her believe she could handle anything." },
          ],
        },
        {
          id: "ch-08",
          number: 8,
          title: "Scylla and Charybdis",
          listenFor: "What appears to happen to Tyson — and what is the truth?",
          questions: [
            { q: "What were Scylla and Charybdis, and why were they so feared by sailors?", a: "Scylla was a six-headed sea monster that snatched sailors from the deck, and Charybdis was a colossal whirlpool that could swallow ships whole." },
            { q: "What terrible choice did the team face when they reached the strait between the two monsters?", a: "Sailing closer to Scylla meant losing a few to her heads — but sailing closer to Charybdis risked being sucked down and losing everyone." },
            { q: "What happened to Tyson when the ship was pulled toward the Charybdis whirlpool?", a: "He was dragged down into the swirling water and the others believed he had drowned — there was no sign of him after the ship broke free." },
            { q: "How did Percy, Annabeth, and Grover escape Charybdis?", a: "Percy used his power over water to fight the whirlpool's pull long enough for them to reach the far side of the strait." },
            { q: "What was the truth about what had happened to Tyson after he disappeared in the whirlpool?", a: "Poseidon had saved him — Tyson was later revealed to be alive and working in Poseidon's underwater forges, given a proper place among his kind." },
          ],
        },
        {
          id: "ch-09",
          number: 9,
          title: "Polyphemus's Cave",
          listenFor: "What ancient trick does Percy use on the Cyclops?",
          questions: [
            { q: "Why was Grover in such serious danger throughout the book?", a: "He was trapped in Polyphemus's cave, pretending to be a female Cyclops named Honeybee — the Cyclops wanted to marry him and was running out of patience." },
            { q: "How did Percy and Annabeth manage to get inside Polyphemus's cave?", a: "They crept in carefully, using Annabeth's invisibility cap to help them stay hidden while they figured out where Grover was." },
            { q: "What clever trick did Percy use against Polyphemus?", a: "He called himself 'Nobody' — copying the trick Odysseus had used on the same Cyclops thousands of years earlier — to confuse Polyphemus when Percy hurt him." },
            { q: "How did the team finally secure the Golden Fleece in the chaos of the fight?", a: "Annabeth grabbed the Fleece from Polyphemus's tree while Percy kept the Cyclops distracted, and they ran for the shore with Grover." },
            { q: "What did Percy do to buy enough time for Annabeth and Grover to escape with the Fleece?", a: "He stood and fought Polyphemus directly, holding the enraged Cyclops's attention while the others made it safely to the water's edge." },
          ],
        },
        {
          id: "ch-10",
          number: 10,
          title: "The Fleece Heals the Tree",
          listenFor: "What completely unexpected thing does the Fleece do to Thalia's tree?",
          questions: [
            { q: "How did Clarisse end up being the one to bring the Fleece back to camp?", a: "She arrived at the island during the fight and took the Fleece, carrying out her official quest even though Percy's team had been the ones to actually retrieve it." },
            { q: "What happened when the Golden Fleece was placed on Thalia's poisoned tree?", a: "Its magic worked immediately — the tree healed, turned green and healthy, and the camp's magical border snapped back to full strength." },
            { q: "What completely unexpected thing happened as the Fleece's magic spread through the tree?", a: "Thalia herself was brought back to life — she had been transformed into the tree years ago and the Fleece's power reversed it, making her a real person again." },
            { q: "Who was Thalia, and why was her return such a big deal for the gods?", a: "She was a daughter of Zeus — one of the most powerful demigods alive — and her return meant the Great Prophecy could now apply to her instead of Percy." },
            { q: "What did the appearance of Thalia signal about the bigger threat waiting for them all?", a: "That the stakes were growing — more powerful players were entering the game, and Kronos was getting closer to having everything he needed to rise." },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // BOOK 3: THE TITAN'S CURSE
    // ─────────────────────────────────────────────
    {
      id: "pj-03",
      number: 3,
      title: "The Titan's Curse",
      color: "#7B1FA2",
      listenFor: "Pay attention to who the mysterious General really is",
      verified: false,
      questions: [],
      chapters: [
        {
          id: "ch-01",
          number: 1,
          title: "Westover Hall",
          listenFor: "Who are the two demigods hiding at the military school?",
          questions: [
            { q: "Why did Percy, Thalia, and Grover travel to Westover Hall military academy?", a: "Grover had detected two young demigods there — a brother and sister named Bianca and Nico di Angelo — who needed to be brought to safety before monsters found them." },
            { q: "What creature attacked during the confrontation at Westover Hall?", a: "Dr. Thorn, a manticore — a monster with a human face, lion's body, and a tail that fired poisoned spines — who was working for an unknown enemy." },
            { q: "What happened to Annabeth during the battle with Dr. Thorn?", a: "She was swept off a cliff by the manticore and captured — she disappeared into the darkness before anyone could reach her." },
            { q: "Who arrived to help fight the manticore just when things looked desperate?", a: "The Hunters of Artemis — a band of immortal girls who served the goddess Artemis — rode in and drove Dr. Thorn back." },
            { q: "What was the immediate crisis after the battle ended?", a: "Annabeth was missing and captured, and the demigods had to figure out where she had been taken and by whom." },
          ],
        },
        {
          id: "ch-02",
          number: 2,
          title: "Bianca's Choice",
          listenFor: "Why does Bianca's decision upset her brother Nico so much?",
          questions: [
            { q: "Who were Bianca and Nico di Angelo, and what made them unusual even among demigods?", a: "A sister and brother who had been hidden from the divine world for years — they had no idea they were demigods and had never been to Camp Half-Blood." },
            { q: "What was the Hunters of Artemis, and what did joining them mean for a girl?", a: "A band of immortal young women devoted to the goddess Artemis who swore off romantic love in exchange for immortality and a life of hunting." },
            { q: "What decision did Bianca make that shocked everyone, especially her little brother?", a: "She chose to join the Hunters of Artemis, giving up the chance to go to camp and leaving Nico behind without his sister to look after him." },
            { q: "How did Nico react to Bianca's choice to join the Hunters?", a: "He was devastated and felt abandoned — Bianca was the only family he had, and her decision left him completely alone." },
            { q: "Why did Artemis herself appear at Westover Hall, and what was she about to do?", a: "She had picked up the trail of a great monster that she believed posed a catastrophic threat to Olympus, and she was setting out alone to hunt it." },
          ],
        },
        {
          id: "ch-03",
          number: 3,
          title: "The Quest to Find Artemis",
          listenFor: "What does the Oracle's prophecy say about who will die?",
          questions: [
            { q: "What crisis occurred shortly after the team returned to camp?", a: "Artemis herself went missing — she had gone to hunt the great monster alone and had not come back, leaving the Olympians alarmed." },
            { q: "What prophecy did the Oracle at Camp Half-Blood give about the quest to find Artemis?", a: "It warned that five would go and that one would be lost in the land without rain, that the bane of Olympus showed the hero's might, and that a choice would end all." },
            { q: "Who made up the official quest team sent to find Artemis?", a: "Zoe Nightshade (Artemis's lieutenant), Bianca di Angelo, Thalia, and Grover — with Percy joining unofficially after a dream sent him a vision of Annabeth." },
            { q: "Why was Percy not officially included in the quest team?", a: "The Oracle's prophecy specified five questers and Percy was not one of them — he went anyway against the rules because of the vision about Annabeth." },
            { q: "What important clue did Percy learn about where Annabeth was being held?", a: "His dreams showed him Annabeth was being held by 'the General' — a powerful figure working for Kronos whose identity was not yet known." },
          ],
        },
        {
          id: "ch-04",
          number: 4,
          title: "Westward Journey",
          listenFor: "What is Grover sensing on the way west?",
          questions: [
            { q: "What was Grover detecting as the team travelled west across the country?", a: "He could sense the presence of Pan — the ancient god of the wild — somewhere far to the west, which filled him with both hope and urgency." },
            { q: "What enemies were pursuing the quest team across the country?", a: "Skeleton warriors — the Spartoi — who had been sent by the General and could not be permanently destroyed, only temporarily driven off." },
            { q: "What made the Spartoi skeleton warriors so terrifying to fight?", a: "They always got back up — every time the heroes knocked them down they simply reassembled themselves and continued the chase." },
            { q: "What did Percy's ongoing dreams reveal about Annabeth's situation?", a: "She was alive but being held somewhere with a great weight overhead — the General was using her as leverage and she was getting weaker." },
            { q: "How did Zoe's attitude toward Percy change slightly as the journey continued?", a: "She remained cold and disapproving — as a Hunter she distrusted all boys — but she grudgingly began to acknowledge his usefulness in a fight." },
          ],
        },
        {
          id: "ch-05",
          number: 5,
          title: "The Junkyard of the Gods",
          listenFor: "What does Bianca do that costs her her life?",
          questions: [
            { q: "What was the junkyard the team stumbled into, and why was it dangerous?", a: "A vast desert scrapyard filled with broken or discarded items belonging to the gods — touching or taking anything risked triggering divine defences." },
            { q: "What tempted Bianca to go inside one of the giant metal objects in the junkyard?", a: "She spotted a small toy figure inside that she wanted to bring back for Nico as a gift — she crawled inside to get it without telling anyone." },
            { q: "What happened when Bianca tried to take the toy from inside the giant metal figure?", a: "The figure activated and came to life — it was a giant automated bronze soldier — and Bianca could not get out before it began to move and fall." },
            { q: "How did the rest of the team try to save Bianca?", a: "They attacked the metal soldier desperately, trying to destroy it or force it to stop before Bianca was crushed — but they were too late." },
            { q: "What impact did Bianca's death have on the remaining quest team?", a: "Zoe was stricken with grief for her fellow Hunter, Percy felt guilty he couldn't save her, and everyone knew Nico didn't yet know what had happened to his sister." },
          ],
        },
        {
          id: "ch-06",
          number: 6,
          title: "The General Is Atlas",
          listenFor: "Why is Atlas forcing Artemis to hold up the sky?",
          questions: [
            { q: "Who was the General, and what was his real identity?", a: "He was the Titan Atlas — freed from his ancient punishment — who had been hiding his true nature while building Kronos's forces." },
            { q: "What was Atlas's punishment in Greek mythology, and how had he escaped it?", a: "He had been condemned to hold up the sky for eternity, but he had arranged for someone else to take the burden so he could walk free." },
            { q: "What had Atlas done to Artemis, and why?", a: "He had tricked her into taking the sky onto her own shoulders — trapping her under its crushing weight — to free himself from his eternal punishment." },
            { q: "Where was Annabeth being held, and in what condition was she?", a: "She was also there near the mountain, alive but barely — the General had used her as bait to lure the hunters into a trap." },
            { q: "What was Atlas's larger plan in service of Kronos?", a: "To free himself completely, raise a monster powerful enough to destroy Olympus, and hand victory to Kronos — he had been manipulating the quest from the beginning." },
          ],
        },
        {
          id: "ch-07",
          number: 7,
          title: "Percy Holds the Sky",
          listenFor: "How does Percy give Artemis a chance to break free?",
          questions: [
            { q: "What did Percy do to help free Artemis from the crushing weight of the sky?", a: "He ran forward and took the sky onto his own shoulders, holding it up so that Artemis could finally break free and rejoin the fight." },
            { q: "What was it like for Percy to hold the sky?", a: "Unbearable — the weight was unimaginable and grew heavier every second, threatening to crush him into the ground while his legs shook with the effort." },
            { q: "What happened in the battle while Percy held the sky?", a: "Zoe fought her father Atlas directly in a fierce duel, Thalia battled Luke at the mountain's edge, and Artemis moved to help once she was free." },
            { q: "How did Artemis finally take the sky back and free Percy?", a: "She wrestled it from his shoulders and carried it briefly herself, then used her divine strength to manoeuvre it back where it belonged." },
            { q: "What happened to Luke during the fighting on the mountain?", a: "Thalia fought him and knocked him off the edge of the cliff — he fell, but landed on the Princess Andromeda below and escaped." },
          ],
        },
        {
          id: "ch-08",
          number: 8,
          title: "Zoe's Last Fight",
          listenFor: "How does Artemis honour Zoe at the end?",
          questions: [
            { q: "What happened to Zoe Nightshade during the battle against Atlas?", a: "She was fatally wounded by her own father during the duel — Atlas struck her with a blow she could not survive." },
            { q: "What did Percy learn about the relationship between Zoe and Atlas?", a: "Atlas was her father — she had been born a Titan's daughter but had turned against him long ago to serve Artemis instead, and he had never forgiven her." },
            { q: "How did Zoe spend her final moments after the battle?", a: "She said goodbye to Artemis and the quest team, fading away peacefully — she had fulfilled her duty and was at peace with it." },
            { q: "How did Artemis honour Zoe after her death?", a: "She placed Zoe among the stars as a new constellation — the Huntress — so her courage would shine in the night sky for ever." },
            { q: "What important choice did Thalia make at the end of the quest?", a: "She joined the Hunters of Artemis, becoming immortal — which meant she would never turn 16 and could not be the child in the Great Prophecy." },
          ],
        },
        {
          id: "ch-09",
          number: 9,
          title: "Nico's Discovery",
          listenFor: "What secret about Nico and Bianca is finally revealed?",
          questions: [
            { q: "How did Nico find out that his sister Bianca had died on the quest?", a: "Percy had to tell him directly — there was no gentle way to deliver the news, and Nico's reaction was immediate and overwhelming grief." },
            { q: "How did Nico respond when Percy told him about Bianca's death?", a: "He was devastated and furious — he blamed Percy for not protecting his sister, and in his grief he summoned skeletal soldiers out of the earth before running away." },
            { q: "What extraordinary power did Nico accidentally demonstrate when he lost control of his emotions?", a: "He called the dead up from the ground without meaning to — soldiers' skeletons burst out of the earth and attacked Percy before Nico fled." },
            { q: "What shocking secret about Nico and Bianca's true identity was revealed?", a: "They were children of Hades — the god of the Underworld — which explained Nico's power over the dead and made them incredibly rare and dangerous." },
            { q: "Why was being a child of Hades so significant in terms of the Great Prophecy?", a: "Hades was one of the three eldest gods — along with Zeus and Poseidon — meaning Nico was a candidate for the child in the prophecy that could destroy Olympus." },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // BOOK 4: THE BATTLE OF THE LABYRINTH
    // ─────────────────────────────────────────────
    {
      id: "pj-04",
      number: 4,
      title: "The Battle of the Labyrinth",
      color: "#558B2F",
      listenFor: "Notice what the swordmaster Quintus is hiding",
      verified: false,
      questions: [],
      chapters: [
        {
          id: "ch-01",
          number: 1,
          title: "A New School, A New Threat",
          listenFor: "What does Percy find hidden beneath the school?",
          questions: [
            { q: "What new school was Percy attending at the start of the book?", a: "Goode High School — his mother's boyfriend Paul Blofis taught English there, which is why Percy had ended up enrolled." },
            { q: "Who did Percy run into at the school orientation that surprised him?", a: "Rachel Elizabeth Dare — the mortal girl who had helped him during the battle of the Labyrinth's predecessor events and who could see through the Mist." },
            { q: "What happened at the school orientation to interrupt Percy's attempt at a normal start?", a: "Monster cheerleaders attacked him in the gymnasium, revealing themselves as empousai — creatures that fed on the blood of young men." },
            { q: "What did Percy discover hidden beneath the school gymnasium?", a: "An entrance to Daedalus's Labyrinth — a hidden trapdoor leading down into the ancient underground maze." },
            { q: "Why was finding a Labyrinth entrance inside the school so alarming?", a: "It meant the Labyrinth connected to places in the normal world, and anyone who knew how to navigate it could use it to move undetected." },
          ],
        },
        {
          id: "ch-02",
          number: 2,
          title: "The Labyrinth Under Camp",
          listenFor: "How could Luke use the Labyrinth to destroy Camp Half-Blood?",
          questions: [
            { q: "What did Annabeth discover about the Labyrinth when the team investigated the entrance at camp?", a: "There was an entrance directly beneath Camp Half-Blood's arena — Luke could use it to send his entire army inside the magical border undetected." },
            { q: "Why was the Labyrinth such a perfect weapon for Luke to use against the camp?", a: "It ran beneath the magical border, meaning monsters could bypass all of the camp's defences and appear inside the safe zone without any warning." },
            { q: "What quest did Annabeth receive, and why was it especially significant for her?", a: "She was given the quest to find Daedalus in the Labyrinth and either recruit him to help camp or stop Luke from doing so — it was her first time leading a quest." },
            { q: "Who made up the quest team for the Labyrinth mission?", a: "Annabeth led the team, with Percy, Grover, and Tyson accompanying her into the underground maze." },
            { q: "What was the core problem with navigating the Labyrinth?", a: "The maze shifted and changed constantly — no map ever stayed accurate for long, and a wrong turn could lead anywhere in the ancient world." },
          ],
        },
        {
          id: "ch-03",
          number: 3,
          title: "Rachel in the Maze",
          listenFor: "What can Rachel see that the demigods cannot?",
          questions: [
            { q: "Why was navigating the Labyrinth nearly impossible for Annabeth, despite all her intelligence?", a: "The maze was magically designed to resist the minds of those with divine blood — its passages shifted and misled demigods specifically." },
            { q: "What special ability did Rachel Elizabeth Dare have that the team desperately needed?", a: "She could see through the Mist — the magic that hides the supernatural world — which allowed her to read the Labyrinth's true markings and find the right path." },
            { q: "Why was bringing Rachel into the Labyrinth controversial?", a: "She was a mortal with no training or combat ability — bringing a regular human into one of the most dangerous places in the world put her at serious risk." },
            { q: "How did Annabeth feel about relying on Rachel to navigate, and why?", a: "She was reluctant and slightly resentful — she prided herself on her intelligence and it stung that a mortal girl could do something she could not." },
            { q: "What was Rachel able to see in the Labyrinth that appeared invisible to Percy and Annabeth?", a: "Glowing marks on the walls that indicated the correct path — Daedalus had inscribed them so that a clear-sighted mortal could follow them." },
          ],
        },
        {
          id: "ch-04",
          number: 4,
          title: "Quintus Is Daedalus",
          listenFor: "What has Daedalus done to himself to keep living?",
          questions: [
            { q: "Who was Quintus, the new swordmaster at Camp Half-Blood?", a: "He was actually Daedalus — the legendary inventor who had built the Labyrinth — living inside a mechanical human body of his own construction." },
            { q: "Why had Daedalus transferred his soul into a mechanical body?", a: "He had found a way to achieve a kind of immortality — by housing his consciousness in an automaton, he could never die of old age or injury." },
            { q: "What had Luke offered Daedalus in exchange for giving him a way to navigate the Labyrinth?", a: "A chance to be fully free — Luke promised Daedalus that Kronos could give him real life again, not just a mechanical existence." },
            { q: "What did Annabeth realise about the camp's danger once she worked out who Quintus really was?", a: "That Daedalus might already have given Luke what he needed — if Luke had the secret to navigating the maze, the invasion could begin at any moment." },
            { q: "What terrible guilt did Daedalus carry that Percy learned about?", a: "He had killed his own nephew Perdix out of jealousy long ago — a crime he could never undo and that had haunted him ever since." },
          ],
        },
        {
          id: "ch-05",
          number: 5,
          title: "The God Pan Fades",
          listenFor: "What does Pan say as he disappears?",
          questions: [
            { q: "What had Grover been searching for across many years that was connected to the Labyrinth quest?", a: "Pan — the ancient god of the wild — who had been missing for centuries as humans destroyed the natural world and stopped believing in him." },
            { q: "What did Percy and Grover find when they finally located Pan deep in the Labyrinth?", a: "Pan was alive but fading — he had been slowly dissolving for centuries as the wild places of the world shrank and fewer people cared about nature." },
            { q: "What message did Pan give before he finally dissolved completely?", a: "He said the wild could not be saved by one god — it needed everyone to take responsibility for it — and then his spirit passed into those standing around him." },
            { q: "How did Grover feel about Pan's passing, and what did it mean for him?", a: "He was heartbroken — his lifelong mission had been to find Pan and he had arrived too late to save him. But Pan's spirit now lived inside Grover himself." },
            { q: "What did Percy understand about why the wild was in danger, based on what Pan told them?", a: "That the destruction of nature was a human problem, not a divine one — no god could fix it, only the choices people made about the world around them." },
          ],
        },
        {
          id: "ch-06",
          number: 6,
          title: "Kronos Takes Over Luke",
          listenFor: "What is Kronos doing to Luke's body?",
          questions: [
            { q: "What had Percy been seeing in his dreams about Luke throughout the book?", a: "Kronos was slowly possessing Luke's body — using the boy's anger and pain as a vessel to rebuild himself into a physical form, piece by piece." },
            { q: "How was Kronos able to use Luke as a host?", a: "Luke had willingly let Kronos in — his bitterness toward the gods was so deep that he had opened himself to possession as an act of deliberate revenge." },
            { q: "What sign did Percy see of Kronos's growing influence on Luke?", a: "Luke's eyes sometimes flickered with golden light and his voice changed, speaking with the authority and cruelty of a Titan rather than a teenager." },
            { q: "What did Nico reveal to Percy about a plan he had been working on in secret?", a: "He said he knew a way to give Percy an advantage against Kronos — but he would need Percy to trust him and keep the plan secret." },
            { q: "Why was Nico visiting the Underworld so often, and what had he learned there?", a: "He had been talking to the dead, trying to summon his sister Bianca and also to find out more about Percy's fatal flaw and how to use it." },
          ],
        },
        {
          id: "ch-07",
          number: 7,
          title: "The Battle of the Labyrinth",
          listenFor: "How does Daedalus finally destroy the Labyrinth?",
          questions: [
            { q: "How did Luke's army enter Camp Half-Blood?", a: "They poured through the Labyrinth tunnel beneath the camp's arena, bypassing all the magical defences and appearing inside the camp's border." },
            { q: "What did the battle look like inside Camp Half-Blood?", a: "Chaotic and desperate — monsters and demigods fighting all across the camp's grounds, with the campers badly outnumbered and taking serious losses." },
            { q: "How did Daedalus arrive at the battle, and what did he choose to do?", a: "He appeared during the fighting and decided he could not let his invention be used to destroy the people he had come to care about." },
            { q: "How did Daedalus destroy the Labyrinth and end the invasion?", a: "He chose to die — and because the Labyrinth was magically bound to his life, his death caused the entire maze to instantly collapse and disappear." },
            { q: "What was the cost of Daedalus's decision to destroy the Labyrinth?", a: "His life — the mechanical body that had housed his consciousness for centuries finally stopped, and Daedalus was truly gone." },
          ],
        },
        {
          id: "ch-08",
          number: 8,
          title: "Percy's Fatal Flaw",
          listenFor: "What secret has Nico worked out about Percy?",
          questions: [
            { q: "What did Nico reveal he had discovered about Percy's fatal flaw?", a: "Percy's fatal flaw was excessive personal loyalty — his fierce need to protect the people he cared about could be exploited to control him or destroy him." },
            { q: "How had Nico learned about Percy's fatal flaw?", a: "He had spoken with the spirit of his sister Bianca in the Underworld, who had given him insights into Percy's character and where he was most vulnerable." },
            { q: "Why did Nico keep this information secret instead of telling Percy directly?", a: "He was still working out how to use the knowledge — he believed Percy's weak spot was also the key to defeating Kronos, and he needed to understand it fully first." },
            { q: "How did the camp recover after the battle of the Labyrinth?", a: "Slowly and painfully — there were losses among the campers, and everyone knew the battle had been a warning of how much larger the coming war would be." },
            { q: "What was Kronos's status at the very end of the book, and why was it terrifying?", a: "He had almost fully taken over Luke's body — he was nearly complete, and his first real attack on the mortal world was only months away." },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────
    // BOOK 5: THE LAST OLYMPIAN
    // ─────────────────────────────────────────────
    {
      id: "pj-05",
      number: 5,
      title: "The Last Olympian",
      color: "#C62828",
      listenFor: "Listen for what Percy asks the gods to promise at the very end",
      verified: false,
      questions: [],
      chapters: [
        {
          id: "ch-01",
          number: 1,
          title: "The Princess Andromeda Burns",
          listenFor: "What does Beckendorf sacrifice himself to do?",
          questions: [
            { q: "What mission did Percy and his friend Beckendorf undertake at the start of the book?", a: "They snuck onto the Princess Andromeda to plant explosives and destroy Luke's cruise ship, hoping to cripple Kronos's forces before the final battle." },
            { q: "Who was Charles Beckendorf, and what happened to him during the mission?", a: "A son of Hephaestus and one of the best demigods at camp — he deliberately set off the explosives while still on the ship to make sure they went off, sacrificing himself." },
            { q: "How did Percy escape the explosion on the Princess Andromeda?", a: "He jumped into the sea just before the ship blew up — the water protected him and he swam clear of the wreckage." },
            { q: "What did the destruction of the Princess Andromeda accomplish?", a: "It eliminated a major part of Kronos's naval forces and killed many monsters — but it could not stop the main assault that was already being planned." },
            { q: "How did Beckendorf's death affect Percy and the rest of the camp?", a: "It hit everyone hard — he was well-liked and his sacrifice showed how real and deadly the coming war was going to be." },
          ],
        },
        {
          id: "ch-02",
          number: 2,
          title: "The River Styx",
          listenFor: "What is the one spot where Percy can still be hurt?",
          questions: [
            { q: "What plan did Nico propose to make Percy nearly indestructible for the final battle?", a: "He suggested Percy bathe in the River Styx — the same thing Achilles had done — which would make his entire body nearly invulnerable." },
            { q: "What happened to Percy when he submerged himself in the River Styx?", a: "He felt the worst pain of his life as the Styx's power swept through him — it felt like being burned and frozen simultaneously." },
            { q: "What was the one spot that remained vulnerable after Percy's bath in the Styx?", a: "The small of his back — the spot he had been thinking of most strongly while in the river, connected to his greatest loyalty." },
            { q: "Why did every person who bathed in the Styx end up with a different weak spot?", a: "The weak spot was tied to what the person was most focused on during the process — their deepest attachment became the point the Styx could not cover." },
            { q: "What did Nico reveal about Percy's weak spot that made it especially significant?", a: "It was tied to Percy's greatest flaw — his fierce loyalty to the people he loved — meaning an enemy who knew this could use it to destroy him." },
          ],
        },
        {
          id: "ch-03",
          number: 3,
          title: "Typhon and the Gods Depart",
          listenFor: "Why does Olympus end up completely undefended?",
          questions: [
            { q: "Who was Typhon, and why was he considered the most terrifying monster in Greek mythology?", a: "The father of most monsters — a creature so powerful that even the Olympian gods were afraid of him and had barely defeated him in ancient times." },
            { q: "Where did Typhon appear, and what was he doing?", a: "He rose in the American south and began marching toward New York, destroying everything in his path — Kronos had deliberately unleashed him as a distraction." },
            { q: "Why did all the Olympian gods leave New York to fight Typhon?", a: "Typhon posed such a massive direct threat that the gods felt they had no choice — they had to fight him themselves, leaving Olympus completely undefended." },
            { q: "How did Kronos's plan use Typhon as a distraction?", a: "While every god was focused on fighting Typhon across the country, Kronos and his forces were free to march on an unguarded Olympus in New York." },
            { q: "What did Percy understand about the situation when the gods left?", a: "That the demigods would have to defend Manhattan and Olympus entirely on their own — there would be no divine help until the gods defeated Typhon, if they could." },
          ],
        },
        {
          id: "ch-04",
          number: 4,
          title: "Defending Manhattan",
          listenFor: "How do the demigods try to hold back Kronos's army?",
          questions: [
            { q: "What did the campers do with the mortals in Manhattan before the battle began?", a: "Hecate's magic put most of Manhattan's mortal residents into a deep sleep, ensuring they were safely out of the way of the supernatural battle." },
            { q: "How did Percy organise the demigods to defend the city?", a: "He split them into teams to hold key locations — bridges, streets, and approaches to the Empire State Building — slowing the army's march through the city." },
            { q: "How did Percy's Styx-powers change the way he fought in the battle?", a: "He was nearly impossible to injure — he moved through the fighting confidently, able to take hits that would have killed him before and keep going." },
            { q: "What was Kronos's army composed of, and what made it so difficult to fight?", a: "Monsters, Titans, and corrupted demigods — a mix of powerful creatures that kept regenerating or fighting past wounds that should have stopped them." },
            { q: "What important tactical advantage did Percy have by fighting near the rivers and canals of Manhattan?", a: "Water was everywhere in the city — he could draw power from it constantly, healing injuries and boosting his strength throughout the battle." },
          ],
        },
        {
          id: "ch-05",
          number: 5,
          title: "The Spy Revealed",
          listenFor: "Who has been passing information to Luke all along?",
          questions: [
            { q: "What had been happening inside Camp Half-Blood that had helped Luke throughout the war?", a: "A spy had been passing detailed information about camp defences, plans, and personnel to Luke — someone trusted had been betraying everyone." },
            { q: "Who was revealed to be the spy, and why had they done it?", a: "Silena Beauregard, a daughter of Aphrodite, had been the spy — she had been blackmailed by Luke long before the war started and felt she had no way out." },
            { q: "How did the other campers react when Silena's betrayal was revealed?", a: "Clarisse was especially devastated — Silena had been her best friend, and the betrayal felt deeply personal and painful." },
            { q: "What did Silena do to try to make up for her betrayal?", a: "She put on Clarisse's armour and led the Ares cabin into battle herself, pretending to be Clarisse to inspire them — she died fighting bravely." },
            { q: "How did Clarisse respond to Silena's heroic death despite the betrayal?", a: "She was heartbroken but also proud — she fought ferociously in the battle afterwards, driven by both grief and the desire to honour Silena's final act." },
          ],
        },
        {
          id: "ch-06",
          number: 6,
          title: "Ethan's Choice",
          listenFor: "What does Ethan do that costs him his life?",
          questions: [
            { q: "Who was Ethan Nakamura, and which side had he been fighting for?", a: "A son of Nemesis — the goddess of revenge — who had joined Kronos's side because he felt unclaimed demigods were ignored and disrespected by Olympus." },
            { q: "What change came over Ethan during the fighting on Olympus?", a: "He began to doubt Kronos — watching the destruction and realising that Kronos was not actually fighting for demigods but only for the Titans' own power." },
            { q: "What brave act did Ethan perform against Kronos?", a: "He stabbed Kronos in the side, trying to find a weak spot and defying the Titan king directly in the middle of his own stronghold." },
            { q: "What did Kronos do to Ethan after he attacked?", a: "He threw Ethan off the edge of Olympus — Ethan fell to his death for his act of defiance." },
            { q: "What did Ethan's act of rebellion show Percy in the middle of the battle?", a: "That Kronos's control over his followers was not absolute — even those who had joined him could turn, and that gave Percy hope that Luke himself might still be reachable." },
          ],
        },
        {
          id: "ch-07",
          number: 7,
          title: "Luke Breaks Free",
          listenFor: "How does Luke finally defeat Kronos from the inside?",
          questions: [
            { q: "What happened as Percy fought Kronos on Olympus and seemed to be losing?", a: "Annabeth stepped between them and was wounded — and it was seeing Annabeth hurt that seemed to reach something buried deep inside Luke." },
            { q: "What did Annabeth do that helped break Kronos's grip on Luke?", a: "She spoke directly to Luke — not to Kronos — reminding him of who he really was and of the promise he had made her years ago to always be her family." },
            { q: "How did Percy find a way to give Luke the chance to fight back against Kronos?", a: "He handed Luke Annabeth's dagger — a weapon Luke already recognised — instead of fighting Kronos himself, trusting that Luke could do what needed to be done from the inside." },
            { q: "What did Luke do with the dagger Percy gave him?", a: "He stabbed himself in his own Achilles heel spot — driving Kronos out of his body by destroying the vessel the Titan was inhabiting." },
            { q: "What were Luke's final words before he died?", a: "He asked Annabeth if she had ever thought of him as family — and she said yes — and then he was gone, having destroyed Kronos at the cost of his own life." },
          ],
        },
        {
          id: "ch-08",
          number: 8,
          title: "The New Olympus",
          listenFor: "What promise does Percy make the gods swear to keep?",
          questions: [
            { q: "What happened to Typhon after Kronos was defeated on Olympus?", a: "Poseidon's army dragged Typhon into Tartarus, trapping him — the gods returned to New York to find Olympus saved, though badly damaged." },
            { q: "What reward did the Olympian gods offer Percy for saving Olympus?", a: "They offered to make him a god — to give him full immortality and a place among the Olympians as thanks for everything he had done." },
            { q: "What did Percy choose instead of accepting godhood?", a: "He turned it down — he chose to remain a demigod so he could stay with his friends, his mother, and live a real human life." },
            { q: "What important demand did Percy make the gods swear to on the River Styx?", a: "He made them promise to officially claim all their demigod children by the age of thirteen, and to honour the minor gods by giving them proper respect." },
            { q: "Why did Percy's demand about claiming demigod children matter so much?", a: "Because feeling unclaimed and abandoned by their divine parents was exactly what had turned Luke bitter — Percy wanted to make sure no child ever went through that again." },
          ],
        },
      ],
    },
  ],
};

export default percyJackson;
